### ISSUE TITLE
when i called blur view in listener It does not work properly

### ISSUE THREAD

**Issue by abiistar** [Dimezis/BlurView#102]
Please include:
1) Library version
2) Device and OS version
3) Detailed steps to reproduce the issue
4) XML layout and code for BlurView setup
5) Stacktrace in case of a crash

**Comment by abiistar** [comment]
if i called blur view in onCreate method it does work good....but in listener ...nopp

**Comment by Dimezis** [comment]
Provide the data requested in the issue template.

```
Please include:

Library version
Device and OS version
Detailed steps to reproduce the issue
XML layout and code for BlurView setup
Stacktrace in case of a crash
```

And post the code the reproduce the issue.

**Comment by Dimezis** [comment]
Please provide a more detailed report or I'm closing the issue
