### ISSUE TITLE
BlurView overlay color tints the blurred view

### ISSUE THREAD

**Issue by Lucchetto** [Dimezis/BlurView#108]
Please include:
1) 1.6.3
2) Android 10 on Leeco Le Max 2
3) Enable dark mode, open the app, the content is tinted from the overlay color
4) https://github.com/RevengeOS/android_packages_apps_Settings/commit/8865ab783f268fac17f4c070cf8095533c55dd22

Screenshot of the issue: https://pasteboard.co/INtGsfT.png
Here, I have set a solid color as overlay color, and you can see it's tinting the whole blurred view

**Comment by Dimezis** [comment]
It works as intended. Don't use a solid color as an overlay. Pick an alpha you'd like to have an set it
