### ISSUE TITLE
Decreases performance when I use it

### ISSUE THREAD

**Issue by dumitruPuggle** [Dimezis/BlurView#114]
Dear Dimitrii, I have installed your library successfully, it works very well, and looks nice.
Well, here is a problem, it decreases the performance.
So actually this layout is not being used every time in my case, so how can I disable it when it is not used, to increase performance and smoothness

**Comment by Dimezis** [comment]
You can disable the blur auto-update with `setBlurAutoUpdate(false)` or disable blur at all with `setBlurEnabled(false)`.

But if you post your setup (full XML layout, what device are you testing on, what's going on on the screen when the performance is decreasing, etc etc), I might be able to hint you how it can be fixed without disabling it

**Comment by dumitruPuggle** [comment]
Well I'm using a webview and it reallyyyy laggyyy when I use blur
Ahh I used the code just right now still laggy.

**Comment by dumitruPuggle** [comment]
Thank you Dimitrii, I fixed it with
