### ISSUE TITLE
How to make  app:blurOverlayColor with bottom round corner

### ISSUE THREAD

**Issue by kingnightdrifter** [Dimezis/BlurView#115]
Please include:
1) Library version : 1.6.3
2) Device and OS version : All

Hello All,
I am using this blur Dependency which is really helpful for me but at the same time I am getting face a problem with  app:blurOverlayColor . I want to make this blurOverlayColor to round. Because My Toolbar is with round shape.
In this regard I tried many attempts with the Liberary. Add styleable for round but failed.
Anyone please help me. The code snippt is here bellow

`  <eightbitlab.com.blurview.BlurView
        android:id="@+id/topBlurView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:elevation="4dp"
        android:outlineProvider="bounds"
        app:blurOverlayColor="@color/colorOverlay"
        app:roundedCorners="bottomRight|bottomLeft"
        app:cornerRadius="20dp"
        tools:targetApi="lollipop">`

Also the style-able is bellow

`<?xml version="1.0" encoding="utf-8"?>
<resources>
    <declare-styleable name="BlurView">
        <attr name="blurOverlayColor" format="color" />
        <attr name="cornerRadius" format="dimension" />
        <attr name="roundedCorners">
            <flag name="topLeft" value="1" />
            <flag name="topRight" value="2" />
            <flag name="bottomRight" value="4" />
            <flag name="bottomLeft" value="8" />
            <flag name="all" value="15" />
        </attr>
    </declare-styleable>
</resources>`

The java code is

`   private void init(AttributeSet attrs, int defStyleAttr) {
        TypedArray a = getContext().obtainStyledAttributes(attrs, R.styleable.BlurView, defStyleAttr, 0);
        overlayColor = a.getColor(R.styleable.BlurView_blurOverlayColor, TRANSPARENT);
        cornerRadius = a.getDimensionPixelSize(R.styleable.BlurView_roundedCorners, 20);
        roundedCorners = a.getInt(R.styleable.BlurView_cornerRadius, CORNER_NONE);
        a.recycle();
    }`

**Comment by Dimezis** [comment]
There are multiple threads with a solution:
https://github.com/Dimezis/BlurView/issues/37
https://github.com/Dimezis/BlurView/issues/85
