### ISSUE TITLE
BlurView with RecyclerView Adapter inside Fragment does not working

### ISSUE THREAD

**Issue by aravindtechzar** [Dimezis/BlurView#120]
I add blurview for recyclerview adapter for every recyclereview item blur in android fragment.
for android fragment with recyclerview adapter this codes does not work.

internal inner class ViewHolder(itemView : View): RecyclerView.ViewHolder(itemView){
        val announceTitle = itemView.title_text
        val announceTime = itemView.announce_time_ago
        val announceDescription = itemView.announce_description
        val announceImage = itemView.announce_image

        val announceParent = itemView.announce_item_parent_linear
        val blurImage = itemView.blur_layout

}
  override fun onBindViewHolder(holder: RecyclerView.ViewHolder, position: Int) {
          viewHolder.blurImage.setupWith(viewHolder.announceParent)
                .setBlurRadius(radius)
                .setBlurEnabled(true)
                .setBlurAlgorithm(RenderScriptBlur(context))
                .setBlurRadius(radius)
                .setHasFixedTransformationMatrix(true)
                .setBlurAutoUpdate(true)

}

  <LinearLayout
           android:id="@+id/announce_item_parent_linear"
           android:layout_width="match_parent"
           android:layout_height="wrap_content"
           android:orientation="vertical"
           android:layout_gravity="bottom|center_horizontal"
           android:layout_alignParentBottom="true">

           <eightbitlab.com.blurview.BlurView
               android:id="@+id/blur_layout"
               android:layout_width="match_parent"
               android:layout_height="match_parent">

        

     <View
               android:id="@+id/separator"
               android:background="#0f8fc6"
               android:layout_width="match_parent"
               android:layout_height="5dp" />

           <TextView
               android:id="@+id/title_text"
               android:layout_width="match_parent"
               android:layout_height="wrap_content"
               android:layout_marginStart="8dp"
               android:layout_marginTop="8dp"
               android:ellipsize="end"
               android:maxLines="5"
               android:text="Notification header"
               android:textColor="@android:color/white"
               android:textSize="16sp"
               android:textStyle="bold" />

               

           <TextView
               android:id="@+id/announce_description"
               android:layout_width="match_parent"
               android:layout_height="wrap_content"
               android:layout_marginStart="8dp"
               android:layout_marginEnd="8dp"
               android:layout_marginTop="8dp"
               android:layout_marginBottom="16dp"
               android:ellipsize="end"
               android:maxLines="4"
               android:padding="5dp"
               android:layout_below="@+id/title_text"
               android:textColor="@android:color/white"
               android:textSize="16sp" />

           </eightbitlab.com.blurview.BlurView>

       </LinearLayout>

**Comment by Dimezis** [comment]
It's a bad idea overall to have a BlurView in each list item.
Please refer to the documentation, you need to set setHasFixedTransformationMatrix to false and set the appropriate parent view to start blurring from

**Comment by aravindtechzar** [comment]
I can't add the parent view inside onBindViewHolder

**Comment by Dimezis** [comment]
Of course you can, just pass it in the constructor

**Comment by aravindtechzar** [comment]
Recyclerview child items background not get blured

internal inner class ViewHolder(itemView : View): RecyclerView.ViewHolder(itemView){
        val announceTitle = itemView.title_text
        val announceTime = itemView.announce_time_ago
        val announceDescription = itemView.announce_description
        val announceImage = itemView.announce_image
        val announceParent = itemView.announce_item_parent_linear  //appropriate parent layout
        val blurImage = itemView.blur_layout
}

override fun onBindViewHolder(holder: RecyclerView.ViewHolder, position: Int) {

 viewHolder.blurImage.setupWith(viewHolder.announceParent)
                .setBlurRadius(radius)
                .setBlurEnabled(true)
                .setBlurAlgorithm(RenderScriptBlur(context))
                .setBlurRadius(radius)
                .setHasFixedTransformationMatrix(false)
                .setBlurAutoUpdate(true)

}

**Comment by Dimezis** [comment]
As I said, pass a proper parent View to the BlurView.
What you're trying to do just can't work and doesn't make any sense.
Also move the BlurView setup to the ViewHolder constructor, otherwise it will recreate the bitmap each time the ViewHolder gets bound
