### ISSUE TITLE
Migrate to Androidx so library users can drop jetifier

### ISSUE THREAD

**Issue by 0rp3u** [Dimezis/BlurView#122]
Library version: all including 1.6.3
Device and OS version: Any
Detailed steps to reproduce the issue:  iclude library in project, configure and run https://github.com/plnice/can-i-drop-jetifier
XML layout and code for BlurView setup: any valid XML view

Cannot drop Jetifier due to following external dependencies:
* com.eightbitlab:blurview:1.6.3

I am requesting that we migrate to Androidx so library users can drop jetifier, improving build times, on big projects this is essential: https://adambennett.dev/2020/08/disabling-jetifier/
best regards,
David

**Comment by Dimezis** [comment]
Migrated. Thanks @danielwilson1702 for the PR
