### ISSUE TITLE
I have a problem with Blur

### ISSUE THREAD

**Issue by FlowerFF** [Dimezis/BlurView#123]
Please include:
1) Library version ：
1.6.4
2) Device and OS version ：
Virtual device Pixel 2 XL API29
3) Detailed steps to reproduce the issue：
I used the sample code in the README, and the program did not crash, but it did not seem to meet my expectations. I used ConstraintLayout as the rootview, which contained three views. Blur successfully processed the blur of ConstraintLayout, but it contained The three views are not working, how can I fix it?
4) XML layout and code for BlurView setup
![QQ图片20201011095939](https://user-images.githubusercontent.com/33564254/95668576-8cd34780-0ba8-11eb-8b8d-bbc3417a9975.png)
![QQ图片20201011100036](https://user-images.githubusercontent.com/33564254/95668582-a1afdb00-0ba8-11eb-8ab5-1a4d6c71b145.png)
![QQ图片20201011100124](https://user-images.githubusercontent.com/33564254/95668598-c015d680-0ba8-11eb-874d-2b75aaeb0e34.png)

**Comment by Dimezis** [comment]
You're misusing it.
If you nest those views into the BlurView, they will be drawn as is.
Pay attention on how it's used in the example project.
If you want to blur something, just put a BlurView on top of that view.
If you don't want to blur some other part, nest it into the BlurView, or don't include it into the ViewGroup you're passing to the BlurView.setUpWith()

**Comment by FlowerFF** [comment]
> You're misusing it.
> If you nest those views into the BlurView, they will be drawn as is.
> Pay attention on how it's used in the example project.
> If you want to blur something, just put a BlurView on top of that view.
> If you don't want to blur some other part, nest it into the BlurView, or don't include it into the ViewGroup you're passing to the BlurView.setUpWith()

OK，Thanks
