### ISSUE TITLE
Blur not applied with postDelayed 

### ISSUE THREAD

**Issue by ssadovnikov** [Dimezis/BlurView#13]
When you try to apply blur with some delay it will not applied while you touch the screen.

**Comment by Dimezis** [comment]
Didn't get the point.
How do you "apply blur"? Why do you delay it and why do you expect it to be applied if you delayed it?

**Comment by ssadovnikov** [comment]
```
mBlurView.postDelayed(new Runnable() {
		@Override
		public void run() {
                final View decorView = getActivity().getWindow().getDecorView();
                final View rootView = decorView.findViewById(android.R.id.content);
                final Drawable windowBackground = decorView.getBackground();
                mBlurView.setupWith(rootView)
                        .windowBackground(windowBackground)
                        .blurAlgorithm(new StackBlur(true)) 
                        .blurRadius(RADIUS);
            }
        }, DEFAULT_ANIMATION_DURATION);
```
Where DEFAULT_ANIMATION_DURATION is some constant. In my case it is 300ms

**Comment by Dimezis** [comment]
Why don't you just call `mBlurView.updateBlur()` inside postDelayed?

**Comment by ssadovnikov** [comment]
If you init BlurView immediately in fragment and add this fragment with animation, it will break an animation.

**Comment by Dimezis** [comment]
I see, I don't suggest you to init and show it immediately. I suggest you to do this:

```
mBlurView.postDelayed(new Runnable() {
        @Override
        public void run() {
                final View decorView = getActivity().getWindow().getDecorView();
                final View rootView = decorView.findViewById(android.R.id.content);
                final Drawable windowBackground = decorView.getBackground();
                mBlurView.setupWith(rootView)
                        .windowBackground(windowBackground)
                        .blurAlgorithm(new StackBlur(true)) 
                        .blurRadius(RADIUS);

                mBlurView.updateBlur();
            }
        }, DEFAULT_ANIMATION_DURATION);
```

**Comment by ssadovnikov** [comment]
I'll check your solution and let you know  how it works.

**Comment by anass05** [comment]
for the release 1.6.1 this how i was able to animate the blur view
`final ValueAnimator animator = ValueAnimator.ofFloat(.1f, 10f);
                animator.setInterpolator(new DecelerateInterpolator());
                animator.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
                    @Override
                    public void onAnimationUpdate(ValueAnimator animation) {
                        blurView.setBlurRadius((float) animator.getAnimatedValue());
                        blurView.invalidate();
                    }
                });
                animator.setDuration(900);
                animator.start();`

**Comment by Dimezis** [comment]
@anass05 wrong thread?
