### ISSUE TITLE
How can I use BlurView for Custom Spinner dropdown item? 

### ISSUE THREAD

**Issue by greatkub** [Dimezis/BlurView#131]
For now, I can blur only the Spinner.
<img width="412" alt="Screen Shot 2564-01-17 at 22 42 58" src="https://user-images.githubusercontent.com/71839217/104848006-9db4f700-5915-11eb-9a90-0e9d4a23c2ec.png">

Can it be like this?
<img width="662" alt="Screen Shot 2564-01-17 at 22 57 28" src="https://user-images.githubusercontent.com/71839217/104848437-87a83600-5917-11eb-9350-31237245be0e.png">

Some of my code:
  
activity_main.xml

                  <eightbitlab.com.blurview.BlurView
                       android:id="@+id/blurspinner"
                       android:layout_width="wrap_content"
                       android:layout_height="wrap_content"
                       android:background="@drawable/background"
                       app:layout_constraintBottom_toBottomOf="parent"
                       app:layout_constraintLeft_toLeftOf="parent"
                       app:layout_constraintRight_toRightOf="parent"
                       app:layout_constraintTop_toTopOf="parent" >
                           <Spinner
                           android:id="@+id/spinner"
                           android:layout_width="277.5dp"
                           android:layout_height="wrap_content"
                           android:entries="@array/list"
                           android:paddingRight="10dp"
                           android:spinnerMode="dropdown"
                           android:popupBackground="@drawable/bg_dropdownlist"
                           android:dropDownWidth="277.5dp"
                           android:dropDownVerticalOffset="45dp"/>

                   </eightbitlab.com.blurview.BlurView>

custom_spinner.xml

               <?xml version="1.0" encoding="utf-8"?>
                <TextView
                    xmlns:android="http://schemas.android.com/apk/res/android"
                    android:id="@android:id/text1"
                    style="?attr/spinnerDropDownItemStyle"
                    android:singleLine="true"
                    android:layout_width="match_parent"
                    android:layout_height="?attr/dropdownListPreferredItemHeight"
                    android:ellipsize="marquee"
                    android:textColor="@android:color/white"
                    android:textSize="14dp"
                    android:background="@drawable/abc_spinner_mtrl_am_alpha"
                    android:backgroundTint="@android:color/white"/>

custom_spinner_dropdown.xml

            <?xml version="1.0" encoding="utf-8"?> 
            <TextView
                 xmlns:android="http://schemas.android.com/apk/res/android"
                 android:id="@android:id/text1"
                 style="?attr/spinnerDropDownItemStyle"
                 android:singleLine="true"
                 android:layout_width="match_parent"
                 android:layout_height="wrap_content"
                 android:textSize="14dp"
                 android:ellipsize="marquee"
                 android:textColor="@color/white"
                 android:background="@drawable/bg_dropdownlist" />

My MainActivity

        val adapter = ArrayAdapter(
            this,
            R.layout.custom_spinner,
            resources.getStringArray(R.array.list)
        )
        adapter.setDropDownViewResource(R.layout.custom_spinner_dropdown)
        spinner.adapter = adapter

        spinner.onItemSelectedListener = object : OnItemSelectedListener {
            override fun onItemSelected(
                adapterView: AdapterView<*>?,
                view: View,
                position: Int,
                l: Long
            ) {

                val selectedItem = spinner.getItemAtPosition(position).toString()
                Toast.makeText(applicationContext, selectedItem, Toast.LENGTH_LONG).show()
            }

            override fun onNothingSelected(adapterView: AdapterView<*>?) {

            }
        }

**Comment by Dimezis** [comment]
Spinner's dropdown is a separate `PopupWindow`, so it's not present in the parent BlurView.
You need to write your own Spinner that will behave like a normal View

**Comment by greatkub** [comment]
Thank you for your quick response.
