### ISSUE TITLE
Bintray (incl. JCenter) will shutdown on May 1st

### ISSUE THREAD

**Issue by Marc-JB** [Dimezis/BlurView#134]
JFrog announced that Bintray (including JCenter) will shutdown on May 1st: [https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). This means that recent versions of this library won't be available from JCenter after that date.
  
**Affected library versions**: 1.3.4, 1.5.0, 1.6.0 to 1.6.5 (https://mvnrepository.com/artifact/com.eightbitlab/blurview?repo=jcenter)
  
Will this library be available on other solutions, like Maven Central? Or do you recommend the usage of [JitPack](https://jitpack.io/#Dimezis/BlurView)?

**Comment by Dimezis** [comment]
I will make sure the library is properly migrated to some other repository, but I haven't yet investigated it, so can't say where exactly.
Thanks for a heads up though

**Comment by Dimezis** [comment]
Alright, so the problem with Maven Central is that it requires a package domain ownership verification, I don't really want to register a domain for the sake of publishing a library.

So I suppose JitPack is the way to go, using release tags as stable artifacts.
Also, it doesn't require any support from my side which is great

**Comment by muhammedyalcin** [comment]
I think project JCenter dependencies also needs to be migrated if any exist

**Comment by pke** [comment]
Would it be possible to build from source to have ZERO dependency on some badly managed 3rd party artefact repository?

**Comment by Dimezis** [comment]
@pke I suppose you mean jitpack is badly managed?
I have no experience with it, so if you have some alternatives that don't require domain registration, I can consider them.

Answering your question, building from source should be as straightforward as it gets, since there are barely any deps at all. All releases were tagged and the source is buildable

**Comment by pke** [comment]
with badly managed 3rd party repo I meant jfrog :) Running it out of business out of the blue I consider bad management.
I have no experience with jitpack, or any artifact repos in general. I was always bundling my dependencies with the source tree directly in the years I did Java (OSGi).

**Comment by dmackinn** [comment]
Is the move from jcenter to jitpack still going to happen?

**Comment by Dimezis** [comment]
@dmackinn Jitpack doesn't require anything to do from my side, you can already use it as described on their landing
