### ISSUE TITLE
Is it possible to use BlurView with a Snackbar?

### ISSUE THREAD

**Issue by elizavetamikhailova** [Dimezis/BlurView#137]
Hello! I want to use blurView as a background for my snackbar. I configure my snackbar background like this:

    private fun createSnackbar(length: Int) {
        snackBar = Snackbar.make(view, "", length)
        val layout = snackBar.view as Snackbar.SnackbarLayout
        layout.findViewById<TextView>(com.google.android.material.R.id.snackbar_text).visibility =
            View.INVISIBLE
        layout.setBackgroundColor(Color.TRANSPARENT)
        layout.addView(snackView.root, 0)
        snackView.blurView.apply {
            if (isL()) {
                outlineProvider = ViewOutlineProvider.BACKGROUND
                clipToOutline = true
            }
            background = createGradientDrawable(R.color.uikit_neutral_100_50)
        }
        if (isJ1())
            setupBlurBackground()
    }

And I configure blurView like this:

    @RequiresApi(Build.VERSION_CODES.JELLY_BEAN_MR1)
    private fun setupBlurBackground() {
        snackView.root.post {
            snackView.blurView
                .setupWith(snackView.root.parent as ViewGroup)
                .setBlurAlgorithm(RenderScriptBlur(context))
                .setBlurRadius(blurRadius)
                .setBlurAutoUpdate(true)
                .setHasFixedTransformationMatrix(false)
                .setBlurEnabled(true)
        }
    }

But it doesn't work, and BlurView doesn't blur anything :( 
<img width="360" alt="Снимок экрана 2021-03-15 в 17 57 49" src="https://user-images.githubusercontent.com/44157370/111173766-f6bca680-85b7-11eb-844f-3f49b4170cfa.png">
I'm trying to figure out why this doesn't work and can I get it to work?

**Comment by Dimezis** [comment]
Could you try replacing `.setupWith(snackView.root.parent as ViewGroup)` with the root of your activity/fragment?

I guess the problem is that this particular ViewGroup `snackView.root.parent` might not have any background? 
You can also debug what `snackView.root.parent` is referencing exactly to be sure

**Comment by elizavetamikhailova** [comment]
Yes it worked! Thank you very much!
