### ISSUE TITLE
Strange Blur Background

### ISSUE THREAD

**Issue by ShahabGT** [Dimezis/BlurView#143]
hi, I'm trying to use your library to blur the bottom navigation view ( on both standard and support versions). this happens: any ideas?
![Screenshot_1620564824](https://user-images.githubusercontent.com/25537966/117573262-284f7b00-b0ec-11eb-8007-5b7a248c1981.png)

`<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/main_main"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <androidx.fragment.app.FragmentContainerView
        android:id="@+id/main_container"
        android:name="androidx.navigation.fragment.NavHostFragment"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:defaultNavHost="true"
        app:navGraph="@navigation/main_nav" />

    <eightbitlab.com.blurview.BlurView
        android:id="@+id/blurView"
        android:outlineProvider="bounds"
        app:blurOverlayColor="@color/overlay"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom">

        <com.google.android.material.bottomnavigation.BottomNavigationView
            android:id="@+id/main_bnv"
            android:layout_width="match_parent"
            android:layout_height="70dp"
            android:background="@android:color/transparent"
            app:itemIconTint="@color/main_bnv_text_light"
            app:itemTextColor="@color/main_bnv_text_light"
            app:labelVisibilityMode="labeled"
            app:menu="@menu/main_bnv_menu" />
    </eightbitlab.com.blurview.BlurView>
</FrameLayout>`

`
b.blurView.setupWith(b.mainMain as ViewGroup)
.setFrameClearDrawable(window.decorView.background)
.setBlurAlgorithm(RenderScriptBlur(this))
.setBlurRadius(25f)
.setHasFixedTransformationMatrix(true)
`

**Comment by Dimezis** [comment]
I don't think it's because of the BlurView.
You have elevation on the bottom bar and a transparent background color. It usually results in this kind of artifacts

**Comment by ShahabGT** [comment]
thanks for the quick reply. there is no elevation on bnv. I also check it with custom background, without it, with transparent background, and also with @null.  unfortunately non of them work

**Comment by Dimezis** [comment]
It does have some sort of implicit elevation, not in the layout you posted, but in the sources of the BNV. 
Setting `app:elevation="0dp"` should help (specifically with `app` namespace)

**Comment by ShahabGT** [comment]
unfortunately, it didn't work, but finally, I managed to make it work by making this the bnv background

`<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:padding="10dp"
    android:shape="rectangle">

    <solid android:color="#00000000" />

</shape>`
