### ISSUE TITLE
Blur the background of a Navigation Drawer

### ISSUE THREAD

**Issue by ezechuka** [Dimezis/BlurView#144]
Library version: implementation 'com.eightbitlab:blurview:1.6.6'

Trying to blur the background of the navigation drawer, but the blur is not enough
[![Screenshot_20210521-001152](https://user-images.githubusercontent.com/35205214/119060259-c0414480-b9c9-11eb-9102-86a0d7bfcd69.png)](url)

**blurview step**
` val decorView = requireActivity().window.decorView
        val rootView = decorView.findViewById(android.R.id.content) as ViewGroup

        binding.blurView.setupWith(drawerLayout)
            .setFrameClearDrawable(decorView.background)
            .setBlurAlgorithm(RenderScriptBlur(requireContext()))
            .setBlurRadius(32f)
            .setBlurAutoUpdate(true)
            .setHasFixedTransformationMatrix(true) 
`

**xml layout**
`<?xml version="1.0" encoding="utf-8"?>
<androidx.drawerlayout.widget.DrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/drawer"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    tools:context=".ui.home.HomeFragment"
    tools:openDrawer="start">

    <androidx.constraintlayout.widget.ConstraintLayout
        android:id="@+id/main_home"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@drawable/splash_image">

        <androidx.appcompat.widget.Toolbar
            android:id="@+id/toolBar"
            android:layout_width="0dp"
            app:layout_constraintTop_toTopOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            android:layout_height="wrap_content"
            android:paddingHorizontal="8dp"
            android:paddingTop="24dp"
            android:background="@android:color/transparent"
            android:theme="@style/Theme.Easychop.Toolbar"
            android:minHeight="?attr/actionBarSize" />

        <TextView
            android:id="@+id/greetings"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginStart="24dp"
            android:layout_marginTop="90dp"
            android:fontFamily="@font/gotham_light"
            android:text="Welcome!"
            android:textAlignment="center"
            android:textColor="@android:color/white"
            android:textSize="16sp"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent" />

        <TextView
            android:id="@+id/username"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:fontFamily="@font/gotham_medium"
            android:text="Onyedika"
            android:textColor="@android:color/white"
            android:textSize="24sp"
            android:textStyle="bold"
            app:layout_constraintStart_toStartOf="@id/greetings"
            app:layout_constraintTop_toBottomOf="@id/greetings" />

        <com.google.android.material.card.MaterialCardView
            android:id="@+id/order_food_section"
            android:layout_width="match_parent"
            android:layout_height="125dp"
            android:layout_marginStart="24dp"
            android:layout_marginTop="28dp"
            android:layout_marginEnd="24dp"
            android:clickable="true"
            android:focusable="true"
            app:cardCornerRadius="12dp"
            app:layout_constraintStart_toStartOf="@id/greetings"
            app:layout_constraintTop_toBottomOf="@id/username"
            app:rippleColor="@android:color/darker_gray">

            <RelativeLayout
                android:layout_width="match_parent"
                android:layout_height="match_parent">

                <ImageView
                    android:id="@+id/order_food_image"
                    android:layout_width="100dp"
                    android:layout_height="100dp"
                    android:layout_alignParentStart="true"
                    android:layout_centerVertical="true"
                    android:src="@drawable/first_onboarding_image" />

                <TextView
                    android:id="@+id/order_food_title"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_alignTop="@id/order_food_image"
                    android:layout_marginStart="7dp"
                    android:layout_marginTop="16dp"
                    android:layout_toEndOf="@id/order_food_image"
                    android:fontFamily="@font/gotham_medium"
                    android:text="@string/order_food"
                    android:textColor="@android:color/white"
                    android:textSize="24sp"
                    android:textStyle="bold" />

                <TextView
                    android:id="@+id/order_food_desc"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_below="@id/order_food_title"
                    android:layout_alignStart="@id/order_food_title"
                    android:layout_alignEnd="@id/order_food_title"
                    android:layout_marginStart="4dp"
                    android:layout_marginTop="4dp"
                    android:lineSpacingExtra="4dp"
                    android:fontFamily="@font/gotham_medium"
                    android:text="@string/order_food_desc"
                    android:textColor="@android:color/white"
                    android:textSize="12sp" />

                <ImageView
                    android:layout_width="24dp"
                    android:layout_height="24dp"
                    android:layout_below="@id/order_food_desc"
                    android:layout_alignEnd="@id/order_food_title"
                    android:src="@drawable/arrow"
                    app:tint="@android:color/white" />

            </RelativeLayout>

        </com.google.android.material.card.MaterialCardView>

        <com.google.android.material.card.MaterialCardView
            android:id="@+id/groceries_section"
            android:layout_width="match_parent"
            android:layout_height="125dp"
            android:layout_marginStart="24dp"
            android:layout_marginTop="28dp"
            android:layout_marginEnd="24dp"
            android:clickable="true"
            android:focusable="true"
            app:cardCornerRadius="12dp"
            app:layout_constraintStart_toStartOf="@id/greetings"
            app:layout_constraintTop_toBottomOf="@id/order_food_section"
            app:rippleColor="@android:color/darker_gray">

            <RelativeLayout
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:paddingStart="24dp">

                <ImageView
                    android:id="@+id/groceries_image"
                    android:layout_width="105dp"
                    android:layout_height="100dp"
                    android:scaleType="fitXY"
                    android:layout_marginEnd="-8dp"
                    android:layout_alignParentEnd="true"
                    android:layout_centerVertical="true"
                    android:src="@drawable/second_onboarding_image" />

                <TextView
                    android:id="@+id/groceries_title"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_alignTop="@id/groceries_image"
                    android:layout_marginTop="16dp"
                    android:layout_marginEnd="7dp"
                    android:layout_toStartOf="@id/groceries_image"
                    android:fontFamily="@font/gotham_medium"
                    android:text="@string/groceries"
                    android:textColor="@android:color/white"
                    android:textSize="24sp"
                    android:textStyle="bold" />

                <TextView
                    android:id="@+id/groceries_desc"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_below="@id/groceries_title"
                    android:layout_alignStart="@id/groceries_title"
                    android:layout_alignEnd="@id/groceries_title"
                    android:layout_marginTop="4dp"
                    android:lineSpacingExtra="4dp"
                    android:fontFamily="@font/gotham_medium"
                    android:text="@string/groceries_home_desc"
                    android:textColor="@android:color/white"
                    android:textSize="12sp" />

                <ImageView
                    android:layout_width="24dp"
                    android:layout_height="24dp"
                    android:layout_below="@id/groceries_desc"
                    android:layout_alignStart="@id/groceries_title"
                    android:src="@drawable/arrow"
                    app:tint="@android:color/white" />

            </RelativeLayout>

        </com.google.android.material.card.MaterialCardView>

        <com.google.android.material.card.MaterialCardView
            android:id="@+id/dispatch_rider_section"
            android:layout_width="match_parent"
            android:layout_height="125dp"
            android:layout_marginStart="24dp"
            android:layout_marginTop="28dp"
            android:layout_marginEnd="24dp"
            android:clickable="true"
            android:focusable="true"
            app:cardCornerRadius="12dp"
            app:layout_constraintStart_toStartOf="@id/greetings"
            app:layout_constraintTop_toBottomOf="@id/groceries_section"
            app:rippleColor="@android:color/darker_gray">

            <RelativeLayout
                android:layout_width="match_parent"
                android:layout_height="match_parent">

                <ImageView
                    android:id="@+id/dispatch_rider_image"
                    android:layout_width="100dp"
                    android:layout_height="100dp"
                    android:layout_alignParentStart="true"
                    android:layout_centerVertical="true"
                    android:src="@drawable/third_onboarding_image" />

                <TextView
                    android:id="@+id/dispatch_rider_title"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_alignTop="@id/dispatch_rider_image"
                    android:layout_marginStart="4dp"
                    android:layout_marginTop="16dp"
                    android:layout_toEndOf="@id/dispatch_rider_image"
                    android:fontFamily="@font/gotham_medium"
                    android:text="@string/dispatch_rider_title"
                    android:textColor="@android:color/white"
                    android:textSize="24sp"
                    android:textStyle="bold" />

                <TextView
                    android:id="@+id/dispatch_rider_desc"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:lineSpacingExtra="4dp"
                    android:layout_below="@id/dispatch_rider_title"
                    android:layout_alignStart="@id/dispatch_rider_title"
                    android:layout_alignEnd="@id/dispatch_rider_title"
                    android:layout_marginStart="4dp"
                    android:layout_marginTop="4dp"
                    android:fontFamily="@font/gotham_medium"
                    android:text="Order a dispatch rider to run your errands."
                    android:textColor="@android:color/white"
                    android:textSize="12sp" />

                <ImageView
                    android:layout_width="24dp"
                    android:layout_height="24dp"
                    android:layout_below="@id/dispatch_rider_desc"
                    android:layout_alignEnd="@id/dispatch_rider_title"
                    android:src="@drawable/arrow"
                    app:tint="@android:color/white" />

            </RelativeLayout>

        </com.google.android.material.card.MaterialCardView>

    </androidx.constraintlayout.widget.ConstraintLayout>

    <eightbitlab.com.blurview.BlurView
        android:id="@+id/blurView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:blurOverlayColor="@android:color/darker_gray">

    </eightbitlab.com.blurview.BlurView>

    <com.google.android.material.navigation.NavigationView
        android:id="@+id/nav_view"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:layout_gravity="start"
        android:background="@drawable/nav_drawer_bg"
        app:headerLayout="@layout/nav_header"
        app:itemBackground="@drawable/menu_item_padding"
        app:itemHorizontalPadding="36dp"
        app:itemIconPadding="24dp"
        app:itemIconSize="20dp"
        app:itemIconTint="@android:color/darker_gray"
        app:itemTextAppearance="@style/Theme.Easychop.NavbarTextAppearance"
        app:itemTextColor="@android:color/white"
        app:menu="@menu/easy_chop_menu_items" >
        
        <LinearLayout
            android:layout_width="match_parent"
            android:orientation="vertical"
            android:layout_gravity="bottom"
            android:layout_marginBottom="72dp"
            android:layout_height="wrap_content">

            <com.google.android.material.button.MaterialButton
                android:layout_width="match_parent"
                android:text="@string/logout"
                style="@style/Theme.Easychop.MaterialButton"
                android:layout_marginHorizontal="24dp"
                app:strokeWidth="2dp"
                app:strokeColor="#707070"
                android:background="@drawable/logout_button_bg"
                android:layout_height="wrap_content" />

            <com.google.android.material.button.MaterialButton
                android:layout_width="match_parent"
                android:text="@string/vendor"
                style="@style/Theme.Easychop.MaterialButton"
                app:icon="@drawable/arrow"
                app:iconGravity="textEnd"
                app:iconSize="22dp"
                app:iconTint="@android:color/white"
                android:layout_marginTop="64dp"
                android:background="@drawable/rounded"
                android:layout_marginHorizontal="24dp"
                android:layout_height="wrap_content" />

        </LinearLayout>

    </com.google.android.material.navigation.NavigationView>

</androidx.drawerlayout.widget.DrawerLayout>`

**Comment by Dimezis** [comment]
Max blur radius is 25, with blur radius 32 it should just crash. Is this really the code you're running?

**Comment by ezechuka** [comment]
It seems I commented the setup code, but when I uncommented the setup code and used radius of 22f or 20f, I get a dark gray screen not on the navigation drawer but on the drawer layout

**Comment by Dimezis** [comment]
Your BlurView has 0 height - it's `wrap_content` with no content in it.

**Comment by ezechuka** [comment]
When I set it's height to match_parent and set blur radius to 16dp, with `drawerLayout` as the rootView it blurs the whole screen. what I want is to blur only the background of the navigation view.
Thanks

**Comment by Dimezis** [comment]
Next time please be more specific. 
You are posting a screenshot with no blur, saying "blur is not enough", and now it turns out it blurs the whole screen and the problem is completely elsewhere.

Just put your BlurView inside of the `NavigationView` so it's in the drawer itself, not in the root

**Comment by Dimezis** [comment]
Also please set this to false `setHasFixedTransformationMatrix(false)`, since it's going to be animated

**Comment by Dimezis** [comment]
It probably won't cover the menu items though, so you will have to either set them manually or figure out how to put them inside of the BlurView

**Comment by ezechuka** [comment]
If I should put the blur view inside of the navigation view and make the nav view as the rootview it'll blur the items too right?

**Comment by Dimezis** [comment]
BlurView blurs every View inside of `setUpWith(root)` root, except of those that are the children of the BlurView itself.
Plan your layout accordingly

**Comment by ezechuka** [comment]
Yeah, I got that, but I can put the menu items of the navigation view inside of blurView because I have no control over the menu layout

**Comment by Dimezis** [comment]
Can't help with that unfortunately

**Comment by ezechuka** [comment]
I just did it with your help.
I put the navigation view inside blurView and set the root to drawerLayout and it worked
