### ISSUE TITLE
No blurring on Galaxy S10, Android 11

### ISSUE THREAD

**Issue by Michael-Liutov** [Dimezis/BlurView#145]
1) Library version:
 1.6.6
2) Device and OS version: 
Samsung Galaxy S10, Android 11
3) Detailed steps to reproduce the issue:
Open the screen where the BlurView should be. There is no blur, only overlay color. The problem doesn't happen on other devices with Android 11 (or other versions of Android), seems to be a problem with Galaxy S10 specifically.
4) XML layout and code for BlurView setup
XML layout element:
```
<eightbitlab.com.blurview.BlurView
            android:id="@+id/blurView"
            android:layout_width="0dp"
            android:layout_height="90dp"
            app:blurOverlayColor="#80E8EBF3"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent" />
```

Code setup:
 ```
        val decorView: View = requireActivity().window.decorView
        val rootView = decorView.rootView as ViewGroup
        val windowBackground = decorView.background
        dataBinding.blurView.setupWith(rootView)
            .setFrameClearDrawable(windowBackground)
            .setBlurAlgorithm(RenderScriptBlur(requireContext()))
            .setBlurRadius(10f)
            .setBlurAutoUpdate(true)
```

**Comment by Dimezis** [comment]
Is the Fragment you're having BlurView in attached straight away in Activity's onCreate, or you add it dynamically later?

**Comment by Michael-Liutov** [comment]
I'm using Navigation component, so it's loaded by nav controller

**Comment by Dimezis** [comment]
Alright, and could you also tell me in what lifecycle callback you initialize the BlurView?

**Comment by Michael-Liutov** [comment]
In the `onViewCreated`, and the fragment is a `DialogFragment`

**Comment by Dimezis** [comment]
Thanks. 
I have S10 with Android 11, so will check later what's going on

**Comment by Michael-Liutov** [comment]
I've noticed now that putting the app to the background and re-opening it makes the blur appear. But still, on every start of the app there's just overlay color.

**Comment by Dimezis** [comment]
I quickly sketched a setup with a DialogFragment (without Navigation component though), but couldn't reproduce this bug.
If you could make a repo with the smallest possible example illustrating this issue, it would help me a lot

**Comment by Michael-Liutov** [comment]
Will prepare a repo during the weekends. Looks like the issue is some race condition, because sometimes the blur does appear even on first launch, but most of the time it doesn't.

**Comment by Michael-Liutov** [comment]
Unfortunately, I wasn't able to reproduce the issue with some small example.

**Comment by Dimezis** [comment]
Ok, if you could debug it on the broken setup, the order of these events could give me a hint:
`Fragment.onViewCreated`
`Fragment.onResume`
`BlurView.onDetachedFromWindow`
`BlurView.onAttachedToWindow`
`BlurView.setupWith`
`BlurView.onSizeChanged`

If you also call

**Comment by Michael-Liutov** [comment]
The order is like this:
onViewCreated
setupWith
onResume
onAttachedToWindow
onSizeChanged

But I'm not getting the issue anymore, the blur works every time. Maybe a restart of the phone helped or something. If it appears again, I'll provide you with details (perhaps the order of these events will change).
