### ISSUE TITLE
ReyclerView item background blur not working

### ISSUE THREAD

**Issue by tnt-ndricimh** [Dimezis/BlurView#147]
recycler_view_item.xml
```
<layout>
         <eightbitlab.com.blurview.BlurView
                      android:id="@+id/blurView"
                      android:layout_width="match_parent"
                      android:layout_height="wrap_content"
                      android:background="@drawable/bg_white_radius_17sdp"
                      android:backgroundTint="@android:color/transparent"
                      app:blurOverlayColor="#29FFFFFF">
            
                      <LinearLayout android:padding="12dp">..some textviews </LinearLayout>
                      
        </eightbitlab.com.blurview.BlurView>
</layout>
```
```
RecyclerView
override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): ViewHolder {
        val binding: ItemReyclerViewBinding = inflate(R.layout.recycler_view_item, parent)
        binding.blurView.setupWith(binding.root as ViewGroup)
            .setBlurAlgorithm(RenderScriptBlur(binding.root.context))
            .setBlurRadius(2f)
            .setBlurAutoUpdate(true)
            .setHasFixedTransformationMatrix(false)
        binding.blurView.outlineProvider = ViewOutlineProvider.BACKGROUND;
        binding.blurView.clipToOutline = true
        return ViewHolder(binding)
    }
```

Checked some other similar issues but did not found a solution. Also tried setting a constraint layout as parent and then inside it the blurview. I need the background of item to be blurred and the items not.

**Comment by Dimezis** [comment]
>  I need the background of item to be blurred and the items not
I don't see any background in your `recycler_view_item`, there's only BlurView, so there's nothing to be blurred

**Comment by Dimezis** [comment]
If you want to blur the background of your RecyclerView, pass the appropriate parent to `setupWith`, not the item row

**Comment by tnt-ndricimh** [comment]
Even if I have a parent layout inside the item with background (Or an ImageView before blurView together inside a Constraint and the image is set to be blurred) And it set it:  `binding.blurView.setupWith(binding.parent) / binding.image` still not working. I don't need to blur the background of the whole recyclerview. Only the background of the items.
```
<androidx.constraintlayout.widget.ConstraintLayout
        android:id="@+id/parent"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="@drawable/bg_white_radius_17sdp"
        android:backgroundTint="@android:color/transparent">
        
                                  blurView inside 
                                  
         </androidx.constraintlayout.widget.ConstraintLayout>
```

**Comment by Dimezis** [comment]
>   <eightbitlab.com.blurview.BlurView
                      android:id="@+id/blurView"
                      android:layout_width="match_parent"
                      android:layout_height="wrap_content"
                      android:background="@drawable/bg_white_radius_17sdp"
                      android:backgroundTint="@android:color/transparent"
                      app:blurOverlayColor="#29FFFFFF"

But why do you set background and background tint to the BlurView?

Please send a screenshot of what's happening on the screen

**Comment by tnt-ndricimh** [comment]
I user that bg_white_radius_17 somewhere else. So to not create a new resource file I just used backgroundTint to change its color. Blurr effect its not happening. Only the transparency of the` color #29FFFFFF` This is the code of background

```
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle">
    <corners  android:radius="17dp"/>
    <solid android:color="@color/background"/>
</shape>
```


![Blur](https://user-images.githubusercontent.com/79631933/125603654-c05bb284-ac6e-4ee2-8cc0-b29a2a36988f.png)

**Comment by Dimezis** [comment]
> This is the code of background

But there's nothing to blur in this background. It's a solid color, and you set it as a background to both ConstraintLayout and BlurView.

1) Remove the background from the BlurView
2) Send a screenshot of what's happening when you have actually something to blur (ImageView with an image in ConstraintLayout, or a proper background in ConstraintLayout that is not just a solid color)

**Comment by tnt-ndricimh** [comment]
The thing is that the fragment has an background image. I don't need to add an image or something in the item layout. I need the item background to be blurred. Here is a photo of a view with blur in that fragment. I need to have the same thing for the recyclerview items
![Blur1](https://user-images.githubusercontent.com/79631933/125618800-e4e5dfcb-b443-4e03-9e83-4e24cb7e937a.png)

**Comment by Dimezis** [comment]
You should have said that from the very beginning.
You don't need _item_ background to be blurred. You need _Fragment's_ background to be blurred by an _item_.

Pass the root of your Activity to `setupWith` and `setHasFixedTransformationMatrix(true)`

**Comment by tnt-ndricimh** [comment]
Sorry for my bad explanation. It is working now. Thank you for you time
