### ISSUE TITLE
Release 1.6.6 unsuccessfully assembled for jitpack.io 

### ISSUE THREAD

**Issue by kuFEAR** [Dimezis/BlurView#149]
build log https://jitpack.io/com/github/Dimezis/BlurView/version-1.6.6/build.log 

Can you fix build and upload artefacts? 
https://jitpack.io/#Dimezis/BlurView

**Comment by Dimezis** [comment]
`BUILD SUCCESSFUL `
Not sure what to do here

**Comment by kuFEAR** [comment]
maybe just flaky?

**Comment by Dimezis** [comment]
I mean the logs of the failed build say `BUILD SUCCESSFUL`, so that would be weird :)
Seems like I triggered a rebuild, will see what happens next

**Comment by kuFEAR** [comment]
yeah, now it's okay
