### ISSUE TITLE
com.eightbitlab:supportrenderscriptblur not available for JitPack

### ISSUE THREAD

**Issue by brunoaduarte** [Dimezis/BlurView#152]
Hi @Dimezis , I'm removing "jcenter()" from my project but I could not find an alternative repository for 'com.eightbitlab:supportrenderscriptblur:1.0.2'. Is it possible to use it with JitPack ?

I've successfully done this for the BlurView library
`implementation 'com.github.Dimezis:BlurView:version-1.6.6'`

But now i need to do for the "supportrenderscriptblur"
`implementation 'com.eightbitlab:supportrenderscriptblur:1.0.2'`

**Comment by Dimezis** [comment]
https://jitpack.io/docs/BUILDING/
Haven't tried, but I believe you can get it working with something like `com.github.Dimezis.BlurView:supportrenderscriptblur:version-1.6.6`.

**Comment by brunoaduarte** [comment]
> com.github.Dimezis.BlurView:supportrenderscriptblur:version-1.6.6

`Failed to resolve: com.github.Dimezis.BlurView:supportrenderscriptblur:version-1.6.6`

I think a release tag specifically for the "supportrenderscriptblur" is needed.

**Comment by Dimezis** [comment]
There's no such thing as a tag for a module.
Sorry for the confusion, I made a typo, there should be a colon instead of a dot :)
`com.github.Dimezis:BlurView:supportrenderscriptblur:version-1.6.6`

**Comment by Dimezis** [comment]
SupportRenderScript blur is now completely removed, since it was obsolete and not accessible anyway.
If you still need it, you can implement it in your custom `BlurAlgorithm`
