### ISSUE TITLE
View rounding doesn't work if applying specific corner radius

### ISSUE THREAD

**Issue by dxshindeo** [Dimezis/BlurView#154]
If we apply 

`android:radius="30dp"`

then we get round blurred view, but if we only set, ex. top corners to be rounded       

```
android:topLeftRadius="30dp"
android:topRightRadius="30dp"
```

then it results in no corners being rounded.

**Comment by Dimezis** [comment]
That is expected and not BlurView specific.

`clipToOutline` with `background` as outline provider doesn't work with complex shapes as per documentation.
