### ISSUE TITLE
Using with Jetpack Compose

### ISSUE THREAD

**Issue by LorenzoFerri** [Dimezis/BlurView#157]
Hi, I would like to use this library in a Jetpack Compose project however I'm not finding any success. Could you provide a simple `Composable` component that with an `AndroidView` or a `AndroidViewBinding` wrap your library? Thank you

**Comment by Dimezis** [comment]
Not sure if I understand what problem you're having exactly. 
Why can't you wrap it into `AndroidView` yourself?

**Comment by rabross** [comment]
@LorenzoFerri If you are interested `Modifier.blur()` is available in Compose `1.1.0-alpha03` on Android 12

**Comment by LorenzoFerri** [comment]
> @LorenzoFerri If you are interested `Modifier.blur()` is available in Compose `1.1.0-alpha03` on Android 12

I tried that Modifier, but it doesn’t achieve what I need, blurring only the composable itself and not what's behind it.

**Comment by ComposeDesigner** [comment]
@LorenzoFerri 
Did you get this to work using Compose? I am stuck with the same issue!

**Comment by jakub-cosmose** [comment]
I've spent some time trying to achieve the blurring effect in Compose using this library and anything else that I was able to find, but I haven't found any solution. So, currently, migrating my project to Compose is put on hold indefinitely.

**Comment by ComposeDesigner** [comment]
I haven't found a solution either. But I noticed that using @LorenzoFerri's code stops throwing an error if I don't use a Modifier in the AndroidView section. So I wonder if it has something to do with that. I'd love to find a solution to this.

**Comment by tengyeekong** [comment]
It would be really great if BlurView can be used in Jetpack Compose :')

**Comment by SecretKeeper** [comment]
Any updates?

**Comment by Dimezis** [comment]
@SecretKeeper 
I've opened an issue here - https://issuetracker.google.com/issues/232625913
I don't think there's anything reasonable I can do to fix this crash on my side.
The Compose's behavior doesn't look right to me in this case

**Comment by yaokongfave** [comment]
I tried moving the `setupWith` into `update` block and it works, but it only renders for the first time
<img width="675" alt="Screenshot 2022-05-15 at 11 27 40 PM" src="https://user-images.githubusercontent.com/99250614/168480658-85474c07-b1e2-4b2d-b5f1-030e0a1028e1.png">

**Comment by tengyeekong** [comment]
I tried moving the `setupWith` into `update` block and it works, but it only renders for the first time..
<img width="675" alt="Screenshot 2022-05-15 at 11 27 40 PM" src="https://user-images.githubusercontent.com/19898540/168480767-d7a4eb5e-3918-4608-a87f-84b8db30d15f.png">

**Comment by Dimezis** [comment]
> I tried moving the setupWith into update block and it works

Unfortunately, it's probably some (un)lucky quirk of your particular setup, because there's a fundamental problem preventing it from working correctly.
Also, it still crashes for me even with this delayed setup

**Comment by Dimezis** [comment]
Version 2.0.2 _should_ fix this problem, but I'm not sure it's going to be working in every scenario.
But you can try and let me know how it went

**Comment by jianinz** [comment]
Hi @Dimezis, sorry to comment on the closed issue, but I found this is relavent to my question, I am curious about what if the root view is composable? Basically I have a composable that is ready to be used, I just want its background to be blured, I tried to embed BlurView into AndroidView, but how to integrate composable in this case? Could you shed some lights, thanks!


```

@Composable
fun HomeBottomBar(){
// Composable goes here
}

```

```

@Composable
fun AndroidViewBasedCompose(){
    val context = LocalContext.current
    val decorView = context.activity.window.decorView
    val rootView = decorView.findViewById<ViewGroup>(android.R.id.content). //Where can I get this???
    val windowBackground = decorView.background;
    AndroidView(
        modifier = Modifier
            .fillMaxWidth()
            .height(56.dp),
        factory = { context ->
            BlurView(context).apply {
                this.setupWith(rootView)
                    .setFrameClearDrawable(windowBackground)
                    .setBlurAlgorithm(RenderScriptBlur(context))
                    .setBlurRadius(20f)
                    .setBlurAutoUpdate(true)
            }
        }
    )
}

```


```
// Utility function for getting activity ref
fun Context.getActivity(): AppCompatActivity? = when (this) {
    is AppCompatActivity -> this
    is ContextWrapper -> baseContext.getActivity()
    else -> null
}
 ```

**Comment by Dimezis** [comment]
@jianinz I'm not sure if I understand your problem.

> val rootView = decorView.findViewById<ViewGroup>(android.R.id.content). //Where can I get this??? It's a composable in my case

`android.R.id.content` can't be a composable. It's a default ViewGroup present in every Activity.

Your setup looks fine, though I didn't test it.
What's the problem exactly and what happens when you use `AndroidViewBasedCompose`?

**Comment by jianinz** [comment]
@Dimezis Thanks for your quick response! In the example here https://github.com/Dimezis/BlurView#how-to-use, BlurView will have any child view which will not be blured. In my case, the child view will be a composable, I wonder how to integrate that composable into BlurView?

Should I just do something like:

```
              Box {
                HomeBottomBar(
                )
                AndroidViewBasedCompose()
              }
```

**Comment by jianinz** [comment]
If I use code below

```
@Composable
fun AndroidViewBasedCompose(){
    val context = LocalContext.current
    val decorView = context.activity.window.decorView
    val rootView = decorView.findViewById<ViewGroup>(android.R.id.content)
    val windowBackground = decorView.background
    AndroidView(
        modifier = Modifier
            .fillMaxWidth()
            .height(56.dp),
        factory = { context ->
            BlurView(context).apply {
                this.setupWith(rootView)
                    .setFrameClearDrawable(windowBackground)
                    .setBlurAlgorithm(RenderScriptBlur(context)) // No longer available in the version 2.0.3
                    .setBlurRadius(20f)
                    .setBlurAutoUpdate(true)
            }
        }
    )
}
```
```
              Box {
                HomeBottomBar(
                )
                AndroidViewBasedCompose()
              }
```

I don't see the blured view, instead I see the mono background colored bottom bar, no blur effect takes into place

**Comment by Dimezis** [comment]
> Should I just do something like:
...

Yes, although I think the order should be 
```Kotlin
Box {
    AndroidViewBasedCompose()
    HomeBottomBar()                
}
```

And the `HomeBottomBar` has to have a transparent background for the BlurView to be visible

**Comment by jianinz** [comment]
> On second thought, in this case, the BlurView would also include the bottom bar into its blurred content, so that might not be doable in the end.

Yeah, just tried changing order, in the end the blur view does not show up, is there any ways to include the bottom bar into its blurred content?

**Comment by Dimezis** [comment]
>  in the end the blur view does not show up

As I said, the bottom bar composable has to have a transparent background. I don't know if it's adjustable though

**Comment by jianinz** [comment]
> As I said, the bottom bar composable has to have a transparent background. I don't know if it's adjustable though

I set HomeBottomBar's color as transparent and blur view as purple, unfortunately the result is just transparent HomeBottomBar
