### ISSUE TITLE
Dark mode issue

### ISSUE THREAD

**Issue by SiarheiSm** [Dimezis/BlurView#160]
In dark mode some views blurred in original color scheme, and does not use dark colors 
![image](https://user-images.githubusercontent.com/24812695/140937308-57311bef-ec34-48f3-ab7d-79a37bcaa733.png)

**Comment by Dimezis** [comment]
More details, please.

I really doubt this can happen if you configured your BlurView properly.
What's your root? Does it have a background? Do you use `setFrameClearDrawable`?

Post screenshots of unblurred layout as well.

**Comment by SiarheiSm** [comment]
Hi, it seems issue relates to force dark mode 
i've prepared small example, here you can see fullscreen RecyclerView with top item blurred: 
![image](https://user-images.githubusercontent.com/24812695/141118744-cef527e0-71af-4c35-9001-d1ff72a8f170.png)

here the code 
https://drive.google.com/file/d/1T8xQpR6ZxrIR5DfvL7r4dwWbnToM_QyI/view?usp=sharing

**Comment by Dimezis** [comment]
https://developer.android.com/guide/topics/ui/look-and-feel/darktheme#force-dark

Apparently, google uses some hacks to swap the colors during drawing without actually changing the properties of the View.
I can only suggest you to implement a proper dark mode without this flag.
