### ISSUE TITLE
Custom Algorithm ?

### ISSUE THREAD

**Issue by SudoDios** [Dimezis/BlurView#165]
Hello.  
I wanted to know if I can pass a customized algorithm to the **setBlurAlgorithm** parameter?  
For example stackblur in jni c.

**Comment by SudoDios** [comment]
If this library is transferred to **jni**, it will be much better

**Comment by SudoDios** [comment]
I used stackblur in C ++, it gives the best performance if we also make bitmap native

**Comment by Dimezis** [comment]
Yes, you can pass own algorithm there, that's why that method exist

**Comment by SudoDios** [comment]
How to round corner view???

**Comment by Dimezis** [comment]
> How to round corner view???

That's offtopic, but short answer is exactly the same as any other View - https://github.com/Dimezis/BlurView/issues/37
