### ISSUE TITLE
 java.lang.StackOverflowError: stack size 8MB        at android.view.ViewGroup.buildOrderedChildList(ViewGroup.java:3427)        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3313)        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1975)

### ISSUE THREAD

**Issue by kirikaTowa** [Dimezis/BlurView#166]
Please include:
1) Library version
2) Device and OS version
3) Detailed steps to reproduce the issue
4) XML layout and code for BlurView setup
5) Stacktrace in case of a crash

**Comment by kirikaTowa** [comment]
at android.view.View.draw(View.java:15363)
       at android.widget.FrameLayout.draw(FrameLayout.java:647)
       at eightbitlab.com.blurview.BlockingBlurController.updateBlur(BlockingBlurController.java:122)
       at eightbitlab.com.blurview.BlockingBlurController.draw(BlockingBlurController.java:164)

 **rootView.draw(internalCanvas) Seems to be in an endless loop。**

**Comment by Dimezis** [comment]
Please fill in the required details properly

**Comment by kirikaTowa** [comment]
> 请正确填写所需的详细信息
I would like to ask, this method will cause an infinite loop under normal circumstances, how do you deal with it?
![image](https://user-images.githubusercontent.com/43930957/152965882-52bd1387-15d8-4cf5-a10e-237d2d5920e7.png)

**Comment by Dimezis** [comment]
The BlurView checks if the `Canvas` used in `draw` is `internalCanvas`, so it draws itself only on system canvas and skips the recursive drawing on `internalCanvas`

**Comment by kirikaTowa** [comment]
Thank you.InternalCanvas will have a problem when performing animation on some 5.0 models, resulting in this type of error. The rootView can be solved by using the parent of the previous level.
