### ISSUE TITLE
Android 12 enables blur natively

### ISSUE THREAD

**Issue by erickriva** [Dimezis/BlurView#168]
From version 12 of Android, it's enabled blurring views natively.
It depends on OEMs enable a flag to work, so not all devices will have support, but it's still native.

Source: https://source.android.com/devices/tech/display/window-blurs?hl=en

**Comment by Dimezis** [comment]
Thanks, I'm aware of that.
However, this API works only for translucent Windows (i.e. Dialogs and transparent Activities), which makes it unusable in context of this library
