### ISSUE TITLE
PixelCopy

### ISSUE THREAD

**Issue by SudoDios** [Dimezis/BlurView#170]
Hello.
I had a question.  
Why not use pixelcopy to capture bitmaps?  
It even supports surfaces.

**Comment by Dimezis** [comment]
I'd love to use it, but it would capture BlurView's content as well. I mean the content that shouldn't be blurred.
As well as the already blurred part.

**Comment by SudoDios** [comment]
I am working on this topic. You also see you.

**Comment by Dimezis** [comment]
I haven't, but I don't see `PixelCopy` in it

**Comment by SudoDios** [comment]
Yes, I know, 
but you can learn from it.

**Comment by Dimezis** [comment]
What do you suggest to learn exactly?
You can't exclude the views from PixelCopy the way it's done there

**Comment by SudoDios** [comment]
Can't use the ThreadedRenderer class?
https://github.com/AndroidSDKSources/android-sdk-sources-for-api-level-31/blob/master/android/view/ThreadedRenderer.java

**Comment by Dimezis** [comment]
It's a hidden class that is not accessible to developers
