### ISSUE TITLE
BlurView corner radius and corner width

### ISSUE THREAD

**Issue by muxammed** [Dimezis/BlurView#171]
Hi there is there any capability of adding corner radius to BlurView? if there is please share
Thanks

**Comment by muxammed** [comment]
Thanks, what about make alertDialog window blured, is it possible with this library, if does please explain how

**Comment by Dimezis** [comment]
Please check other threads before asking a question, it has been discussed a couple of times.
Also don't post all your questions in a single thread.

Yes, it's possible to use the BlurView with a dialog.
The details depend on how you want it to look exactly.
Try to code it, and then, if you'll have anything more specific to ask, create a new thread.
