### ISSUE TITLE
Not importing for "Android Studio Bumblebee" version. Can you help urgently?

### ISSUE THREAD

**Issue by Seyf25** [Dimezis/BlurView#173]
These imports are not valid when I upgrade to "**Android Studio Bumblebee**".
Can you help urgently?
 
```
import eightbitlab.com.blurview.BlurView;
import eightbitlab.com.blurview.RenderScriptBlur;
```

Not working.

Edit:
The cause of the problem:
With the Bumblebee update, jcenter() is being replaced by mavenCentral().
After this modification, it cannot be imported. When I set it to jcenter() it gives a warning like this:
"_JCenter Maven repository is no longer receiving updates: newer library versions may be available elsewhere_"

```
//working
allprojects {
    repositories {
        google()
        maven { url 'https://jitpack.io' }
        jcenter()
    }
}
```

```
//notworking
allprojects {
    repositories {
        google()
        maven { url 'https://jitpack.io' }
        mavenCentral()
    }
}

```

**Comment by Seyf25** [comment]
I solved the problem with this. It was imported without any problems, it's easy.


- https://jitpack.io/#Dimezis/BlurView
**Solution:**
```
allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}


dependencies {
	        implementation 'com.github.Dimezis:BlurView:Tag'
	}

```

**Comment by Dimezis** [comment]
Yes, it's in the [Readme](https://github.com/Dimezis/BlurView#gradle)
