### ISSUE TITLE
Could not find com.eightbitlab:blurview:2.0.0

### ISSUE THREAD

**Issue by 542604974** [Dimezis/BlurView#174]
Could not determine the dependencies of task ':app:compileDebugKotlin'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.eightbitlab:blurview:2.0.0.
     Searched in the following locations:
       - file:/Users/mac/Desktop/QihaoAccessControl/app/libs/blurview-2.0.0.jar
       - file:/Users/mac/Desktop/QihaoAccessControl/app/libs/blurview.jar
       - https://jcenter.bintray.com/com/eightbitlab/blurview/2.0.0/blurview-2.0.0.pom
       - https://dl.google.com/dl/android/maven2/com/eightbitlab/blurview/2.0.0/blurview-2.0.0.pom
       - https://repo.maven.apache.org/maven2/com/eightbitlab/blurview/2.0.0/blurview-2.0.0.pom
       - http://developer.huawei.com/repo/com/eightbitlab/blurview/2.0.0/blurview-2.0.0.pom
       - https://jitpack.io/com/eightbitlab/blurview/2.0.0/blurview-2.0.0.pom
     Required by:
         project :app

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by 542604974** [comment]
buildscript {
    ext.kotlin_version = '1.3.61'
    repositories {
        jcenter()
        google()
        mavenCentral()
        //tpns接入
        maven { url 'http://developer.huawei.com/repo/' }
        maven { url 'https://jitpack.io' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.1'
        //tpns集成插件
        classpath "com.tencent.android.tpns:tpnsplugin:1.8.0"

        classpath 'com.huawei.agconnect:agcp:1.6.0.300'     // 华为推送 gradle 插件依赖

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        //   支持kotlin
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        flatDir {
            dirs project(':app').file('libs')
        }
        jcenter()
        google()
        mavenCentral()
        maven { url 'http://developer.huawei.com/repo/' } // 华为仓，如果不集成华为可以不加
        maven { url 'https://jitpack.io' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by Dimezis** [comment]
You're using a wrong version tag name.

Please check the Readme.

```
implementation 'com.github.Dimezis:BlurView:version-2.0.0'
```

**Comment by 542604974** [comment]
I had try, it's error too.

**Comment by 542604974** [comment]
> You're using a wrong version tag name.
> 
> Please check the Readme.
> 
> ```
> implementation 'com.github.Dimezis:BlurView:version-2.0.0'
> ```

I tried, but I still reported a mistake

**Comment by Dimezis** [comment]
Here's the build on jitpack, you can see it's there - https://jitpack.io/#Dimezis/BlurView/version-2.0.0

`maven { url 'https://jitpack.io/' }`
and the version tag 
`implementation 'com.github.Dimezis:BlurView:version-2.0.0'`

work properly.

If it doesn't work for you, you made a mistake somewhere

**Comment by freeboub** [comment]
It would be interesting to add these informations to the README.md file !
Should I create a PR with this change ?

**Comment by Dimezis** [comment]
@freeboub the readme has a link to Jitpack which has these instructions on the main page.
The instructions are also the same for every library, so I don't think it's necessary to repeat them in the readme
