### ISSUE TITLE
Modifying radius does not work

### ISSUE THREAD

**Issue by 542604974** [Dimezis/BlurView#177]
Hello, thank you very much for your lib. It's very excellent. There are some problems. I can only use the renderscriptblur, not supportrenderscriptblur, otherwise it will crash abnormally (Java. Lang. NoClassDefFoundError). Now I use renderscriptblur with shallow blur effect, radius = 25F, coloroverlay = #99ffffff. How can I solve the problem of deepening blur effect?

**Comment by 542604974** [comment]
And version-1.6.6

**Comment by Dimezis** [comment]
I'm not sure what you mean by deepening. 

The maximum radius for RenderScript blur is 25.
You can't go beyond that, if that's what you mean.

You can make it lower though

**Comment by 542604974** [comment]
Sorry, My English is not good. 
I mean it is now a translucent effect, and the radius has been set to 25.
 how to set a deeper effect.

**Comment by Dimezis** [comment]
Please post a screenshot of what's happening. And post the code you're using to set up the BlurView

**Comment by 542604974** [comment]
![851652450151_ pic](https://user-images.githubusercontent.com/15099430/168299351-48f30071-70db-4878-950e-b5f6ce115a73.jpg)
![861652450152_ pic](https://user-images.githubusercontent.com/15099430/168299370-2294e723-08ac-4c1b-a992-17c3f420aaf7.jpg)

**Comment by 542604974** [comment]
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:id="@+id/cl_root"
    android:background="@color/trtccalling_color_videocall_background">

    <androidx.constraintlayout.widget.Guideline
        android:id="@+id/gl_horizontal_top"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:orientation="horizontal"
        app:layout_constraintGuide_begin="20dp" />



    <TextView
        android:id="@+id/wati_state_text"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:textColor="@color/white"
        android:gravity="center"
        android:textSize="@dimen/trtccalling_text_size_biger"
        android:text="@string/trtccalling_waitting_call"
        app:layout_constraintLeft_toLeftOf="@+id/ll_video_toolbar"
        app:layout_constraintRight_toRightOf="@+id/switch_camera"
        app:layout_constraintTop_toTopOf="@+id/switch_camera"
        app:layout_constraintBottom_toBottomOf="@+id/switch_camera"
        tools:ignore="MissingConstraints" />

    <com.tencent.liteav.trtccalling.ui.videocall.videolayout.TRTCVideoLayoutManager
        android:id="@+id/trtc_layout_manager"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintHorizontal_bias="0.0"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" >

        <View
            android:id="@+id/shade_sponsor"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@color/trtccalling_color_shade" />
    </com.tencent.liteav.trtccalling.ui.videocall.videolayout.TRTCVideoLayoutManager>

    <LinearLayout
        android:id="@+id/ll_video_toolbar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginLeft="14dp"
        android:layout_marginTop="12dp"
        android:background="@color/trtccalling_color_transparent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintTop_toTopOf="@id/gl_horizontal_top">
        <ImageView
            android:id="@+id/img_video_back"
            android:layout_width="40dp"
            android:layout_height="40dp"
            android:src="@drawable/calling_video_back" />
    </LinearLayout>

    <com.tencent.liteav.trtccalling.ui.common.RoundCornerImageView
        android:id="@+id/iv_sponsor_avatar"
        android:layout_width="80dp"
        android:layout_height="80dp"
        android:layout_marginTop="44dp"
        android:layout_marginEnd="20dp"
        app:trtcradius="15dp"
        android:visibility="gone"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintTop_toTopOf="@+id/gl_horizontal_top" />

    <TextView
        android:id="@+id/tv_sponsor_user_name"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginTop="44dp"
        android:layout_marginEnd="20dp"
        android:paddingLeft="20dp"
        android:text="@string/trtccalling_contact_default_name"
        android:textColor="@color/trtccalling_color_white"
        android:textSize="24sp"
        android:textStyle="bold"
        app:layout_constrainedWidth="true"
        android:visibility="gone"
        app:layout_constraintEnd_toStartOf="@+id/iv_sponsor_avatar"
        app:layout_constraintHorizontal_bias="1.0"
        app:layout_constraintHorizontal_chainStyle="packed"
        app:layout_constraintTop_toTopOf="@+id/gl_horizontal_top" />

    <TextView
        android:id="@+id/tv_sponsor_video_tag"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginEnd="10dp"
        android:layout_marginTop="3dp"
        android:text="@string/trtccalling_invite_video_call"
        android:textColor="@color/trtccalling_color_white"
        android:textSize="@dimen/trtccalling_text_size_hint"
        android:visibility="gone"
        app:layout_constraintTop_toBottomOf="@+id/tv_sponsor_user_name"
        app:layout_constraintEnd_toStartOf="@+id/iv_sponsor_avatar" />


    <androidx.constraintlayout.widget.Group
        android:id="@+id/group_inviting"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:visibility="gone"
        app:constraint_referenced_ids="tv_inviting_tag,ll_img_container" />

    <TextView
        android:id="@+id/tv_inviting_tag"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="@string/trtccalling_inviting_tag"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/trtc_layout_manager" />

    <LinearLayout
        android:id="@+id/ll_img_container"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="10dp"
        android:gravity="center"
        android:orientation="horizontal"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/tv_inviting_tag" />
    
    <ImageView
        android:id="@+id/switch_camera"
        android:layout_width="40dp"
        android:layout_height="40dp"
        android:layout_marginTop="10dp"
        android:layout_marginRight="13dp"
        android:src="@drawable/calling_switch_camera"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="@+id/gl_horizontal_top" />
    


    <TextView
        android:id="@+id/tv_time"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginBottom="20dp"
        android:textSize="@dimen/trtccalling_text_size_biger"
        android:textColor="@color/trtccalling_color_white"
        app:layout_constraintBottom_toTopOf="@id/ll_switch_audio_call"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        tools:text="@string/trtccalling_call_time_default" />

    <LinearLayout
        android:id="@+id/ll_mute"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginBottom="17dp"
        android:gravity="center_horizontal"
        android:orientation="vertical"
        android:visibility="gone"
        app:layout_constraintBottom_toTopOf="@+id/ll_hangup"
        app:layout_constraintEnd_toStartOf="@+id/ll_handsfree"
        app:layout_constraintHorizontal_bias="0.5"
        app:layout_constraintStart_toStartOf="parent">

        <ImageView
            android:id="@+id/iv_mute"
            android:layout_width="52dp"
            android:layout_height="52dp"
            android:src="@drawable/trtccalling_bg_mute_mic" />

        <TextView
            android:id="@+id/tv_mic"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="16dp"
            android:gravity="center"
            android:textColor="@color/trtccalling_color_white"
            android:text="@string/trtccalling_text_microphone"
            android:textSize="@dimen/trtccalling_text_size_hint" />
    </LinearLayout>

    <LinearLayout
        android:id="@+id/ll_handsfree"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginBottom="17dp"
        android:gravity="center_horizontal"
        android:orientation="vertical"
        app:layout_constraintBottom_toTopOf="@+id/ll_hangup"
        app:layout_constraintEnd_toStartOf="@+id/ll_open_camera"
        app:layout_constraintHorizontal_bias="0.5"
        android:visibility="gone"
        app:layout_constraintStart_toEndOf="@+id/ll_mute">

        <ImageView
            android:id="@+id/iv_handsfree"
            android:layout_width="52dp"
            android:layout_height="52dp"
            android:src="@drawable/trtccalling_bg_handsfree" />

        <TextView
            android:id="@+id/tv_speaker"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="16dp"
            android:gravity="center"
            android:textColor="@color/trtccalling_color_white"
            android:text="@string/trtccalling_text_speaker"
            android:textSize="@dimen/trtccalling_text_size_hint" />

    </LinearLayout>

    <LinearLayout
        android:id="@+id/ll_open_camera"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginBottom="17dp"
        android:gravity="center_horizontal"
        android:orientation="vertical"
        app:layout_constraintBottom_toTopOf="@+id/ll_hangup"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintHorizontal_bias="0.5"
        android:visibility="gone"
        app:layout_constraintStart_toEndOf="@+id/ll_handsfree">

        <ImageView
            android:id="@+id/img_camera"
            android:layout_width="52dp"
            android:layout_height="52dp"
            android:src="@drawable/trtccalling_bg_camera" />

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="16dp"
            android:gravity="center"
            android:text="@string/trtccalling_text_camera"
            android:textColor="@color/trtccalling_color_white"
            android:textSize="@dimen/trtccalling_text_size_hint" />

    </LinearLayout>

    <LinearLayout
        android:id="@+id/ll_hangup"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:gravity="center_horizontal"
        android:orientation="vertical"
        android:layout_marginBottom="62dp"
        app:layout_constraintBottom_toTopOf="@+id/gl_horizontal_bottom"
        app:layout_constraintEnd_toStartOf="@id/ll_dialing"
        app:layout_constraintHorizontal_bias="0.5"
        app:layout_constraintStart_toStartOf="parent">

        <ImageView
            android:id="@+id/iv_hangup"
            android:layout_width="64dp"
            android:layout_height="64dp"
            android:src="@drawable/calling_hangup_logo" />

        <TextView
            android:id="@+id/tv_hangup"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="16dp"
            android:gravity="center"
            android:text="@string/trtccalling_text_reject"
            android:visibility="gone"
            android:textColor="@color/trtccalling_color_white"
            android:textSize="@dimen/trtccalling_text_size_hint" />

    </LinearLayout>

    <LinearLayout
        android:id="@+id/ll_switch_audio_call"
        android:orientation="vertical"
        app:layout_constraintBottom_toTopOf="@+id/ll_handsfree"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        android:layout_marginBottom="20dp"
        android:visibility="gone"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content">

        <ImageView
            android:src="@drawable/trtccalling_ic_switch_to_audio_call"
            android:layout_gravity="center_horizontal"
            android:layout_width="36dp"
            android:layout_height="19dp" />

        <TextView
            android:textSize="12sp"
            android:layout_marginTop="10dp"
            android:layout_gravity="center_horizontal"
            android:text="@string/trtccalling_switch_audio_call"
            android:textColor="@color/trtccalling_color_white"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content" />

    </LinearLayout>

    <LinearLayout
        android:id="@+id/ll_dialing"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:gravity="center_horizontal"
        android:orientation="vertical"
        android:layout_marginBottom="20dp"
        android:visibility="gone"
        app:layout_constraintBottom_toTopOf="@+id/gl_horizontal_bottom"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintHorizontal_bias="0.5"
        app:layout_constraintStart_toEndOf="@+id/ll_hangup">

        <ImageView
            android:id="@+id/iv_dialing"
            android:layout_width="64dp"
            android:layout_height="64dp"
            android:src="@drawable/trtccalling_bg_dialing" />

        <TextView
            android:id="@+id/tv_answer"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="16dp"
            android:gravity="center"
            android:text="@string/trtccalling_text_dialing"
            android:textColor="@color/trtccalling_color_white"
            android:textSize="@dimen/trtccalling_text_size_hint" />

    </LinearLayout>

    <com.tencent.liteav.trtccalling.ui.blurview.BlurView
        android:id="@+id/topBlurView"
        android:layout_width="match_parent"
        android:layout_height="50dp"
        android:elevation="4dp"
        android:outlineProvider="bounds"
        app:blurOverlayColor="@color/colorOverlay"
        tools:targetApi="lollipop"
        app:layout_constraintTop_toTopOf="@+id/gl_horizontal_top">

    </com.tencent.liteav.trtccalling.ui.blurview.BlurView>

    <androidx.constraintlayout.widget.Guideline
        android:id="@+id/gl_horizontal_bottom"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_marginBottom="34dp"
        android:orientation="horizontal"
        app:layout_constraintGuide_percent="0.98084813" />


</androidx.constraintlayout.widget.ConstraintLayout>

**Comment by 542604974** [comment]
private void setupBlurView() {
        final float radius = 25f;
        final float minBlurRadius = 10f;
        final float step = 4f;

        //set background, if your root layout doesn't have one
//        final Drawable windowBackground = getWindow().getDecorView().getBackground();

        View decorView = getWindow().getDecorView();
        //ViewGroup you want to start blur from. Choose root as close to BlurView in hierarchy as possible.
        ViewGroup rootView = (ViewGroup) decorView.findViewById(R.id.cl_root);
        Drawable windowBackground = decorView.getBackground();

        mTopBlurView.setupWith(rootView)
                .setFrameClearDrawable(windowBackground)
                .setBlurAlgorithm(new RenderScriptBlur(this))
                .setBlurRadius(radius)
                .setHasFixedTransformationMatrix(true);
    }

**Comment by 542604974** [comment]
Sorry, no data cable, can't debug

**Comment by Dimezis** [comment]
If you're trying to blur the video, that's unfortunately not possible with the BlurView

**Comment by 542604974** [comment]
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:id="@+id/cl_root"
    android:orientation="horizontal">

<com.tencent.liteav.trtccalling.ui.blurview.BlurView
    android:id="@+id/topBlurView"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:elevation="4dp"
    android:outlineProvider="bounds"
    app:blurOverlayColor="@color/colorOverlay"
    tools:targetApi="lollipop">

    <androidx.constraintlayout.widget.ConstraintLayout
        android:layout_width="456dp"
        android:layout_height="match_parent"
        android:layout_gravity="center"
        android:layout_centerInParent="true"
        android:background="@color/trtccalling_color_videocall_background">
        <androidx.constraintlayout.widget.Guideline
            android:id="@+id/gl_horizontal_top"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:orientation="horizontal" />

        <TextView
            android:id="@+id/toast_text"
            android:layout_width="0dp"
            android:layout_height="0dp"
            android:background="@drawable/trtccalling_circle_black_30"
            android:padding="10dp"
            android:text="@string/sure"
            android:visibility="gone"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintLeft_toLeftOf="parent"
            app:layout_constraintRight_toRightOf="parent"
            app:layout_constraintTop_toTopOf="parent" />

        <com.tencent.liteav.trtccalling.ui.videocall.videolayout.TRTCVideoLayoutManager
            android:id="@+id/trtc_layout_manager"
            android:layout_width="482dp"
            android:layout_height="match_parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintHorizontal_bias="0.0"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent" />

        <LinearLayout
            android:id="@+id/ll_video_toolbar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginStart="20dp"
            android:layout_marginTop="44dp"
            android:background="@color/trtccalling_color_transparent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="@id/gl_horizontal_top"
            android:layout_marginLeft="20dp"
            android:visibility="gone">
            // 缩小窗口按钮
            <ImageView
                android:id="@+id/img_video_back"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:src="@drawable/trtccalling_ic_movetoback" />
        </LinearLayout>

        <View
            android:id="@+id/shade_sponsor"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@color/trtccalling_color_shade" />

        // 发起人的头像
        <com.tencent.liteav.trtccalling.ui.common.RoundCornerImageView
            android:id="@+id/iv_sponsor_avatar"
            android:layout_width="80dp"
            android:layout_height="80dp"
            android:layout_marginTop="44dp"
            android:layout_marginEnd="20dp"
            app:radius="15dp"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintTop_toTopOf="@+id/gl_horizontal_top"
            android:layout_marginRight="20dp"
            android:visibility="gone"/>

        // 发起人的姓名
        <TextView
            android:id="@+id/tv_sponsor_user_name"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="44dp"
            android:layout_marginEnd="20dp"
            android:paddingLeft="20dp"
            android:text="@string/trtccalling_contact_default_name"
            android:textColor="@color/trtccalling_color_white"
            android:textSize="24sp"
            android:textStyle="bold"
            app:layout_constrainedWidth="true"
            app:layout_constraintEnd_toStartOf="@+id/iv_sponsor_avatar"
            app:layout_constraintHorizontal_bias="1.0"
            app:layout_constraintHorizontal_chainStyle="packed"
            app:layout_constraintTop_toTopOf="@+id/gl_horizontal_top"
            android:layout_marginRight="20dp"
            android:visibility="gone"/>

        // 发起人的邀请
        <TextView
            android:id="@+id/tv_sponsor_video_tag"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginEnd="10dp"
            android:layout_marginTop="3dp"
            android:text="@string/trtccalling_invite_video_call"
            android:textColor="@color/trtccalling_color_white"
            android:textSize="@dimen/trtccalling_text_size_hint"
            app:layout_constraintTop_toBottomOf="@+id/tv_sponsor_user_name"
            app:layout_constraintEnd_toStartOf="@+id/iv_sponsor_avatar"
            android:layout_marginRight="10dp"
            android:visibility="gone"/>

        // 通话时其他邀请人呼叫
        <androidx.constraintlayout.widget.Group
            android:id="@+id/group_inviting"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:visibility="gone"
            app:constraint_referenced_ids="tv_inviting_tag,ll_img_container" />

        <TextView
            android:id="@+id/tv_inviting_tag"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="@string/trtccalling_inviting_tag"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@id/trtc_layout_manager" />

        <LinearLayout
            android:id="@+id/ll_img_container"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="10dp"
            android:gravity="center"
            android:orientation="horizontal"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@id/tv_inviting_tag" />

        // 切换摄像头
        <ImageView
            android:id="@+id/switch_camera"
            android:layout_width="32dp"
            android:layout_height="32dp"
            android:layout_marginLeft="20dp"
            android:layout_marginTop="64dp"
            android:src="@drawable/trtccalling_ic_switch_camera"
            app:layout_constraintBottom_toBottomOf="@+id/ll_hangup"
            app:layout_constraintEnd_toEndOf="@+id/ll_open_camera"
            app:layout_constraintStart_toStartOf="@+id/ll_open_camera"
            app:layout_constraintTop_toTopOf="@+id/ll_open_camera" />



        // 麦克风开关
        <LinearLayout
            android:id="@+id/ll_mute"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginBottom="17dp"
            android:gravity="center_horizontal"
            android:orientation="vertical"
            app:layout_constraintBottom_toTopOf="@+id/ll_hangup"
            app:layout_constraintEnd_toStartOf="@+id/ll_handsfree"
            app:layout_constraintHorizontal_bias="0.5"
            app:layout_constraintStart_toStartOf="parent">

            <ImageView
                android:id="@+id/iv_mute"
                android:layout_width="52dp"
                android:layout_height="52dp"
                android:src="@drawable/trtccalling_bg_mute_mic" />

            <TextView
                android:id="@+id/tv_mic"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginTop="16dp"
                android:gravity="center"
                android:textColor="@color/trtccalling_color_white"
                android:text="@string/trtccalling_text_microphone"
                android:textSize="@dimen/trtccalling_text_size_hint" />
        </LinearLayout>

        // 扬声器
        <LinearLayout
            android:id="@+id/ll_handsfree"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginBottom="17dp"
            android:gravity="center_horizontal"
            android:orientation="vertical"
            app:layout_constraintBottom_toTopOf="@+id/ll_hangup"
            app:layout_constraintEnd_toStartOf="@+id/ll_open_camera"
            app:layout_constraintHorizontal_bias="0.5"
            app:layout_constraintStart_toEndOf="@+id/ll_mute">

            <ImageView
                android:id="@+id/iv_handsfree"
                android:layout_width="52dp"
                android:layout_height="52dp"
                android:src="@drawable/trtccalling_bg_handsfree" />

            <TextView
                android:id="@+id/tv_speaker"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginTop="16dp"
                android:gravity="center"
                android:textColor="@color/trtccalling_color_white"
                android:text="@string/trtccalling_text_speaker"
                android:textSize="@dimen/trtccalling_text_size_hint" />

        </LinearLayout>

        // 摄像头
        <LinearLayout
            android:id="@+id/ll_open_camera"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginBottom="17dp"
            android:gravity="center_horizontal"
            android:orientation="vertical"
            app:layout_constraintBottom_toTopOf="@+id/ll_hangup"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintHorizontal_bias="0.5"
            app:layout_constraintStart_toEndOf="@+id/ll_handsfree">

            <ImageView
                android:id="@+id/img_camera"
                android:layout_width="52dp"
                android:layout_height="52dp"
                android:src="@drawable/trtccalling_bg_camera" />

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginTop="16dp"
                android:gravity="center"
                android:text="@string/trtccalling_text_camera"
                android:textColor="@color/trtccalling_color_white"
                android:textSize="@dimen/trtccalling_text_size_hint" />

        </LinearLayout>

        //挂断按钮
        <LinearLayout
            android:id="@+id/ll_hangup"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:gravity="center_horizontal"
            android:orientation="vertical"
            android:layout_marginBottom="50dp"
            app:layout_constraintBottom_toTopOf="@+id/gl_horizontal_bottom"
            app:layout_constraintEnd_toStartOf="@id/ll_dialing"
            app:layout_constraintHorizontal_bias="0.5"
            app:layout_constraintStart_toStartOf="parent">

            <ImageView
                android:id="@+id/iv_hangup"
                android:layout_width="64dp"
                android:layout_height="64dp"
                android:src="@drawable/trtccalling_bg_hangup" />

            <TextView
                android:id="@+id/tv_hangup"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginTop="16dp"
                android:gravity="center"
                android:text="@string/trtccalling_text_reject"
                android:textColor="@color/trtccalling_color_white"
                android:textSize="@dimen/trtccalling_text_size_hint" />

        </LinearLayout>

        // 切换语音通话
        <LinearLayout
            android:id="@+id/ll_switch_audio_call"
            android:orientation="vertical"
            app:layout_constraintBottom_toTopOf="@+id/ll_handsfree"
            app:layout_constraintLeft_toLeftOf="parent"
            app:layout_constraintRight_toRightOf="parent"
            android:layout_marginBottom="20dp"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content">

            <ImageView
                android:src="@drawable/trtccalling_ic_switch_to_audio_call"
                android:layout_gravity="center_horizontal"
                android:layout_width="36dp"
                android:layout_height="19dp" />

            <TextView
                android:textSize="12sp"
                android:layout_marginTop="10dp"
                android:layout_gravity="center_horizontal"
                android:text="@string/trtccalling_switch_audio_call"
                android:textColor="@color/trtccalling_color_white"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content" />

        </LinearLayout>

        // 接听按钮
        <LinearLayout
            android:id="@+id/ll_dialing"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:gravity="center_horizontal"
            android:orientation="vertical"
            android:layout_marginBottom="50dp"
            app:layout_constraintBottom_toTopOf="@+id/gl_horizontal_bottom"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintHorizontal_bias="0.5"
            app:layout_constraintStart_toEndOf="@+id/ll_hangup">

            <ImageView
                android:id="@+id/iv_dialing"
                android:layout_width="64dp"
                android:layout_height="64dp"
                android:src="@drawable/trtccalling_bg_dialing" />

            <TextView
                android:id="@+id/tv_answer"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginTop="16dp"
                android:gravity="center"
                android:text="@string/trtccalling_text_dialing"
                android:textColor="@color/trtccalling_color_white"
                android:textSize="@dimen/trtccalling_text_size_hint" />

        </LinearLayout>

        <androidx.constraintlayout.widget.ConstraintLayout
            android:id="@+id/ll_opendoor_calling"
            android:layout_width="0dp"
            android:layout_height="66dp"
            android:layout_marginLeft="100dp"
            android:layout_marginRight="100dp"
            android:layout_marginBottom="30dp"
            app:layout_constraintBottom_toTopOf="@id/ll_hangup"
            app:layout_constraintLeft_toLeftOf="parent"
            app:layout_constraintRight_toRightOf="parent"
            android:background="@drawable/trtccalling_stroke_white_16">

            <ImageView
                android:id="@+id/opendoor_image"
                android:layout_width="34dp"
                android:layout_height="38dp"
                android:layout_marginTop="14dp"
                android:layout_marginLeft="101dp"
                app:layout_constraintLeft_toLeftOf="parent"
                app:layout_constraintTop_toTopOf="parent"
                android:src="@drawable/trtccaling_ic_door"
                />

            <TextView
                android:id="@+id/tv_opendoor_calling"
                android:layout_width="wrap_content"
                android:layout_height="28dp"
                android:layout_marginTop="19dp"
                android:gravity="center"
                android:text="@string/trtccalling_opendoor"
                android:textColor="@color/trtccalling_color_white"
                android:textSize="@dimen/trtccalling_text_size_morelarge"
                android:layout_marginLeft="16dp"
                app:layout_constraintLeft_toRightOf="@+id/opendoor_image"
                app:layout_constraintTop_toTopOf="parent"/>

        </androidx.constraintlayout.widget.ConstraintLayout>

        // 通话时长
        <TextView
            android:id="@+id/tv_time"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_marginTop="46dp"
            android:textSize="@dimen/trtccalling_text_size_morelarge"
            android:textStyle="bold"
            android:gravity="center"
            android:textColor="@color/trtccalling_color_white"
            app:layout_constraintTop_toTopOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            tools:text="@string/trtccalling_call_time_default" />


        <androidx.constraintlayout.widget.Guideline
            android:id="@+id/gl_horizontal_bottom"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_marginBottom="34dp"
            android:orientation="horizontal"
            app:layout_constraintGuide_percent="0.98084813" />

    </androidx.constraintlayout.widget.ConstraintLayout>
</com.tencent.liteav.trtccalling.ui.blurview.BlurView>






</RelativeLayout>

**Comment by 542604974** [comment]
private void setupBlurView() {
        final float radius = 25f;
        final float minBlurRadius = 25f;
        final float step = 8f;

        //set background, if your root layout doesn't have one
//        final Drawable windowBackground = getWindow().getDecorView().getBackground();

        View decorView = getWindow().getDecorView();
        //ViewGroup you want to start blur from. Choose root as close to BlurView in hierarchy as possible.
        ViewGroup rootView = (ViewGroup) decorView.findViewById(R.id.cl_root);
        //Set drawable to draw in the beginning of each blurred frame (Optional).
        //Can be used in case your layout has a lot of transparent space and your content
        //gets kinda lost after after blur is applied.
        Drawable windowBackground = decorView.getBackground();
        mTopBlurView.setupWith(rootView)
                .setFrameClearDrawable(windowBackground)
                .setBlurAlgorithm(new RenderScriptBlur(this))
                .setBlurRadius(radius)
                .setBlurAutoUpdate(true);
    }

**Comment by 542604974** [comment]
Hello, is this background the same problem？

**Comment by Dimezis** [comment]
As I already said, you can't blur the video (`SurfaceView`, `GLSurfaceView`, `TextureView` and their descendants in particular).
I also don't see the BlurView on your screenshot, so it's hard to guess what you're trying to achieve exactly.

**Comment by 542604974** [comment]
![5951652406949_ pic](https://user-images.githubusercontent.com/15099430/168714702-2231c749-d96a-4fe1-a39c-8b322ee66bb2.jpg)
Hello, this is the effect I want.If not, there's no other way.

**Comment by 542604974** [comment]
In the middle is the audio and video call page. This audio and video page may appear on any page. If not, I can only change a design idea.

**Comment by Dimezis** [comment]
It's possible, you just have to set it up correctly.
Check the example project and the documentation.

I can't help you based on the pieces of code you provided.

I'm closing this issue, because it's not relevant.

**Comment by 542604974** [comment]
OK，thanks you very much！
