### ISSUE TITLE
Low frame rate on device with low memory[see videos]

### ISSUE THREAD

**Issue by MichaelArchangel** [Dimezis/BlurView#18]
Today I tested this Library on another device and the performance was really terrible...

[videos.zip](https://github.com/Dimezis/BlurView/files/346086/videos.zip)
better device's profile:
OS:5.1
resolution:1440*2560
ppi:515
CPU:2.0GHz*4+1.5GHz*4
RAM:4G

poor device's profile:
OS:4.4
resolution:720*1280
ppi:312
CPU:1.2GHz*4
RAM:1G

**Comment by Dimezis** [comment]
Can you please send the source of this example project? Or at least similar setup.
What blur algorithm do you use?

**Comment by MichaelArchangel** [comment]
I will make a similar example project later.
I used the same algorithm in the demo:

blur.setupWith(rootView)
				.windowBackground(windowBackground)
				.blurAlgorithm(new RenderScriptBlur(this, true)) //Preferable algorithm, needs RenderScript support mode enabled
				.blurRadius(radius);

**Comment by Dimezis** [comment]
Any updates?

**Comment by MichaelArchangel** [comment]
sorry, I was busy these days. That poor device works fine after rebooting it. Maybe it is not a issue of library.
