### ISSUE TITLE
Blur Algorithm and Android 13

### ISSUE THREAD

**Issue by GuillaumeBourge** [Dimezis/BlurView#182]
Please include:
1) 2.0.1
2) Pixel 6 with Android 13

We are using blurview to perform blurred overlay behind loader and dialog. It works perfectly fine until Android 13.
On Android 13 when a textfield is shown and focused within Dialog with blurred background, we got a blinking background.. (the blinking/redraw seems to occurred when a letter is drawn or when the cursor blink)
We are using RenderScriptBlur `.setBlurAlgorithm(RenderScriptBlur(rootview.context))` but it is now deprecated.
We try to switch to RenderEffectBlur (that is also deprecated ?) with `setBlurAlgorithm(RenderEffectBlur(this, RenderEffectPrecision.EXACT))` and it seems to work fine (RenderEffectPrecision.DOWNSCALED make a blinks each time in every case).

My question is what script we must used ? the all two are now deprecated and android 13 seems to be tricky :(
The visual render is a little bit different between the two scripts ?

**Comment by Dimezis** [comment]
@GuillaumeBourge Version 2.0.2 undeprecates the `RenderEffectBlur` back 😅 
It's now completely rewritten in a much more efficient (and sane) way

**Comment by Dimezis** [comment]
@GuillaumeBourge No worries, it doesn't matter since the Jcenter is closed and I'm not publishing artifacts there anymore.
If anything, I should just disable this CI step

**Comment by GuillaumeBourge** [comment]
Ok we thought that was that causing our "Failed to resolve: com.github.Dimezis:BlurView:version-2.0.2"
We are not able to retrieve the 2.0.2 version with gradle but not problem with the 2.0.1 :/

**Comment by Dimezis** [comment]
Ah, for some reason Jitpack decided to execute some unrelated tasks. Weird.
Try fetching the 2.0.2 now

**Comment by GuillaumeBourge** [comment]
Yes it works fine now thank you :)
Just to know, the blur radius is also strongly affected by you redesign ?
a 25 radius 2.0.1 RenderEffectBlur seems to be ~ 6 radius 2.0.2 RenderEffectBlur
It's not a problem for me, but knowing the min is 6 maybe it can be too much blurred for some usecase ?

**Comment by GuillaumeBourge** [comment]
Ok thank you for explanations and improvements :)
