### ISSUE TITLE
java.lang.IllegalStateException: Underflow in restore - more restores than saves

### ISSUE THREAD

**Issue by Usman-Click** [Dimezis/BlurView#184]
Hi,

pls i get this error when i tried to scroll blurView inside a scroll view

this is what i get from logcat
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.clickinc.toplayer, PID: 16537
    java.lang.IllegalStateException: Underflow in restore - more restores than saves
        at android.graphics.Canvas.restore(Canvas.java:679)
        at eightbitlab.com.blurview.PreDrawBlurController.updateBlur(PreDrawBlurController.java:116)
        at eightbitlab.com.blurview.PreDrawBlurController$1.onPreDraw(PreDrawBlurController.java:50)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1124)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3854)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2618)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9971)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
        at android.view.Choreographer.doCallbacks(Choreographer.java:809)
        at android.view.Choreographer.doFrame(Choreographer.java:744)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8550)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

thanks

**Comment by Dimezis** [comment]
Please attach a sample project or code with your XML layout

**Comment by Usman-Click** [comment]
Okay 
Where should I send it ?
Or should I paste it here ?

**Comment by Dimezis** [comment]
Post a link to the repository or paste a relevant code here.
Repository is preferable

**Comment by Usman-Click** [comment]
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.motion.widget.MotionLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:background="@android:color/transparent"
    app:layoutDescription="@xml/activity_music_player_scene"
    tools:context=".musicplayer.MusicPlayerActivity">


    <RelativeLayout
        android:id="@+id/music_player_parent"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent">

     
             ////  ImageView to be blured

            <ImageView
                android:id="@+id/musicThumbnailBg"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:background="@color/pri_color_variant"
                android:scaleType="centerCrop" />

    

        ////   BlurView

        <eightbitlab.com.blurview.BlurView
            android:id="@+id/blurLayout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="#80000000" >


        <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">


          <Unrelated-date>
                  ...
         </Unrelated-data>


        </RelativeLayout>


        </eightbitlab.com.blurview.BlurView>


    </RelativeLayout>


</androidx.constraintlayout.motion.widget.MotionLayout>



is it because of MotionLayout ???

**Comment by Usman-Click** [comment]
`<androidx.constraintlayout.motion.widget.MotionLayout xmlns:android="http://schemas.android.com/apk/res/android"
xmlns:app="http://schemas.android.com/apk/res-auto"
xmlns:tools="http://schemas.android.com/tools"
android:layout_width="match_parent"
android:layout_height="wrap_content"
android:background="https://github.com/android:color/transparent"
app:layoutDescription="@xml/activity_music_player_scene"
tools:context=".musicplayer.MusicPlayerActivity">

<RelativeLayout
    android:id="@+id/music_player_parent"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:layout_constraintBottom_toBottomOf="parent"
    app:layout_constraintEnd_toEndOf="parent"
    app:layout_constraintStart_toStartOf="parent">

 
         ////  ImageView to be blured

        <ImageView
            android:id="@+id/musicThumbnailBg"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@color/pri_color_variant"
            android:scaleType="centerCrop" />



    ////   BlurView

    <eightbitlab.com.blurview.BlurView
        android:id="@+id/blurLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="#80000000" >


    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">


      <Unrelated-date>
              ...
     </Unrelated-data>


    </RelativeLayout>


    </eightbitlab.com.blurview.BlurView>


</RelativeLayout>
</androidx.constraintlayout.motion.widget.MotionLayout>
`


**is it because of MotionLayout ??**

**Comment by Usman-Click** [comment]
```
<androidx.constraintlayout.motion.widget.MotionLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:layoutDescription="@xml/activity_music_player_scene"
    tools:context=".musicplayer.MusicPlayerActivity">


    <RelativeLayout
        android:id="@+id/music_player_parent"
        android:layout_width="match_parent"
        android:layout_height="1dp"
        android:visibility="invisible"
        android:alpha="0"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent">


        //// imageView to be blured

            <ImageView
                android:id="@+id/musicThumbnailBg"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:background="@color/pri_color_variant"
                android:scaleType="centerCrop" />

     


     //// BlurView

        <eightbitlab.com.blurview.BlurView
            android:id="@+id/blurLayout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="#80000000" >


        <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">


       <Unrelated-date>..........</Unrelated-data>


    </RelativeLayout>


      </eightbitlab.com.blurview.BlurView>
 


</androidx.constraintlayout.motion.widget.MotionLayout>
```


Is it because of  MotionLayout ???

**Comment by Dimezis** [comment]
Could you please check if [this PR](https://github.com/Dimezis/BlurView/pull/187) fixes your problem?
