### ISSUE TITLE
BlurView doesn't handle text positioning correctly on `RecyclerView`

### ISSUE THREAD

**Issue by Fox2Code** [Dimezis/BlurView#186]
Text snap when scrolling in a scroll view.

Please include:
1) Library version
Verified to exists both on 1.6.6 and 2.0.2
2) Device and OS version
Test both on:
\- Android 11 OxygenOS with `RenderScriptBlur`
\- Android 13 AVD with `RenderScriptBlur` and `RenderEffectBlur`
3) Detailed steps to reproduce the issue
Go in a `RecyclerView` layout with a part of it blurred and scroll slowly.
Note: BlurView example app require the blur slider to be low for the issue to be clearly visible.
4) XML layout and code for BlurView setup
(The issue is exactly the same on both)
BlurView example app:
\- https://github.com/Dimezis/BlurView/blob/master/app/src/main/res/layout/fragment_list.xml &
\- https://github.com/Dimezis/BlurView/blob/master/app/src/main/res/layout/list_item.xml
FoxMMM:
\- https://github.com/Fox2Code/FoxMagiskModuleManager/blob/master/app/src/main/res/layout/activity_main.xml &
\- https://github.com/Fox2Code/FoxMagiskModuleManager/blob/master/app/src/main/res/layout/module_entry.xml
5) Stacktrace in case of a crash
There is not crash hopefully.

- Reported by someone else on my app (Contain video of the issue): 
https://github.com/Fox2Code/FoxMagiskModuleManager/issues/191

**Comment by Dimezis** [comment]
It's not a bug, just an unfortunate consequence of having to scale down the bitmap before blurring.
Increasing the blur radius should help mitigate this issue

**Comment by Fox2Code** [comment]
Yeah, I found out how to manipulate the downscale factor in `BlurView` without changing the library code, I will do this on my app.

I know changing the downscale factor affect the blurring, but I can change the blur radius to compensate for that.
