### ISSUE TITLE
Wrong rendering after return from background

### ISSUE THREAD

**Issue by JustTrust** [Dimezis/BlurView#19]
Hi, Dmitriy! All woks fine except one thing )
When blur view is showing and I send app in background and return it I have strange picture.

![device-2016-07-22-120602](https://cloud.githubusercontent.com/assets/16021604/17052269/615cd660-5005-11e6-8781-dcd2a184c526.png)

I making invalidate() this view in onResume(), but nothing happened (
Please look at this problem.
This is code of call

```
public void onStart() {

        final View decorView = mFragment.getActivity().getWindow().getDecorView();
        //Activity's root View. Can also be root View of your layout
        final View rootView = decorView.findViewById(android.R.id.content);
        //set background, if your root layout doesn't have one
        final Drawable windowBackground = decorView.getBackground();

        mBlurBgView.setupWith(rootView)
                .windowBackground(windowBackground)
                .blurAlgorithm(new RenderScriptBlur(mFragment.getContext(), true)) //Preferable algorithm, needs RenderScript support mode enabled
                .blurRadius(mRadius);
        mBlurBgView.startAutoBlurUpdate();
    }

```

This is were the Blur view set up

```
public void onActivityCreated() {

        Rect visibleFrame = new Rect();
        mRoot = (ViewGroup) mFragment.getActivity().getWindow().getDecorView();
        mRoot.getWindowVisibleDisplayFrame(visibleFrame);

        mBlurContainer = new FrameLayout(mFragment.getActivity());
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB_MR1) {
            // window has a navigation bar
            mBlurContainer = new FrameLayout(mFragment.getActivity());
            FrameLayout.LayoutParams params = new FrameLayout.LayoutParams(visibleFrame.right - visibleFrame.left,
                    visibleFrame.bottom - visibleFrame.top);
            params.setMargins(visibleFrame.left, visibleFrame.top, 0, 0);
            mBlurContainer.setLayoutParams(params);
        } else {
            mBlurContainer.setPadding(visibleFrame.left, visibleFrame.top, 0, 0);
        }

        mBlurBgView = new BlurView(mFragment.getContext());
        mBlurContainer.addView(mBlurBgView);

        mRoot.addView(mBlurContainer);

    }
```

**Comment by JustTrust** [comment]
I fix this problem with change blurAlgorithm to StackBlur, but if you fix RenderScriptBlur it will be good ) And tell me in two words what is difference between those algorithms?

**Comment by Dimezis** [comment]
Hey,

I'll check this behavior, but what if you put setup in onCreate instead of onStart?

Regarding the algorithms, basically RenderscriptBlur is much faster and uses less memory. It is executed on the GPU, you can read about it in some google tutorials. But it has some issues with its context initialization (I have similar issue already).

And StackBlur is just plain bitmap pixels manipulation using regular java code, just in case you can't use renderscript for some reason.

You can also implement your own algorithm and pass it there.

**Comment by JustTrust** [comment]
Thanks for your advice, it helped me!
