### ISSUE TITLE
Crash using react-native-blur [Android] Fatal Exception

### ISSUE THREAD

**Issue by Titozzz** [Dimezis/BlurView#190]
Hello, react-native-blur maintainer here 👋🏻 
We are having a crash in the native android code so I thought I'd ask for help!
If you have any advice regarding the current implementation, that will also be lovely
Many thanks

1) Library version - 2.0.2
2) Device and OS version - >= API 31
3) Detailed steps to reproduce the issue
Sometime the views are not hardware accelerated and the app crashes while trying to use the new implementation (>= API 31), do you know:
a) How to detect if HW accel is enabled to fallback to old implem
b) Maybe make blurview safer to directly fallback by itself ?

4) XML layout and code for BlurView setup
Not relevant
5) Stacktrace in case of a crash
See https://github.com/Kureev/react-native-blur/issues/489, there are plenty

**Comment by Dimezis** [comment]
Yeah, I didn't account for that.
I'll make a fix to fallback to a different blur algorithm for such cases

**Comment by Titozzz** [comment]
Thank you so much, let me know when we can update

**Comment by Dimezis** [comment]
Should be fixed in `2.0.3`
