### ISSUE TITLE
About BlurView how to set fillet？

### ISSUE THREAD

**Issue by wardenlzr** [Dimezis/BlurView#192]
blurOverlayColorOnly one property can be configured

**Comment by Dimezis** [comment]
Sorry, I'm not sure what you mean.
Could you elaborate?

**Comment by wardenlzr** [comment]
Sorry,My English is not good. I think the answer is this
Create a rounded drawable, as usual, set it as a background.
And do
blurView.setOutlineProvider(ViewOutlineProvider.BACKGROUND);
blurView.setClipToOutline(true);

**Comment by wardenlzr** [comment]
But
final Drawable windowBackground = getWindow().getDecorView().getBackground();
        Log.i(TAG, "windowBackground." + windowBackground);
        RoundDrawable roundDrawable = new RoundDrawable(getResources(), drawable2Bitmap(windowBackground));
        roundDrawable.setRadius(30f);
        binding.bv.setupWith(((ViewGroup) getWindow().getDecorView()))
                .setFrameClearDrawable(roundDrawable);

private Bitmap drawable2Bitmap(Drawable drawable) {
        if (drawable == null) {
            return null;
        }

        if (drawable instanceof BitmapDrawable) {
            return ((BitmapDrawable) drawable).getBitmap();
        }

        try {
            Bitmap.Config config =
                    drawable.getOpacity() != PixelFormat.OPAQUE ? Bitmap.Config.ARGB_8888
                            : Bitmap.Config.RGB_565;
            Bitmap bitmap;
            //颜色Drawable
            if (drawable instanceof ColorDrawable) {
                //宽为2, 高为2 ??
                bitmap = Bitmap.createBitmap(2, 2, config);
            } else {
                bitmap = Bitmap.createBitmap(drawable.getIntrinsicWidth(), drawable.getIntrinsicHeight(), config);
            }
            Canvas canvas = new Canvas(bitmap);
            drawable.setBounds(0, 0, canvas.getWidth(), canvas.getHeight());
            //将 drawable 的内容绘制到 bitmap的canvas 上面去.
            drawable.draw(canvas);
            return bitmap;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

I set these, but the fillet does not take effect

**Comment by wardenlzr** [comment]
public class RoundDrawable extends BitmapDrawable {
    private Paint mPaint;   //图片画笔
    private RectF mRectF;   //创建一个矩形，将图片绘制到该矩形上。
    private Bitmap mBitmap; //需要绘制的图片

    //region 绘制图片方法
    public RoundDrawable(Bitmap mBitmap) {

        this.mBitmap = mBitmap;
        //获取图片的着色器
        BitmapShader bitmapShader = new BitmapShader(mBitmap, Shader.TileMode.CLAMP, Shader.TileMode.CLAMP);
        //创建画笔
        mPaint = new Paint();
        //画笔防锯齿
        mPaint.setAntiAlias(true);
        //将图片设置到画笔上
        mPaint.setShader(bitmapShader);
        setBounds(0, 0, mBitmap.getWidth(), mBitmap.getHeight());
    }
    //endregion

    //设置矩形大小和位置
    @Override
    public void setBounds(int left, int top, int right, int bottom) {
        super.setBounds(left, top, right, bottom);
        mRectF = new RectF(left, top, right, bottom);
    }

    //绘制图片
    @Override
    public void draw(@NonNull Canvas canvas) {
        canvas.drawRoundRect(mRectF, /*圆角x轴位置*/30,/*圆角y轴位置*/30, mPaint);
    }

    //设置图片宽度
    @Override
    public int getIntrinsicWidth() {
        return mBitmap.getWidth();
    }

    //设置图片高度
    @Override
    public int getIntrinsicHeight() {
        return mBitmap.getHeight();
    }

    //设置透明度
    @Override
    public void setAlpha(int i) {
        mPaint.setAlpha(i);
    }

    @Override
    public void setColorFilter(@Nullable ColorFilter colorFilter) {
        mPaint.setColorFilter(colorFilter);
    }

    @Override
    public int getOpacity() {
        return PixelFormat.TRANSLUCENT;
    }
}

**Comment by Dimezis** [comment]
I still don't understand.
Is the problem that you can't set rounded corners?
```
blurView.setOutlineProvider(ViewOutlineProvider.BACKGROUND);
blurView.setClipToOutline(true);
```
Should do the job with a proper rounded corner Drawable.

Or is the problem that `setFrameClearDrawable` doesn't work with this drawable? (Why is it rounded though?)

Some screenshots of expected and actual results might be helpful

**Comment by wardenlzr** [comment]
![image](https://user-images.githubusercontent.com/16572346/203528212-31fb92d7-c124-4283-84ec-4fa8a661b102.png)
How to get a round corner BlurView?

**Comment by Dimezis** [comment]
```Java
blurView.setBackgroundDrawable(roundDrawable);
blurView.setOutlineProvider(ViewOutlineProvider.BACKGROUND);
blurView.setClipToOutline(true);
```

**Comment by Dimezis** [comment]
Did that solve your issue?

**Comment by wardenlzr** [comment]
yes  thanks
