### ISSUE TITLE
android.view.ViewGroup.getViewTreeObserver()' on a null object reference

### ISSUE THREAD

**Issue by kimoandroid** [Dimezis/BlurView#193]
Hello, i am trying to display blur at recyclerview customview but it show me this Error:

**Attempt to invoke virtual method 'android.view.ViewTreeObserver android.view.ViewGroup.getViewTreeObserver()' on a null object reference**

![Screenshot_2022_12_16_18_05_18_21_80de061aead4140daa69cfda3df4a614](https://user-images.githubusercontent.com/69405523/208141955-e7fc686f-d963-4496-89fd-6d5a0ee0e631.jpg)

here the code that i used:

```java
float flt = 12f;
View decorView = getWindow().getDecorView();

ViewGroup rootView = (ViewGroup) decorView.findViewById(R.id.content);

Drawable windowBackground = decorView.getBackground();

blurView.setupWith(rootView, new RenderScriptBlur(MainActivity.this))
.setFrameClearDrawable(windowBackground)
.setBlurRadius(flt)
.setBlurAutoUpdate(true);
```

The XML Code:

```xml
<LinearLayout 
  android:id="@+id/content" 
  android:layout_width="match_parent" 
  android:layout_height="wrap_content" 
  android:layout_marginLeft="4dp" 
  android:layout_marginTop="2dp" 
  android:layout_marginRight="4dp" 
  android:layout_marginBottom="10dp" 
  android:orientation="vertical"> 
          <eightbitlab.com.blurview.BlurView 
           android:id="@+id/blurView" 
           android:layout_width="match_parent" 
           android:layout_height="match_parent" 
           android:orientation="vertical"> 
                     <TextView 
                      android:id="@+id/text1" 
                      android:focusable="false" 
                      android:layout_width="wrap_content" 
                      android:layout_height="wrap_content" 
                      android:padding="8dp" 
                      android:text="TextView" 
                      android:textSize="12sp" 
                      android:textColor="#000000" /> 
          </eightbitlab.com.blurview.BlurView> 
 </LinearLayout>
```

- Library Version: 2.0.3
- Android Version: 12

**Comment by Dimezis** [comment]
Your decorView.findViewById(R.id.content) is null most likely

**Comment by kimoandroid** [comment]
> Your decorView.findViewById(R.id.content) is null most likely

But i've added the linear as you see in code
findViewById(R.id.content)

i've tried the same source on another new app and it worked, i don't know why it doesn't work here

**Comment by Dimezis** [comment]
I don't see the full code, so I can't tell you why. But if it's null, it's not a library bug

**Comment by kimoandroid** [comment]
> I don't see the full code, so I can't tell you why. But if it's null, it's not a library bug

the code below is inside recyclerView Adapter:
```java
float flt = 12f;
View decorView = getWindow().getDecorView();

ViewGroup rootView = (ViewGroup) decorView.findViewById(R.id.content);

Drawable windowBackground = decorView.getBackground();

blurView.setupWith(rootView, new RenderScriptBlur(MainActivity.this))
.setFrameClearDrawable(windowBackground)
.setBlurRadius(flt)
.setBlurAutoUpdate(true);
```

**Comment by Dimezis** [comment]
So is it null?

**Comment by kimoandroid** [comment]
> Attempt to invoke virtual method 'android.view.ViewTreeObserver android.view.ViewGroup.getViewTreeObserver()' on a null object reference

Yes, But Finally i've solved it after i used this condition:
```java
if (rootView != null) {
rootView.getViewTreeObserver();
}
```

**Comment by Dimezis** [comment]
If that solves your issue, there's just something wrong with your setup.
Why are you setting the direct parent of the BpurView as the root view? Why are you looking it up in the decorView?

**Comment by kimoandroid** [comment]
> If that solves your issue, there's just something wrong with your setup.
> Why are you setting the direct parent of the BpurView as the root view? Why are you looking it up in the decorView?

Yes, as I mentioned this code is inside Recycler View Adapter linked with custom view

This is same like Facebook posts but the post background is blurred instead of white color, this is the nearest example.
