### ISSUE TITLE
Could not resolve com.github.Dimezis:BlurView:version-2.0.2.

### ISSUE THREAD

**Issue by wouterds** [Dimezis/BlurView#194]
**1) Library version**
`@react-native-community/blur ^4.3.0`

**2) Device and OS version**
Android 12 emulator

**3) Detailed steps to reproduce the issue**
`yarn android`

**4) XML layout and code for BlurView setup**
Unrelated

**5) Stacktrace in case of a crash**
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':react-native-community_blur:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':react-native-community_blur:debugCompileClasspath'.
   > Could not resolve com.github.Dimezis:BlurView:version-2.0.2.
     Required by:
         project :react-native-community_blur
      > Skipped due to earlier error
      > Skipped due to earlier error
```

I'm not sure if this is an issue with Jitpack or something went wrong during publishing?

**Comment by wouterds** [comment]
wrong repository

**Comment by rajeshmarotu** [comment]
@wouterds I'm facing this issue without any code changes recently. Did you find solution for this ? Thanks

**Comment by wouterds** [comment]
I copied ~/.gradle from a colleague who still had it in cache.

**Comment by rajeshmarotu** [comment]
@Dimezis can you help us with this issue ?

**Comment by Dimezis** [comment]
Looks like some Jitpack issue.
I can't even log in or check the build status

**Comment by Dimezis** [comment]
Does it work for you now? For whatever reason, the 2.0.2 build failed on Jitpack, but I can't rerun it 🤷
If it still doesn't work, you can try 2.0.3
