### ISSUE TITLE
Could not find com.github.Dimezis:BlurView:version-2.0.3"

### ISSUE THREAD

**Issue by RiotGoesWoof** [Dimezis/BlurView#199]
Please include:
1) 2.0.3
2) Doesn't Apply. Build issue
3) Added jitpack to build.gradle and added implementation as such: `implementation 'com.github.Dimezis:BlurView:version-2.0.3'`
4) Build issue

Just get this whenever I try to build. Gradle Sync works alright, Build fails with this error. 

![image](https://user-images.githubusercontent.com/5066073/229223255-40087d6b-af9e-435c-b2f5-da5db541246c.png)

On Android Studio Dolphin:
![image](https://user-images.githubusercontent.com/5066073/229223382-491e7029-acb4-41a4-9aca-43cd93c225ad.png)

**Comment by Dimezis** [comment]
I guess you didn't add Jitpack to the list of repos

**Comment by RiotGoesWoof** [comment]
I think I did unless I'm missing something?

![image](https://user-images.githubusercontent.com/5066073/229227569-95936f83-ac56-44dc-8e22-e8f710bbd5af.png)

**Comment by Dimezis** [comment]
Just checked, works fine for me.
Maybe it was some temporary Jitpack problem?

**Comment by RiotGoesWoof** [comment]
Just tried again. still no dice.

**Comment by matr1xp** [comment]
Was this ever fixed?
I still get the issue. 

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform BlurView-version-2.0.3.aar (com.github.Dimezis:BlurView:version-2.0.3) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not find BlurView-version-2.0.3.aar (com.github.Dimezis:BlurView:version-2.0.3).
        Searched in the following locations:
            https://www.jitpack.io/com/github/Dimezis/BlurView/version-2.0.3/BlurView-version-2.0.3.aar
```

**Comment by matr1xp** [comment]
Duplicate of [#6766](https://github.com/jitpack/jitpack.io/issues/6766)

**Comment by Dimezis** [comment]
Just use the latest version folks. 
There is some problem with the Jitpack - it tried rebuilding some of the lib versions but failed because one dependency was no longer available. 
This ended up breaking previously existing artifacts

**Comment by Liew-Yu** [comment]
same issue here. 2.0.2 works fine in my other project, but 2.0.3 doesn't
