### ISSUE TITLE
    Crashed with this:   java.lang.NoClassDefFoundError: Failed resolution of: Landroid/graphics/RenderNode;

### ISSUE THREAD

**Issue by philp55** [Dimezis/BlurView#200]
Please include:
1) com.github.Dimezis:BlurView:version-2.0.3
2) Huawei and Android 8, pixel and Android 11
3) just run it and it'll crash
4) XML down here
<eightbitlab.com.blurview.BlurView
        android:id="@+id/blurView"
        android:layout_width="match_parent"
        android:layout_height="@dimen/_70sdp"
        android:background="@drawable/rounded_top_corners"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent">

        <androidx.constraintlayout.widget.ConstraintLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <ImageView
                android:id="@+id/dashBoard"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:src="@drawable/ic_dashboard"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toStartOf="@+id/camera"
                app:layout_constraintHorizontal_bias="0.5"
                app:layout_constraintHorizontal_chainStyle="spread_inside"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent" />

            <ImageView
                android:id="@+id/camera"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:src="@drawable/ic_camera"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toStartOf="@+id/myUploads"
                app:layout_constraintHorizontal_bias="0.5"
                app:layout_constraintStart_toEndOf="@+id/dashBoard"
                app:layout_constraintTop_toTopOf="parent" />

            <ImageView
                android:id="@+id/myUploads"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:src="@drawable/ic_myuploads"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintHorizontal_bias="0.5"
                app:layout_constraintStart_toEndOf="@+id/camera"
                app:layout_constraintTop_toTopOf="parent" />
        </androidx.constraintlayout.widget.ConstraintLayout>

    </eightbitlab.com.blurview.BlurView>
5) 
ava.lang.NoClassDefFoundError: Failed resolution of: Landroid/graphics/RenderNode;
                                                                                                    	at eightbitlab.com.blurview.RenderEffectBlur.<init>(RenderEffectBlur.java:25)
                                                                                                    	at com.io.HomeActivity.blur(HomeActivity.kt:176)
                                                                                                    	at com.io.HomeActivity.setUpCustomBottomBar(HomeActivity.kt:81)

**Comment by Dimezis** [comment]
`RenderEffectBlur` is available from Android 12 (S), SDK 31.
There's a lint warning when you try to use it without checking for the SDK level.
