### ISSUE TITLE
Failed to run on emulator(x86), also can't blur in Fragment

### ISSUE THREAD

**Issue by a512509050** [Dimezis/BlurView#21]

**Comment by a512509050** [comment]
Demo downloaded can run on the emulator,and if use in Fragment, the background is not right displayed.I use the same code as in demo

**Comment by Dimezis** [comment]
As I already said, It blurs background in BlurView's position. In your case, position is relative to the fragment, which is 0x0, I bet.

Hence BlurView can't know where is the actual position it should start blur.
Do not put it in fragment to blur something below the fragment itself.

**Comment by a512509050** [comment]
Thanks, it helps me a lot. :+1:

**Comment by Dimezis** [comment]
Regarding the emulator, it just works, on any architecture. If you have some specific error, paste it here

**Comment by a512509050** [comment]
08-02 14:37:11.013 21835-21835/? E/RenderScript_jni: Error loading RS jni library: java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/com.example.administrator.myapplication/files/instant-run/dex/slice-wire-runtime-2.1.2_d0340976fd02a9eee41f6e7218093f6c5bc61d2a-classes.dex", dex file "/data/data/com.example.administrator.myapplication/files/instant-run/dex/slice-support-annotations-23.4.0_b35ca2f09419d2858124cc1d48b31654b29da950-classes.dex", dex file "/data/data/com.example.administrator.myapplication/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.example.administrator.myapplication/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.example.administrator.myapplication/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.example.administrator.myapplication/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.example.administrator.myapplication/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.example.administrator.myapplication/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.example.administrator.myapplication/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.example.administrator.myapplication/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.example.administrator.myapplication/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.example.administrator.myapplication/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.example.administrator.myapplication/files/instant-run/dex/slice-renderscript-v8_fad889ba4f9eba92591cc43e5c4715a1830c4c2d-classes.dex", dex file "/data/data/com.example.administrator.myapplication/files/instant-run/dex/slice-okio-1.6.0_c410569bd3ae660f2a7eceb3af69efc833b46b70-classes.dex", dex file "/data/data/com.example.administrator.myapplication/files/instant-run/dex/slice-me.kaelaela-verticalviewpager-1.0.0_007ee1e68b4591e400b3e540f7884a7341a5c79d-classes.dex", dex file "/data/data/com.example.administrator.myapplication/files/instant-run/dex/slice-internal_impl-23.4.0_328d3ec8a95e6679190da9647e839e8a8853db11-classes.dex", dex file "/data/data/com.example.administrator.myapplication/files/instant-run/dex/slice-eventbus-3.0.0_338198e230e883acd6c9c82ca46ba5fc3096755c-classes.dex", dex file "/data/data/com.example.administrator.myapplication/files/instant-run/dex/slice-core-3.2.1_3f96f72d8bc40481fc852122e0314b3485c288eb-classes.dex", dex file "/data/data/com.example.administrator.myapplication/files/instant-run/dex/slice-com.umeng.message_v2.8.1_8a573a5058c111bcffcf36178d5a2a02d99ee07d-classes.dex", dex file "/data/data/com.example.administrator.myapplication/files/instant-run/dex/slice-com.sunfusheng-marqueeview-1.0.0_ef1c70881ae468dc601b2f01463a3e7f5a219b52-classes.dex", dex file "/data/data/com.example.administrator.myapplication/files/instant-run/dex/slice-com.github.iwgang-countdownview-2.1_3eecc43f69dddfb6dfb1d75ee376c88e0e854a17-classes.dex", dex file "/data/data/com.example.administrator.myapplication/files/instant-run/dex/slice-com.eightbitlab-blurview-1.1.2_69a09c6179b9c330439b438e388e4bb6f79b6407-classes.dex", dex file "/data/data/com.example.administrator.myapplication/files/instant-run/dex/slice-com.android.support-support-vector-drawable-23.4.0_d5c9f8f5acde79bd0edb364e91ae42977a251980-classes.dex", dex file "/data/data/com.example.administrator.myapplication/files/instant-run/dex/slice-com.android.support-support-v4-23.4.0_1507d306ff1dbbb0fd35e87cf8f2c81c43b0d437-classes.dex", dex file "/data/data/com.example.administrator.myapplication/files/instant-run/dex/slice-com.android.support-recyclerview-v7-23.4.0_57c34dc5465d994d481ecfd11503300888748691-classes.dex", dex file "/data/data/com.example.administrator.myapplication/files/instant-run/dex/slice-com.android.support-design-23.4.0_5a4ff0dd53c321e7fed6051510ae0b6c7d012f3f-classes.dex", dex file "/data/data/com.example.administrator.my

**Comment by Dimezis** [comment]
Same for demo project? what build tools version are you using?

**Comment by a512509050** [comment]
no, demo runs well ,and I put code in another project of me, it also runs well, only happens in this.
My tools version is "23.0.3"

**Comment by a512509050** [comment]
Seems not a big problem,no need to take time worrying about it

**Comment by a512509050** [comment]
Sorry for trouble again @Dimezis  this layout is in MainActivity. I put a ScrollView in the Framelayout, the LinearLayout below is a navigation bar of my app.However, it just doesn't work if I add the `android:layout_above="@+id/blurView"` I really wish you could help me if you had time,Thanks.

**Comment by a512509050** [comment]
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/white"
    android:fitsSystemWindows="true"
    tools:context="com.juying.warenqi.activity.MainActivity">

    <FrameLayout
        android:id="@+id/frag_main"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_above="@+id/blurView"
        android:layout_gravity="center"
        android:persistentDrawingCache="animation" />

    <eightbitlab.com.blurview.BlurView
        android:id="@+id/blurView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        app:blurOverlayColor="#50ffffff">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal">

            <LinearLayout
                android:id="@+id/lly_home_btn"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_centerVertical="true"
                android:layout_weight="1"
                android:orientation="vertical"
                android:paddingBottom="3dp"
                android:paddingTop="6dp">

                <ImageView
                    android:id="@+id/img_home_pic"
                    android:layout_width="23dp"
                    android:layout_height="23dp"
                    android:layout_gravity="center_horizontal"
                    android:src="@drawable/main_home" />

                <TextView
                    android:id="@+id/tv_home_text"
                    style="@style/grey_12sp"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center_horizontal"
                    android:layout_marginTop="3dp"
                    android:text="@string/main_home" />
            </LinearLayout>

            <LinearLayout
                android:id="@+id/lly_task_btn"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_centerVertical="true"
                android:layout_weight="1"
                android:orientation="vertical"
                android:paddingBottom="3dp">

                <RelativeLayout
                    android:layout_width="match_parent"
                    android:layout_height="0dp"
                    android:layout_weight="1">

                    <ImageView
                        android:id="@+id/img_task_pic"
                        android:layout_width="23dp"
                        android:layout_height="23dp"
                        android:layout_centerHorizontal="true"
                        android:layout_marginTop="6dp"
                        android:src="@drawable/main_mission" />

                    <TextView
                        android:id="@+id/bb_task_count"
                        style="@style/white_10sp"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_toRightOf="@+id/img_task_pic"
                        android:background="@drawable/bubble_bg"
                        android:gravity="center"
                        android:padding="2dp"
                        android:visibility="invisible" />
                </RelativeLayout>


                <TextView
                    android:id="@+id/tv_task_text"
                    style="@style/grey_12sp"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center_horizontal"
                    android:layout_marginTop="3dp"
                    android:text="@string/main_task" />
            </LinearLayout>

            <LinearLayout
                android:id="@+id/lly_my_task_btn"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_centerVertical="true"
                android:layout_weight="1"
                android:orientation="vertical"
                android:paddingBottom="3dp"
                android:paddingTop="6dp">


                <ImageView
                    android:id="@+id/img_my_task_pic"
                    android:layout_width="23dp"
                    android:layout_height="23dp"
                    android:layout_gravity="center_horizontal"
                    android:src="@drawable/main_my_task" />

                <TextView
                    android:id="@+id/tv_my_task_text"
                    style="@style/grey_12sp"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center_horizontal"
                    android:layout_marginTop="3dp"
                    android:text="@string/main_my_task" />
            </LinearLayout>

            <LinearLayout
                android:id="@+id/lly_personal_btn"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_centerVertical="true"
                android:layout_weight="1"
                android:orientation="vertical"
                android:paddingBottom="3dp"
                android:paddingTop="6dp">


                <ImageView
                    android:id="@+id/img_personal_pic"
                    android:layout_width="23dp"
                    android:layout_height="23dp"
                    android:layout_gravity="center_horizontal"
                    android:src="@drawable/main_me" />

                <TextView
                    android:id="@+id/tv_personal_text"
                    style="@style/grey_12sp"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center_horizontal"
                    android:layout_marginTop="3dp"
                    android:text="@string/main_personal" />
            </LinearLayout>

        </LinearLayout>

    </eightbitlab.com.blurview.BlurView>
</RelativeLayout>

**Comment by Dimezis** [comment]
Your layout is completely wrong, you put all the content inside the BlurView.
Look at the demo setup. The point is to have a layout with z order (FrameLayout for example), put the content inside, and put the BlurView on the same hierarchy level. BlurView needs to be on top of content you want to blur.

**Comment by a512509050** [comment]
I've tried use FrameLayout outside,but part of the content will be blocked at the bottom by the navigation bar.What should I do?
![11](https://cloud.githubusercontent.com/assets/18045999/17356487/51b5c198-598a-11e6-94d9-57afe996e6b5.gif)

**Comment by Dimezis** [comment]
Again, just look at the demo setup.
Add padding for ScrollView and
`android:clipToPadding="false"`
