### ISSUE TITLE
Not working with custom corner shape

### ISSUE THREAD

**Issue by akashwebapps** [Dimezis/BlurView#214]
When I define the radius for each corner differently in a drawable shape, it clips out the children and shows a rectangular box. However, if I keep the corner radius the same without defining each corner individually, it works well.

**Comment by Dimezis** [comment]
Yes, this is a known limitation. 
`clipToOutline` doesn't work with complex shapes.
You might want to subclass the BlurView and clip it to path on a Canvas level
