### ISSUE TITLE
RenderScriptBlur deprecated, what now

### ISSUE THREAD

**Issue by CarlosCMD** [Dimezis/BlurView#218]
Please include:
1) Library version: Latest
2) Device and OS version: 9

How to use RenderEffectBlur? since it crashes with error: `NoClassDefFoundError android.graphics.RenderNote`

**Comment by Dimezis** [comment]
RenderEffectBlur targets Android 12 and has the corresponding annotation.
You can't use it on older versions. 
Use the deprecated RenderscriptBlur instead.
