### ISSUE TITLE
Using high-resolution images may cause flickering in blurry areas

### ISSUE THREAD

**Issue by rophy1** [Dimezis/BlurView#220]
Firstly, I ran the code provided by this repository normally.
Then I tried adding a high-resolution image (4K) in fragment_stcroll.xml and compiling it to run. Detected flickering in the blurry areas of the top seekbar and bottom navigation bar.
![image](https://github.com/user-attachments/assets/977417c3-3150-4fe4-9836-94ea539d9a88)

My screen recording：

https://github.com/user-attachments/assets/f6a4e3f2-6d9a-4c79-afca-03b62bf21e62

**Comment by Dimezis** [comment]
It's not really about the resolution of an image.
Anything with fine details can cause flicker on a small blur radius, because it gets heavily downsampled for the blur pass, for performance reasons.

Use a larger blur radius and/or `RenderEffectBlur`

**Comment by rophy1** [comment]
Okay, got it.  Thanks : )
