### ISSUE TITLE
Try to blur each item in adapter / recyclerview

### ISSUE THREAD

**Issue by Encodica** [Dimezis/BlurView#221]
Please include:
1) Library version : 2.0.5
2) Device and OS version : OnePlus / android 14

3) Detailed steps to reproduce the issue

I use a BlurView in the layout of the Holder
In the adapter / onBindViewHolder I try to blur
blurView.setupWith(toBlur, new RenderScriptBlur(act))
                .setFrameClearDrawable(background)
                .setBlurRadius(10f)
                .setBlurAutoUpdate(true)
                .setBlurEnabled(true);

4) XML layout and code for BlurView setup

```
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout
xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">

        android:layout_width="match_parent"
        android:layout_height="wrap_content"

        android:layout_marginStart="@dimen/padding_extra"
        android:layout_marginTop="@dimen/padding_extra"
        android:layout_marginEnd="@dimen/padding_extra"

        >



            <eightbitlab.com.blurview.BlurView
                android:id="@+id/blurView"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:blurOverlayColor="@color/colorBgrMaskTrans"                >

                <com.google.android.material.textview.MaterialTextView
                    android:id="@+id/tvTitle"

                    style="@style/TextViewBoldLarge"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:background="@color/transparent"
                    android:padding="@dimen/padding_extra"

                    android:text="Test"
                    android:textColor="@color/colorTextHigh"

                    app:layout_constraintBottom_toBottomOf="parent"
                    app:layout_constraintEnd_toEndOf="parent"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintTop_toTopOf="parent"


                    />

            </eightbitlab.com.blurview.BlurView>

</androidx.constraintlayout.widget.ConstraintLayout>
```

5) Stacktrace in case of a crash
No Crash
The problem is that when I scroll the RecyclerView the following items do not blur the right parent view group

[Please see captured video here](https://clients.encodica.com/nema/Record_2024-09-16-00-35-27.mp4)

**Comment by Dimezis** [comment]
Does the same happen if you move the setup from `onBindViewHolder` to `onCreateViewHolder`?

**Comment by Encodica** [comment]
Unfortunately yes, the same behavior. :(

**Comment by Encodica** [comment]
Finally was my mistake, I was using a custom view inside the BlurView causing that problem!
Now I have a final issue...
[Please look at the video](https://clients.encodica.com/nema/Screen_recording_20240916_212411.webm)
Some items are bluring right and updating real time, some others, at the center of the list, dont update blur and remain frozen when scrill.

**Comment by Dimezis** [comment]
@Encodica 
Ok, but I still recommend setting it up in `onCreateViewHolder`, that would be **much** more efficient

**Comment by Encodica** [comment]
Everything is ok, I use onCreateViewHolder.
When I use recyclerView.startLayoutAnimation(); the blur is ok, but I don't have any animation , only at the 1st, 2nd holders.

**Comment by Dimezis** [comment]
I don't think I can help with that
