### ISSUE TITLE
blur 

### ISSUE THREAD

**Issue by Knight-xiaolu** [Dimezis/BlurView#28]
how to  change the blur effect?  and  how to close blur

**Comment by Dimezis** [comment]
There are no blur effects. 
Only the blur algorithm setup, like 

`blurView.setupWith(rootView).blurAlgorithm(new RenderScriptBlur(this, true))`

and `setOverlayColor` to set a color which will be drawn over blur.

I'm not sure what does "close blur" mean, but if you are talking about disabling the blur, you can call
`setBlurEnabled(false)` starting from 1.2.0 version.

If you want to add some additional processing for a bitmap, you can implement your custom BlurAlgorithm, which is pretty easy.

**Comment by Knight-xiaolu** [comment]
thank you ,  
if (!blurController.isInternalCanvas(canvas)) {
            blurController.drawBlurredContent(canvas);
            drawColorOverlay(canvas);
            super.draw(canvas);
        }
if  the background is change  ,i don't know the canvas is  the same

**Comment by Knight-xiaolu** [comment]
. sorry  the 1.2 code is changed
