### ISSUE TITLE
Question: is the blurring done on the main thread?

### ISSUE THREAD

**Issue by premnirmal** [Dimezis/BlurView#3]
I don't see any threading going on with `BlurAlgorithm#blur(Bitmap, float)` or with `BlurController#drawBlurredContent(Canvas)`. Blurring on the main thread concerns me. Let me know if I'm wrong or if I've overlooked the threading code

**Comment by Dimezis** [comment]
Yes, the blurring is done on the main thread. 
Threading would add an unnecessary complexity of synchronization and overhead on context switching and memory.

From my point of view, there is no sense to process blur in background if it can be done fast enough in main thread, especially if you always need the latest snapshot of background bitmap.

Correct me if I'm wrong, or you have ideas how to implement it efficiently.

**Comment by premnirmal** [comment]
Blurring is a very intense process and it can drop the UI thread frame-rate considerably. For a simple app (the sample app) that just blurs the view on the UI thread there probably won't be a UI freeze that's very noticeable but for industry level applications it will definitely cause a significant amount of blocking on the UI thread. It's good that you're scaling the bitmap, but also definitely worth putting the blur process on a BG thread, then posting the result on the view's handler using `View#post(Runnable)`.

http://trickyandroid.com/advanced-blurring-techniques/

http://nicolaspomepuy.fr/blur-effect-for-android-design/

I'll post a fix for this in a PR

**Comment by Dimezis** [comment]
Thanks, I have read both of them.
Well, I would be grateful for that kind of contribution.

**Comment by tembloroso** [comment]
Great library, thanks for the effort! But @premnirmal is right, I was going to use your library to blur the background of a sliding View I have until I read this comment.

 I'll add it when the blur is done in a background thread, so I can help you guys test it. 

Thanks!
