### ISSUE TITLE
BlurView fails to blur underlying activities

### ISSUE THREAD

**Issue by CHPraxis** [Dimezis/BlurView#31]
Hello- I'm a bit stumped on this.  I can't get it to work.

I'm creating a new activity that contains a blurview, with the intent of blurring the activity underneath.  My goal is to have this blurview take up the entire screen, so I have a full-screen blurred view, but for this test I didn't even make it full screen, and it still crashes.

Here's my entire onCreate for my Activity:

```
public class BlurWindowActivity extends AppCompatActivity {


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_blur_window);

        BlurView blurView = (BlurView)findViewById(R.id.blurView);
        final float radius = 16;



        final View decorView = getWindow().getDecorView();
        //Activity's root View. Can also be root View of your layout
        final View rootView = decorView.findViewById(android.R.id.content);
        //set background, if your root layout doesn't have one
        final Drawable windowBackground = decorView.getBackground();

        blurView.setupWith(rootView)
                .windowBackground(windowBackground)
                .blurAlgorithm(new RenderScriptBlur(this, true)) //Optional, enabled by default. User can have custom implementation
                .blurRadius(radius);
}
```

Here's my entire XML, "activity_blur_window.xml".

```
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
             xmlns:app="http://schemas.android.com/apk/res-auto"
             xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    <eightbitlab.com.blurview.BlurView
    android:id="@+id/blurView"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:blurOverlayColor="@color/md_blue_50">
    <TextView
        android:layout_width="match_parent"
        android:layout_height="50dp"
        android:text="@string/hello_blank_fragment"/>

</eightbitlab.com.blurview.BlurView>
    </FrameLayout>
```

The moment I instantiate this, it crashes. 

Here's the first part of the crash.

> 09-06 15:45:24.185 6914-6914/com.myapp E/art: Failed to register native method android.support.v8.renderscript.RenderScript.rsnScriptForEach(JJI[JJ[B[I)V in /data/data/com.myapp/files/instant-run/dex/slice-renderscript-v8_723e22d4b50ba946bb48a8a78fc2e239fc80c235-classes.dex
> 09-06 15:45:24.185 6914-6914/com.myapp  E/art: ----- class 'Landroid/support/v8/renderscript/RenderScript;' cl=0x12cb72e0 -----
> 09-06 15:45:24.185 6914-6914/com.myapp  E/art:   objectSize=2330 (744 from super)

From my build.gradle:

```
defaultConfig {
        applicationId "com.myapp"
        minSdkVersion 19
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
        renderscriptTargetApi 24
        renderscriptSupportModeEnabled true
    }
```

What is causing this crash?

**Comment by Dimezis** [comment]
Hey.

Do you have the same issue with example project?
Which device are you using?
What is your build tools version?
Try to make renderscriptTargetApi, targetSdkVersion and build tools version the same.

**Comment by CHPraxis** [comment]
Hm! I've got some more details for you.  Thanks for the help.

I'm running on a Nexus 5 preset emulator on API 23.

I fired up the example project, and it worked fine.
I tweaked the build tools and renderscriptTargetApi and targetSdkVersion to be identical to mine, and started getting a similar error.  So it looks like that might be it.  So I reverted in the sample, and matched mine to be similar, and the crash stopped.  However, still no blur.


However- your sample project is a blurview that is blurring things in the same activity.  I am trying to create a new activity and blur the ones underneath.  So...I created a new activity in the sample project to accomplish that.

The new activity is as barebones as possible.  I gave it a transparent theme.   I used the default RelativeLayout and put a BlurView inside it, set to match parent.  The RelativeLayout by default had a 16dp padding.


Unfortunately, it still doesn't work right.


![See image](http://i.imgur.com/ZuyCLYK.png)

It seems to simply darken the area, instead of blurring the view underneath.  Does BlurView fail to see the underlying activity?

Here is the code, a modified version of your sample project that adds a simple activity.  All changes:

BlurActivity.java:
```
package com.eightbitlab.blurview_sample;

import android.graphics.drawable.Drawable;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.view.View;

import eightbitlab.com.blurview.BlurView;
import eightbitlab.com.blurview.RenderScriptBlur;

public class BlurActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_blur);


        BlurView blurView = (BlurView)findViewById(R.id.blurView);
        final float radius = 20f;



        final View decorView = getWindow().getDecorView();
        //Activity's root View. Can also be root View of your layout
        final View rootView = decorView.findViewById(android.R.id.content);
        //set background, if your root layout doesn't have one
        final Drawable windowBackground = decorView.getBackground();

        blurView.setupWith(rootView)
                .windowBackground(windowBackground)
                .blurAlgorithm(new RenderScriptBlur(this, true)) //Optional, enabled by default. User can have custom implementation
                .blurRadius(radius);
    }
}

```

activity_blur.xml:
<?xml version="1.0" encoding="utf-8"?>
```
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    tools:context="com.eightbitlab.blurview_sample.BlurActivity">

    <eightbitlab.com.blurview.BlurView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/blurView">

    </eightbitlab.com.blurview.BlurView>
    

</RelativeLayout>

```

Added to AndroidManifest.xml:
```
 <activity android:name=".BlurActivity"
            android:theme="@style/AppTheme.Translucent">
        </activity>
```

Added to MainActivity.java:
```
    @Override
    protected void onStart() {
        super.onStart();

        Intent intent = new Intent(this, BlurActivity.class);
        startActivity(intent);
    }
```


[Download here.](https://dl.dropboxusercontent.com/u/2741387/BlurView-praxis-activity.zip)

**Comment by Dimezis** [comment]
Unfortunately that's not possible, because there's no way to retrieve the view of underneath activity.
But you can try to use fullscreen fragment with BlurView within the same activity. Not 100% sure if it will work though :) But at least it's possible theoretically.

**Comment by CHPraxis** [comment]
So after a couple hours of tweaking, I sort of got it working!  What I did was take a screenshot of the sending activity and include it in the intent, then set that to the background view of the new transparent Activity's lowest layer.  Only negative is that it skips the Activity's animation in for some reason.


I'll test out switching to a fullscreen fragment- thanks for the help!
