### ISSUE TITLE
the  blur view not work  good  sometime

### ISSUE THREAD

**Issue by Knight-xiaolu** [Dimezis/BlurView#32]
this  is error  
![img_20160913_112535](https://cloud.githubusercontent.com/assets/16163688/18460582/4722083c-79a5-11e6-8363-91fae49bedb2.jpg)

this  is correct 
![img_20160913_112930](https://cloud.githubusercontent.com/assets/16163688/18460600/72c4860e-79a5-11e6-8dec-901ced7cf865.jpg)
![image](https://cloud.githubusercontent.com/assets/16163688/18460634/b016d78c-79a5-11e6-9813-8f3298ce1d77.png)

**Comment by Dimezis** [comment]
I didn't understand anything, please spend a time to express your problem better. 

And please, don't use a BlurView that way. What's the point of blurring a static image?
You can do it without a BlurView.

setImageBitmap happens asynchronously, so keep blur enabled before changing image bitmap.

**Comment by Knight-xiaolu** [comment]
...no,this  is a default  image,when    user  not a head,
