### ISSUE TITLE
How to blur Google Maps Fragment?

### ISSUE THREAD

**Issue by solareye** [Dimezis/BlurView#33]

**Comment by Dimezis** [comment]
Unfortunately there's no way to do that, because `MapFragment` uses `SurfaceView` to draw its content.

**Comment by solareye** [comment]
But `MapFragment` can make snapshot by `mMap.snapshot(callback)`

Thanks

**Comment by Dimezis** [comment]
@solareye 
Yes, BUT...

1) When `BlurView` traverses the view hierarchy, it has no knowledge about the fragments. Basically, in Android View can know nothing about fragments, in a hierarchy it's just another View from its perspective (and it really is). So you can't call Fragment's methods during traverse, even if you will try explicitly cast it to `MapFragment`. 
It just doesn't work that way. And it's not acceptable for `BlurView` flow.

2) This method is async, which is not really suitable for current API

3) Even if we forget about previous 2 points...
generating a new full sized Bitmap (a snapshot) nonstop is not acceptable for our needs

**Comment by ChristopherDuran** [comment]
> Unfortunately there's no way to do that, because `MapFragment` uses `SurfaceView` to draw its content.

Wow, really i have worked about 4 hours with your library trying that jaja lol. But work with a normal Fragment or too not work? i thinked put a layout over the MapFragment and not work for the momment for me, i have NullPointerException, so, your library not work with any Fragment?. Psdt: your library is awesome, nice to use it others cases

**Comment by Dimezis** [comment]
It works with fragments
