### ISSUE TITLE
How to use BlurView correctly in popup window?

### ISSUE THREAD

**Issue by timshinlee** [Dimezis/BlurView#34]
Thanks for this great job, but now I am a little puzzled by this question.
 I need to show a full-screen and translucent popup window, blurring the background. At first I tried to add BlurView as the root view of popup window, and called setupWith() with itself as the argument. But nothing was blurred. 
Then I managed to blur the background by adding BlurView in the activity, and set its visibility every time I show popup window, but I think this is a compromise.
Is there any way to use BlurView in popup window also blurring the background activity? Or more commonly, will BlurView work correctly when background is changeable?  Thanks for your reading!

**Comment by Dimezis** [comment]
You have to call setupWith() on activity's view, not on the popup window's view. 
Translucent popup window itself draws nothing, so it has to be activity's view.
But I assume that it might be not possible with popup window.
Can you please check this, and also check if DialogFragment with the same setup does the work?

**Comment by timshinlee** [comment]
I tried, but it seems impossible to work in a  dialog or popup window. Anyway, I am satisfied with the current situation. Thanks a lot! Happy new year! ;-)
