### ISSUE TITLE
Rotate BlurView in xml also rotate blurred content

### ISSUE THREAD

**Issue by vxhviet** [Dimezis/BlurView#35]
Hi,

 Thank your for this awesome lib. I have a small issue when I try to rotate the BlurView in xml by -45 degree to replicate a diamond, like this:

```xml
<BlurView
        android:layout_width="64dp"
        android:layout_height="64dp"
        android:rotation="-45"
        app:blurOverlayColor="@color/black_50" />
```

And as you could have guessed the blurred content get rotated as well which create a weird effect.
I'm thinking about pre-rotating the `internalBitmap` in `BlockingBlurController` by 45 degree to counteract this effect without much success. 

Another way I'm thinking about is to have the `internalBitmap` actually bigger than the `canvas`, and only rotate the `canvas` to achieve this effect.

Any suggestion is highly appreciated.

**Comment by Dimezis** [comment]
Hi,
Really good spot!

After a quick look I think that the only legit solution would be increasing `internalBitmap` size and rotating the canvas to properly fit a diamond. So you have to calculate the right size based on the view rotation.
I will think of it more when I'll have a time, maybe I will figure some generic solution to include into a lib. 
Please ping me here in case you will solve it somehow.

**Comment by vxhviet** [comment]
Hi,

After messing around with `BitmapShader` and  `PorterDuff` trying to clip a rectangle `BlurView` into a diamond without much success, I went back to the big-bitmap-small-canvas method. This is a quick and dirty fix for anyone is looking for a good enough solution.

```xml
<BlurView
        android:layout_width="64dp"
        android:layout_height="64dp"
        android:rotation="-45"
        app:blurOverlayColor="@color/black_50" />
```

For the sake of brevity, I'll just double the size of the `internalBitmap`. You can figure out an algorithm to calculate the bitmap's size based on the rotation quite easily if that's your requirement.

In `BlockingBlurController`:

```java
private void allocateBitmap(int measuredWidth, int measuredHeight) {
        ...
        internalBitmap = Bitmap.createBitmap(scaledWidth * 2, scaledHeight * 2, blurAlgorithm.getSupportedBitmapConfig());
    }

private void draw(Canvas canvas) {
        canvas.save();
        canvas.scale(scaleFactor * roundingWidthScaleFactor, scaleFactor * roundingHeightScaleFactor);

        // add these for counter rotation
        canvas.translate(-internalBitmap.getWidth()/4, -internalBitmap.getHeight()/4);
        canvas.rotate(45, internalBitmap.getWidth()/2, internalBitmap.getHeight()/2);

        canvas.drawBitmap(internalBitmap, 0, 0, null);
        canvas.restore();
    }
```

This fix is far from perfect as the blurred content is still a bit above the actual content but by using a high enough blur radius, the effect is quite okay for my use case.

Will update with a better solution when i have more time to work on this.

**Comment by Dimezis** [comment]
Assuming you have equal width and height and 45 degrees rotation, try `size = sqrt(width^2 + width^2)`, this should produce perfect diamond alignment (Pythagorean theorem).

**Comment by vxhviet** [comment]
Thank you Dimezis,

Also a small tip for anyone want to test the alignment of the `internalBitmap` behind the `canvas`. You can go to Developer option and enable Debug GPU overdraw -> show Overdraw area. The blurred bitmap will be rendered nicely.
