### ISSUE TITLE
How to get a round corner BlurView?

### ISSUE THREAD

**Issue by ScuAdam** [Dimezis/BlurView#37]

**Comment by Dimezis** [comment]
Create a rounded drawable, as usual, set it as a `background`.
And do
`blurView.setOutlineProvider(ViewOutlineProvider.BACKGROUND);`
`blurView.setClipToOutline(true);`

**Comment by ScuAdam** [comment]
It works, Thanks for your help :) 👍  @Dimezis

**Comment by mauriciogior** [comment]
This crashes my app:
java.lang.NoClassDefFoundError: android.view.ViewOutlineProvider
        at com.estudiotrilha.inevent.fragment.PrinterModeSelectorFragment.onViewCreated(PrinterModeSelectorFragment.java:120)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1430)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3231)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3181)

**Comment by Dimezis** [comment]
@mauriciogior because it's API 21, and you are running it <21. Android Studio should give you a warning

**Comment by mauriciogior** [comment]
@Dimezis yeah, thanks. It is a known bug https://issuetracker.google.com/issues/63151548

**Comment by mauriciogior** [comment]
@Dimezis so for API < 21, no round corners?

**Comment by Dimezis** [comment]
For sure it's possible to have rounded corners, but you'll have to fork the lib and implement it manually.
You can draw blurred bitmap with a mask, or draw a transparent rounded corners on top of it. Pretty simple

**Comment by mauriciogior** [comment]
Here is a solution for anyone wondering how to do it (just wrap `BlurView` inside `CornerView`:

```java
public class CornerView extends FrameLayout {
    private Path path = new Path();
    private float radius = 0;

    public CornerView(Context context) {
        super(context);
    }

    public CornerView(Context context, AttributeSet attrs) {
        super(context, attrs);

        TypedArray a = context.obtainStyledAttributes(attrs, R.styleable.CornerView);

        try {
            radius = a.getDimension(R.styleable.CornerView_radius, 0);

        } finally {
            a.recycle();
        }
    }

    @Override
    protected void onSizeChanged(int w, int h, int oldw, int oldh) {
        super.onSizeChanged(w, h, oldw, oldh);
        RectF rect = new RectF();

        path.reset();
        rect.set(0, 0, w, h);
        path.addRoundRect(rect, radius, radius, Path.Direction.CW);
        path.close();
    }

    @Override
    protected void dispatchDraw(Canvas canvas) {
        int save = canvas.save();
        canvas.clipPath(path);
        super.dispatchDraw(canvas);
        canvas.restoreToCount(save);
    }

}
`

**Comment by Dimezis** [comment]
@danielwilson1702 post your drawable

**Comment by Dimezis** [comment]
My blind guess you're using per-corner radius, which is not supported.
```XML
<corners android:bottomLeftRadius="..."
        android:bottomRightRadius="..."
        android:topLeftRadius="..."
        android:topRightRadius="..."/>
```

And you should use just
```XML
 <corners android:radius="..." />
```

**Comment by danielwilson1702** [comment]
Brilliant thank you, I wouldn't have thought of that 💯

**Comment by kingnightdrifter** [comment]
Hi Dimezis,

Can you please tell me where I am getting wrong   

`   <eightbitlab.com.blurview.BlurView
            android:id="@+id/topBlurView"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:elevation="0dp"
            android:outlineProvider="paddedBounds"
            app:blurOverlayColor="@android:color/transparent"
            tools:targetApi="lollipop">

            <com.travelist.hi5.custom.CenteredToolbar
                android:id="@+id/toolbar"
                android:layout_width="match_parent"
                android:layout_height="?attr/actionBarSize"
                android:elevation="0dp"
                android:paddingEnd="@dimen/margin_7dp"
                app:layout_collapseMode="pin"
                app:layout_scrollFlags="scroll" />
        </eightbitlab.com.blurview.BlurView>`

Also I am Using in MainActivity.Class


` topBlurView = findViewById(R.id.topBlurView);

        topBlurView.setOutlineProvider(ViewOutlineProvider.BACKGROUND);
        topBlurView.setClipToOutline(true);`

**Comment by kingnightdrifter** [comment]
> Here is a solution for anyone wondering how to do it (just wrap `BlurView` inside `CornerView`):
> 
> ```java
> public class CornerView extends FrameLayout {
>     private Path path = new Path();
>     private float radius = 0;
> 
>     public CornerView(Context context) {
>         super(context);
>     }
> 
>     public CornerView(Context context, AttributeSet attrs) {
>         super(context, attrs);
> 
>         TypedArray a = context.obtainStyledAttributes(attrs, R.styleable.CornerView);
> 
>         try {
>             radius = a.getDimension(R.styleable.CornerView_radius, 0);
> 
>         } finally {
>             a.recycle();
>         }
>     }
> 
>     @Override
>     protected void onSizeChanged(int w, int h, int oldw, int oldh) {
>         super.onSizeChanged(w, h, oldw, oldh);
>         RectF rect = new RectF();
> 
>         path.reset();
>         rect.set(0, 0, w, h);
>         path.addRoundRect(rect, radius, radius, Path.Direction.CW);
>         path.close();
>     }
> 
>     @Override
>     protected void dispatchDraw(Canvas canvas) {
>         int save = canvas.save();
>         canvas.clipPath(path);
>         super.dispatchDraw(canvas);
>         canvas.restoreToCount(save);
>     }
> 
> }
> ```

Can you please send the attr class also

**Comment by kostiaalio** [comment]
@Dimezis Is it possible to have only some of the corners rounded? For example, only top left and top right?

P.S. Дякую за лібу!

**Comment by Dimezis** [comment]
Overall it's possible if you subclass the BlurView and mask those corners manually.

But it's not possible with the XML drawable and **clipToOutline**, because it doesn't support complex shapes.

**Comment by nauhalf** [comment]
> Overall it's possible if you subclass the BlurView and mask those corners manually.
> 
> But it's not possible with the XML drawable and **clipToOutline**, because it doesn't support complex shapes.

@Dimezis is there any example to achieve this? I am really weak with canvas and paint API.

**Comment by baiyunwujin** [comment]
If other method can't solve your problem, you can try to use this class to replace
```
import android.content.Context
import android.graphics.Canvas
import android.graphics.Path
import android.graphics.RectF
import android.util.AttributeSet
import androidx.core.graphics.withClip
import eightbitlab.com.blurview.BlurView

class BlurView @JvmOverloads constructor(
    context: Context,
    attrs: AttributeSet? = null,
    defStyleAttr: Int = 0
) : BlurView(context, attrs, defStyleAttr) {

    private var mWidth = 0
    private var mHeight = 0
    private var mRadiusArray: FloatArray? = null
    private var mRectF = RectF(0f, 0f, 0f, 0f)
    val mPath = Path()

    override fun onSizeChanged(w: Int, h: Int, oldw: Int, oldh: Int) {
        super.onSizeChanged(w, h, oldw, oldh)
        mWidth = w
        mHeight = h
        updateClipPath()
        mRectF = RectF(0f, 0f, w.toFloat(), h.toFloat())
    }

    fun setRadiusArray(radiusArray: FloatArray?) {
        mRadiusArray = radiusArray
        updateClipPath()
    }

    private fun hasCornerRadius(): Boolean {
        return mRadiusArray != null && mRadiusArray?.any { it != 0f } == true
    }

    private fun updateClipPath() {
        val path = mPath
        val rectF = mRectF
        val w = mWidth
        val h = mHeight
        path.reset()
        val radiusArray = mRadiusArray ?: return
        if (w == 0 || h == 0 || !hasCornerRadius()) {
            return
        }
        rectF.set(0f, 0f, w.toFloat(), h.toFloat())
        path.addRoundRect(
            rectF, radiusArray,
            Path.Direction.CW,
        )
    }

    override fun dispatchDraw(canvas: Canvas) {
        val save = canvas.save()
        canvas.clipPath(mPath)
        super.dispatchDraw(canvas)
        canvas.restoreToCount(save)
    }

    override fun draw(canvas: Canvas) {
        if (hasCornerRadius()) {
            canvas.withClip(mPath) {
                super.draw(canvas)
            }
        } else {
            super.draw(canvas)
        }
    }


}
```
and use it like `bottomView.setRadiusArray(floatArrayOf(br, br, br, br, 0f, 0f, 0f, 0f))`
