### ISSUE TITLE
RenderScript v8 incompatible with other support libraries.

### ISSUE THREAD

**Issue by vxhviet** [Dimezis/BlurView#39]
Hi,

I just want to notice you a little problem with Android Studio 2.3. See this [SOF](http://stackoverflow.com/questions/42581963/all-com-android-support-libraries-must-use-the-exact-same-version) for the long version. The short version is Android Studio requires explicit declaration of which library is currently used. As most of our support lib is currently at 25.2.0, it would require a matching 25.2.0 `RenderScript` version. However, the latest build tool version, which provides the `RenderScript` lib, is sitting at 25.0.2 which throws a Gradle incompatible error.

As our application supports minSDK 18, I just need to switch to the native version of `RenderScript` instead. Hopefully this issue will get resolved soon.

**Comment by Dimezis** [comment]
Hey,

From what I understood, I have no options to fix this from my side.
Android Studio beta channel already got this issue fixed, as far as I know.

**Comment by vxhviet** [comment]
Yeah, I understand this is out of the project's scope. Just wanna put this down for anyone looking for a quick fix. Hopefully the fix will come to the stable channel soon.
Thanks for your time though.

**Comment by Dimezis** [comment]
I guess I will move to native Renderscript, probably there's no point of using support version

**Comment by Dimezis** [comment]
Please check out 1.3.3 version, support RenderScript dependency is now optional.
Default implementation of BlurAlgorithm is now no-op.

There are 2 standard algorithms right now - RenderScriptBlur (which uses native RS) and
SupportRenderScriptBlur - compile 'com.eightbitlab:supportrenderscriptblur:1.0.0'
