### ISSUE TITLE
Why enabled RenderScript by default? 

### ISSUE THREAD

**Issue by PureDark** [Dimezis/BlurView#42]
I see this in the constructor of `BlockingBlurController`
```java
this.blurAlgorithm = new RenderScriptBlur(blurView.getContext(), true);
```

I use my custom implementation to avoid apk size going up due to libRSSupport.so, but BlurView instantiated a RenderScript implementation no matter whether I have set a custom implementation, and causing crash.

I think maybe the default implementation should not be instantiated in the constructor , and check before if a custom implementation is set.

**Comment by Dimezis** [comment]
Good point, I'll handle this soon

**Comment by Dimezis** [comment]
Please check out 1.3.3 version, support RenderScript dependency is now optional.
Default implementation is now no-op.

There are 2 standard algorithms right now - `RenderScriptBlur` (which uses native RS) and 
`SupportRenderScriptBlur` - `compile 'com.eightbitlab:supportrenderscriptblur:1.0.0'`
