### ISSUE TITLE
CPU Load

### ISSUE THREAD

**Issue by ghost** [Dimezis/BlurView#44]
Hello,

I have a bug when loading Blurview, the CPU load goes up and does not go down.

When I load my application I have to wait until the end before "blurView.setupWith".

When I load a Fragment, the CPU load goes up and I have to re-execute "blurView.setupWith" to see the CPU load return to normal.

If I load an activity, the cpu load returns to normal and I can make a return without seeing it go up.

Sometimes even by running "blurView.setupWith" the CPU remains blocked at high load.

I put a link to my application to see more clearly https://github.com/Old-Geek/Musique

I code just out of curiosity but I confess not to be very gifted, I do not find the problem so I fill it with DIY.

**Comment by Dimezis** [comment]
Hey,

I'll check this out soon, thanks

**Comment by Dimezis** [comment]
I've tested your app, but I can't see any CPU load issues.
If you have more clear steps or some specific device or OS version, it would really help

**Comment by Dimezis** [comment]
@Old-Geek 
This might help you: 
https://github.com/Dimezis/BlurView/issues/51

**Comment by Old-Geek** [comment]
Thank you :)
