### ISSUE TITLE
All com.android.support libraries must use the exact same version specification

### ISSUE THREAD

**Issue by JavaMachine** [Dimezis/BlurView#46]
Hello,

Android studio gives me warning,

> All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes) Found versions 25.4.0, 25.0.3. Example include com.android.support.animated-vector-drawable:25.4.0 and com.android.support.renderscript:25.0.3

my build.gradle:

> dependencies { 
>     compile 'com.android.support:appcompat-v7:25.4.0'
>     compile 'com.android.support:support-v13:25.4.0'
>     compile 'com.android.support:animated-vector-drawable:25.4.0'
>     compile 'com.android.support:recyclerview-v7:25.4.0'
>     compile 'com.android.support:design:25.4.0'
>     //BlurView
>     compile 'com.eightbitlab:supportrenderscriptblur:1.0.0'
>     compile 'com.eightbitlab:blurview:1.3.3'
> }

I could not find in your source code, where "com.android.support.renderscript:25.0.3" is used.

How can I resolve issue?

**Comment by Dimezis** [comment]
There's no explicit import of Support Renderscript. Only this in `com.eightbitlab:supportrenderscriptblur` artifact:
```
defaultConfig {
        renderscriptTargetApi 25
        renderscriptSupportModeEnabled true
 }
```
And it's actually Google's problem, that they don't provide the same version of Support Renderscript lib.
Meanwhile you can use regular Renderscript if your API is 17+.
