### ISSUE TITLE
Force BlurView to redraw?

### ISSUE THREAD

**Issue by caleb-allen** [Dimezis/BlurView#47]
I have a blur view in a drawer, and when the drawer is pulled out the blur is static. Is there a way for me to force a redraw every frame, during the drawer action?

I've tested with the demo, and can see that layers underneath a blurview work.

Any help would be greatly appreciated.

Regards,

Caleb

**Comment by Dimezis** [comment]
Can you please provide a code snippet or a repo, so I can help you faster?

**Comment by Dimezis** [comment]
@caleb-allen any updates?

**Comment by caleb-allen** [comment]
This was user error. I was calling windowBackground() on a bad view so my view wasn't updating
