### ISSUE TITLE
CPU load on Activity start

### ISSUE THREAD

**Issue by lordjebe** [Dimezis/BlurView#51]
I'm noticing a ~10-15% CPU usage on starting up an activity with a BlurView in it. The CPU use continues until the orientation changes, the screen is turned off or other configuration change happens. Also opening up another activity stops the CPU use.

The CPU usage happens only when I have BlurView being initialized in an activity's onCreate. Here's my project: https://github.com/lordjebe/beaconproject

**Comment by Dimezis** [comment]
Which device and OS are you using?
I don't see any CPU load on my devices

**Comment by lordjebe** [comment]
Android 6.0.1, and this happens on every physical device I've tried it on. Virtual devices don't seem to have the same problem.

**Comment by Dimezis** [comment]
Ok, got it. 

When I remove loading_progressBar from your loading_indicator.xml layout, it starts to work fine.
It seems like progress bar forces BlurView to redraw itself constantly, causing CPU load, even though the parent of progress bar is invisible.

**Comment by lordjebe** [comment]
You're right, that works. However, when I remove the FAB's from the layout, it also stops the CPU usage even if the loading indicator is not removed.
