### ISSUE TITLE
couldn't find "libruntimecore_java.so" when adding another library

### ISSUE THREAD

**Issue by salihyalcin** [Dimezis/BlurView#52]
Hello :)

First of all really thank you for creating such a great library. My issue is when I using your library with [Esri Android SDK ](https://developers.arcgis.com/android/latest/guide/install-and-set-up.htm) library get confused and app crash. 

SO I googled it and found [this question](https://geonet.esri.com/thread/168679#comment-570682) related with this issue and [this ](https://stackoverflow.com/questions/30782848/how-to-use-32-bit-native-libraries-on-64-bit-android-device) question for solving issue. 

So I could not affort to decide which filter that I have to use for solving issue. 

Thanks for helpings

Here is my log : 

`08-25 10:53:57.369 31674-31674/com.example.saltun.blurviewlibdemo E/AndroidRuntime: 
Caused by: java.lang.UnsatisfiedLinkError: 
dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.saltun.blurviewlibdemo-1/base.apk",
 zip file "/data/app/com.example.saltun.blurviewlibdemo-1/split_lib_dependencies_apk.apk", 
 zip file "/data/app/com.example.saltun.blurviewlibdemo-1/split_lib_slice_0_apk.apk", 
 zip file "/data/app/com.example.saltun.blurviewlibdemo-1/split_lib_slice_1_apk.apk", 
 zip file "/data/app/com.example.saltun.blurviewlibdemo-1/split_lib_slice_2_apk.apk", 
 zip file "/data/app/com.example.saltun.blurviewlibdemo-1/split_lib_slice_3_apk.apk",
 zip file "/data/app/com.example.saltun.blurviewlibdemo-1/split_lib_slice_4_apk.apk", 
 zip file "/data/app/com.example.saltun.blurviewlibdemo-1/split_lib_slice_5_apk.apk", 
 zip file "/data/app/com.example.saltun.blurviewlibdemo-1/split_lib_slice_6_apk.apk", 
 zip file "/data/app/com.example.saltun.blurviewlibdemo-1/split_lib_slice_7_apk.apk", 
 zip file "/data/app/com.example.saltun.blurviewlibdemo-1/split_lib_slice_8_apk.apk", 
 zip file "/data/app/com.example.saltun.blurviewlibdemo-1/split_lib_slice_9_apk.apk"],
 nativeLibraryDirectories=[/data/app/com.example.saltun.blurviewlibdemo-1/lib/arm64, /data/app/com.example.saltun.blurviewlibdemo-1/base.apk!/lib/arm64-v8a, 
 /data/app/com.example.saltun.blurviewlibdemo-1/split_lib_dependencies_apk.apk!/lib/arm64-v8a, 
 /data/app/com.example.saltun.blurviewlibdemo-1/split_lib_slice_0_apk.apk!/lib/arm64-v8a, 
 /data/app/com.example.saltun.blurviewlibdemo-1/split_lib_slice_1_apk.apk!/lib/arm64-v8a,
 /data/app/com.example.saltun.blurviewlibdemo-1/split_lib_slice_2_apk.apk!/lib/arm64-v8a, 
 /data/app/com.example.saltun.blurviewlibdemo-1/split_lib_slice_3_apk.apk!/lib/arm64-v8a, 
 /data/app/com.example.saltun.blurviewlibdemo-1/split_lib_slice_4_apk.apk!/lib/arm64-v8a, 
 /data/app/com.example.saltun.blurviewlibdemo-1/split_lib_slice_5_apk.apk!/lib/arm64-v8a, 
 /data/app/com.example.saltun.blurviewlibdemo-1/split_lib_slice_6_apk.apk!/lib/arm64-v8a, 
 /data/app/com.example.saltun.blurviewlibdemo-1/split_lib_slice_7_apk.apk!/lib/arm64-v8a, 
 /data/app/com.example.saltun.blurviewlibdemo-1/split_lib_slice_8_apk.apk!/lib/arm64-v8a, 
 /data/app/com.example.saltun.blurviewlibdemo-1/split_lib_slice_9_apk.apk!/lib/arm64-v8a, 
 /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]] couldn't find "libruntimecore_java.so"
`

**Comment by Dimezis** [comment]
Hi, 

Are you using support version of RenderScript or the native one?

I believe native version should have x64 build on your device, so this issue won't be happening

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by salihyalcin** [comment]
I am using support version of RenderScript 

here is my gradle file 

`pply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    buildToolsVersion "26.0.1"
    defaultConfig {
        applicationId "com.example.saltun.blurviewlibdemo"
        minSdkVersion 17
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        renderscriptTargetApi 26 //must match target sdk and build tools, 23+
        renderscriptSupportModeEnabled true
        ndk {
            abiFilters "arm64-v8a"
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {

    ext {
        // Uygulamada kullanılan kütüphane versiyonları
        esriAndroidSDKVersion = '100.1.0'
    }


    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile "com.esri.arcgisruntime:arcgis-android:$esriAndroidSDKVersion"
    compile 'com.sothree.slidinguppanel:library:3.3.1'
    compile 'com.android.support:design:25.3.1'
    compile 'com.eightbitlab:blurview:1.3.3'
    compile 'com.eightbitlab:supportrenderscriptblur:1.0.0'
    testCompile 'junit:junit:4.12'
}
`

**Comment by Dimezis** [comment]
You don't have to use support version if you have min sdk 17.

You can remove these lines

compile 'com.eightbitlab:supportrenderscriptblur:1.0.0'

renderscriptTargetApi 26 
renderscriptSupportModeEnabled true

Also these filters should do the trick:

abiFilters "armeabi", "armeabi-v7a", "x86", "mips"

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by salihyalcin** [comment]
I removed lines but when I remove this lines. Blur functionality isnt working :(

**Comment by Dimezis** [comment]
Did you set RenderScript blur algorithm though?

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by salihyalcin** [comment]
Here is my MainActivity too 

```
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        BlurView blurView = (BlurView) findViewById(R.id.blurView);
        MapView mapView = (MapView) findViewById(R.id.mapViewxx);

        float bvRadius = 24.9f;

        final View decorView = getWindow().getDecorView();
        //Activity's root View. Can also be root View of your layout (preferably)
        final ViewGroup rootView = decorView.findViewById(android.R.id.content);
        //set background, if your root layout doesn't have one
        final Drawable windowBackground = decorView.getBackground();

        blurView.setupWith(rootView)
                .windowBackground(windowBackground)
                .blurAlgorithm(new RenderScriptBlur(this))
                .blurRadius(bvRadius);
        MapViewUtils.changeBaseMap(this, "Harita", mapView);
        MapViewUtils.mapRemoveIconAndText(mapView);
        MapViewUtils.setMapEnvelope(mapView);

    }
}

```

**Comment by Dimezis** [comment]
Closing since no clear actions to perform
