### ISSUE TITLE
How to blur over a blurview?

### ISSUE THREAD

**Issue by KnIfER** [Dimezis/BlurView#54]

**Comment by KnIfER** [comment]
In a blurview,i have a listview,and i add items to listview dynamically.however when i scroll items beneath a second blurview,the second blur view seems make no response to items.

**Comment by KnIfER** [comment]
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
	xmlns:android="http://schemas.android.com/apk/res/android"
	xmlns:tools="http://schemas.android.com/tools"
	xmlns:app="http://schemas.android.com/apk/res-auto"
	android:layout_height="match_parent"
	android:layout_width="match_parent"
	android:id="@+id/main_layout"
	style="@style/AppTheme">

	<RelativeLayout
		android:layout_height="match_parent"
		android:layout_width="match_parent"
		android:id="@+id/mainRelativeLayout2">

		<ImageView
			android:layout_height="match_parent"
	
			android:layout_width="match_parent"
			android:src="@drawable/image_4"
		
			android:scaleType="centerCrop"/>
		
		<eightbitlab.com.blurview.BlurView
			android:id="@+id/FIRST"
			android:layout_width="match_parent"
			android:layout_height="match_parent"
			android:outlineProvider="bounds"
			app:blurOverlayColor="#00ffffff"
			tools:targetApi="lollipop">

			<LinearLayout
				android:layout_height="match_parent"
				android:layout_width="match_parent"
				android:orientation="vertical">

				<ListView
					android:layout_height="wrap_content"
					android:layout_width="match_parent"
					android:id="@+id/main_list"
					android:layout_marginTop="50dp"/>

			</LinearLayout>

		</eightbitlab.com.blurview.BlurView>

	</RelativeLayout>

	<RelativeLayout
		android:layout_height="50dp"
		android:layout_width="match_parent"
		android:id="@+id/mainRelativeLayout1">

		<Button
			style="?android:attr/buttonBarButtonStyle"
			android:layout_height="match_parent"
			android:layout_width="wrap_content"
			android:text="Run"
			android:layout_alignParentLeft="true"
			android:id="@+id/run_button"/>

		<Button
			style="?android:attr/buttonBarButtonStyle"
			android:layout_height="match_parent"
			android:layout_width="wrap_content"
			android:text="Option"
			android:layout_alignParentRight="true"
			android:id="@+id/option_button"
			android:onClick="OnOptionButtonClick"/>

	</RelativeLayout>

	
	<eightbitlab.com.blurview.BlurView
		android:id="@+id/SECOND"
		android:layout_width="wrap_content"
		android:layout_height="wrap_content"
		android:elevation="3dp"
		app:blurOverlayColor="#00ffffff"
		android:layout_centerHorizontal="true"
		android:layout_alignParentBottom="true"
		tools:targetApi="lollipop">
			
		<Button
			android:layout_height="wrap_content"
			android:layout_width="wrap_content"
			android:text="rghggrt"
			style="?android:attr/buttonBarButtonStyle"
			android:id="@+id/extractor"/>

	</eightbitlab.com.blurview.BlurView>

</RelativeLayout>




2 BLURVIEW:FIRST and SECOND

**Comment by Dimezis** [comment]
What's your goal in the first place? Which part of the content you want to be blurred? A list? Then don't put it inside the BlurView.
One BlurView can't blur something what's in another BlurView.

You should use one BlurView only,

**Comment by KnIfER** [comment]
Oh I see..
