### ISSUE TITLE
Blur not happening in FrameLayout which is above a TextureView

### ISSUE THREAD

**Issue by premacck** [Dimezis/BlurView#56]
I have an activity, in which I am playing a video in background (in a TextureView), and I am populating fragments on top of that using a FrameLayout.
here is my layout:

`<RelativeLayout
    android:id="@+id/container"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <TextureView
        android:id="@+id/welcome_video"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:adjustViewBounds="true" />

    <eightbitlab.com.blurview.BlurView
        android:id="@+id/blur_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:blurOverlayColor="@color/colorTranslucentBgMainActivity">

        <FrameLayout
            android:id="@+id/main_fragment_container"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

    </eightbitlab.com.blurview.BlurView>

</RelativeLayout>`

And here's how I am setting up the blurView:

       `settings = blurView.setupWith(rootView)

        .windowBackground(getWindow().getDecorView().getBackground())

        .blurAlgorithm(new RenderScriptBlur(this))

        .blurRadius(20);

     blurView.setBlurEnabled(false);`

Now there are two fragments (A and B) which I populate in "main_fragment_container" (one at a time)
Initially I don't want any blur when on fragment A (I am using `blurView.setBlurEnabled(false);` when setting up the blurView)
But when I navigate to fragment B, then I want blur with animation as described in [https://github.com/Dimezis/BlurView/issues/9#issuecomment-227092499](url)
and for that I am using:

       `blurView.setBlurEnabled(true);

        blurView.updateBlur();

        final ValueAnimator animator = ValueAnimator.ofFloat(1f, 15f);

        animator.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {

            @Override

            public void onAnimationUpdate(ValueAnimator animation) {

                settings.blurRadius((float) animator.getAnimatedValue());

                blurView.updateBlur();

            }

        });

        animator.setDuration(5000);
        animator.start();`

But it is not having any effect on the FrameLayout when switching between fragments.
Does blurView work with TextureView? Or is there anything wrong with my code?

**Comment by Dimezis** [comment]
Unfortunately it's impossible to blur `TextureView` with `BlurView`, because `TextureView` requires a hardware-accelerated canvas to be drawn on. So `BlurView` can't draw it on it's own software canvas to blur it later.

I'm currently working on a different implementation, which might have this possibility for API 23+, but it's still in progress and I'm not sure when I'll be able to release it.

**Comment by premacck** [comment]
So if I play the video in VodeoView or SurfaceView, will I be able to do it?

**Comment by Dimezis** [comment]
No, SurfaceView draws on a separate surface, and you can't draw it's content on a canvas, so BlurView can't obtain it's content.
And VideoView is just a SurfaceView basically.

**Comment by premacck** [comment]
So, is there any workaround for this situation?

**Comment by Dimezis** [comment]
No, there are no libraries on Android capable of doing that, for the reasons I already mentioned. I mean without access to all internals of a particular implementation of video renderer.

Of course, you can create your own renderer, store frames in OpenGL texture and blur it with a shader, but I doubt you'd like to go for that solution.

**Comment by premacck** [comment]
Yeahm that's not probably worth all that work, for now, I am just applying dark tint over the FrameLayout, and waiting for the "different implementation" in BlurView.
