### ISSUE TITLE
Conflicting OS Dependent Files 

### ISSUE THREAD

**Issue by searchy2** [Dimezis/BlurView#58]
*Library does not seem to work with Gradle v3 projects due to conflicting OS files. Please review and merge PR #57 which solves the problem. 

>Error:Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForDebug'.
> More than one file was found with OS independent path 'lib/arm64-v8a/libRSSupport.so'

**Comment by Dimezis** [comment]
Merged, thank you!
