### ISSUE TITLE
Blur Background Position Incorrect

### ISSUE THREAD

**Issue by searchy2** [Dimezis/BlurView#63]
Amazing library! I'm trying to use it in my AlertView and PermissionsDialogue libraries. Unfortunately, I've ran into a bit of a problem with fragments and the view being duplicated. 
![maxthonsnap20180209163018](https://user-images.githubusercontent.com/19896174/36053344-01bbfdc8-0db7-11e8-9db3-7db44cd8ab38.png)
You can see in the picture above that the same background position is displaying on both the top and bottom BlurViews. The BlurView position calculation is not doing anything. 
![maxthonsnap20180209163705](https://user-images.githubusercontent.com/19896174/36053511-8acd6610-0db7-11e8-9454-95af1fa92b27.png)
Another example with only 1 BlurView to illustrate the problem.
![maxthonsnap20180209162938](https://user-images.githubusercontent.com/19896174/36053528-98bd8a84-0db7-11e8-9505-7b5f9394b4a8.png)
What's puzzling is that the BlurView works correctly when the size is smaller.

Any ideas? I am so close to getting the blur working! 

My repo w/ code here -> https://github.com/searchy2/CustomPermissionsDialogue/tree/blur

**Comment by Dimezis** [comment]
Thanks for report and example project, will dig into this soon and hopefully fix it

**Comment by searchy2** [comment]
@Dimezis I'd be very appreciative if you could take a look. I have such high hopes because the blur background works on one of them because the height is shorter. So something about the height causes the positioning to be wrong.

**Comment by Dimezis** [comment]
I think I know what's the problem, will make an update in couple of days with new API to handle your case.

**Comment by searchy2** [comment]
@Dimezis Please let me know if I can help. I have a few libraries that would really benefit from this feature so it would be great if you share what's wrong.

**Comment by Dimezis** [comment]
The issue is that dialog's relative position is always x=0, y=0.
So for the dialog I need to do special handling using `getLocationInWindow()` to know the proper position for blur. 
I'll release this soon, I just need a bit of free time

**Comment by Dimezis** [comment]
For now you can check out and test your scenario on branch 1.4.0
https://github.com/Dimezis/BlurView/tree/v1.4.0

**Comment by searchy2** [comment]
Bless you! You are such an amazing person! 

![maxthonsnap20180222120241](https://user-images.githubusercontent.com/19896174/36555689-555d2c2a-17c8-11e8-9fef-dfc9fde72f8d.png)

If you can create an release, I'll be able to release my libraries too. Thank you so much!

**Comment by searchy2** [comment]
One more note, `windowIsFloating` must be set to false in your dialogue style or the positioning will be incorrect. 

`<item name="android:windowIsFloating">false</item>`

Library works perfectly!
