### ISSUE TITLE
Loop

### ISSUE THREAD

**Issue by wangshuaiyuan** [Dimezis/BlurView#68]
It seems that the code is a loop call.how did you do that the "draw() " method is not loop called. 

 private ViewTreeObserver.OnPreDrawListener mOnPreDrawListener = new ViewTreeObserver.OnPreDrawListener() {
        @Override
        public boolean onPreDraw() {
            invalidate();
            return true;
        }
    };

**Comment by Dimezis** [comment]
Your code will be executed infinitely, that's true.
But BlurView has a check to skip own invalidate calls.

https://github.com/Dimezis/BlurView/blob/master/library/src/main/java/eightbitlab/com/blurview/BlockingBlurController.java
