### ISSUE TITLE
Crash on destroy

### ISSUE THREAD

**Issue by ilandblack** [Dimezis/BlurView#7]
Sometimes crashes with
Attempt to invoke virtual method 'void android.support.v8.renderscript.Allocation.destroy()' on a null object reference at eightbitlab.com.blurview.RenderScriptBlur.destroy(RenderScriptBlur.java:74)

**Comment by Dimezis** [comment]
Thank you for report, releasing the fix now.

**Comment by ilandblack** [comment]
Thanks. Now I'm getting
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Bitmap.recycle()' on a null object reference at eightbitlab.com.blurview.DefaultBlurController.destroy(DefaultBlurController.java:251)

**Comment by Dimezis** [comment]
Ok, I see.
What causes the fact that destroy is called before the initialization?
Is your View has visibility GONE?

**Comment by Dimezis** [comment]
Should be fine now in 1.0.4

**Comment by ilandblack** [comment]
Yes. I'm periodically switching gone/visible.
