### ISSUE TITLE
Help needed with RecyclerView list item setup

### ISSUE THREAD

**Issue by monowar1993** [Dimezis/BlurView#70]
I user blurview in recycleview item to hide some contents. But as I scrolldown the blur gets fade and lastly the blur effect is just vanished.
`<RelativeLayout
            android:id="@+id/layoutContent"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_below="@+id/tvName"
            android:layout_marginTop="@dimen/size_12dp">

            <LinearLayout
                android:id="@+id/layoutContentChild"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:orientation="vertical">

                <ImageView
                    android:id="@+id/ivImage"
                    android:layout_width="@dimen/size_150dp"
                    android:layout_height="@dimen/size_150dp"
                    android:layout_gravity="center_horizontal"
                    android:contentDescription="@string/poll_image"
                    android:scaleType="fitCenter"
                    android:src="@drawable/img_profile_pic_rect" />

                <TextView
                    android:id="@+id/tvPoll"
                    fontPath="fonts/Roboto-Bold.ttf"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_marginEnd="@dimen/size_16dp"
                    android:layout_marginStart="@dimen/size_16dp"
                    android:layout_marginTop="@dimen/size_8dp"
                    android:gravity="center"
                    android:text="@string/report_reason_inappropriate"
                    android:textColor="@color/text_color"
                    android:textSize="@dimen/text_size_18sp" />

            </LinearLayout>

            <ProgressBar
                android:id="@+id/progressBar"
                android:layout_width="@dimen/size_50dp"
                android:layout_height="@dimen/size_50dp"
                android:layout_centerInParent="true"
                android:indeterminateTint="@color/colorAccent" />

            <eightbitlab.com.blurview.BlurView
                android:id="@+id/blurView"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_alignBottom="@+id/layoutContentChild"
                android:layout_alignParentTop="true"
                app:blurOverlayColor="@color/white_transparent_2">

                <TextView
                    fontPath="fonts/Roboto-Bold.ttf"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center"
                    android:drawableTop="@drawable/ic_eye"
                    android:gravity="center_horizontal"
                    android:text="@string/tap_here_to_view"
                    android:textColor="@color/white"
                    android:textSize="@dimen/text_size_20sp"
                    android:textStyle="bold" />

            </eightbitlab.com.blurview.BlurView>

        </RelativeLayout>`

This my item.

`
val layoutContent = helper.getView<RelativeLayout>(R.id.layoutContent);
val blurView = helper.getView<BlurView>(R.id.blurView);
blurView.setupWith(layoutContent)
                .windowBackground(layoutContent.background)
                .blurAlgorithm(SupportRenderScriptBlur(mContext))
                .blurRadius(25f)
                .setHasFixedTransformationMatrix(true);
`

and this from my adapter.

**Comment by monowar1993** [comment]
I've checked in your demo project. Recyclerview item blur is not working properly. Please check the codes bellow. Please do give a solution. 

> Adapter code
https://pastebin.com/scp0EExY

> Item Code
https://pastebin.com/AmkTpmqa

**Comment by Dimezis** [comment]
First of all, tell me what do you expect from your setup. 
You're setting up a BlurView with list item's root. Also you're setting `.windowBackground(layoutContent.background)`, although your `layoutContent` has no background.

This setup doesn't make any sense, and I'm not sure what exactly do you want to achieve.
What part of UI do you want to blur?

**Comment by monowar1993** [comment]
Sorry for late. I was in a vacation. I would like to have an image that is blurred inside a recyclerview. And when I tap then blurred view will be gone and real image will be reveled. Thats what I want.

**Comment by Dimezis** [comment]
Ok, then just try to set some actual windowBackground. Like in demo project

**Comment by monowar1993** [comment]
Why should I put window background? I want to load the image in a imageview and then your library will make a blurred view of it. Please just test your demo with static images on recyclerview. When it loads for the first time its okay. But when I scroll down and then scroll back up again the blurred effect is gone. That is the issue.

**Comment by Dimezis** [comment]
You should put it because your `layoutContent` has no background, and in this case each new frame overlaps with previous one. Because BlurView is not clearing the canvas on each drawing, to avoid it when it's not needed. 
That can be changed, but for now you can just set windowBackground as I already said. 
And it works fine in demo project.
