### ISSUE TITLE
How to remove the blur ? 

### ISSUE THREAD

**Issue by AhmadHossam10** [Dimezis/BlurView#75]
How to remove the blur after I put it on a view ? 
Also the blur by default gives white color I want it to be blurry transparent how to achieve this ? 

@Dimezis can you help ?

**Comment by Dimezis** [comment]
Instead of spamming me with issues on github, you could spend 5 minutes reading Javadoc to BlurView and Readme.md.
`blurView.setBlurEnabled`.
Clarify your second question.

**Comment by AhmadHossam10** [comment]
"blurview.setBlurEnabled" is not mentioned in the Readme.md

about the second question when I start the blur it gives me a blurry white color I want to change to another color.

![12](https://user-images.githubusercontent.com/30598877/40326928-52080342-5d41-11e8-92e7-def83c5b4fb8.png)

P.S using blurOverlayColor colors the whole screen and don't blur it.

**Comment by Dimezis** [comment]
This is the color drawable you're passing in `windowBackground(someDrawable)`. So you can pass a different one

**Comment by AhmadHossam10** [comment]
@Dimezis

**Comment by Dimezis** [comment]
Look for the issue in your code, `setBlurEnabled` works fine. 
Probably you're initializing BlurView again accidentally.

**Comment by AhmadHossam10** [comment]
now you are answering just to appear that you are helpful ?!!!

**Comment by Dimezis** [comment]
I'm answering because I have a time. You were waiting for an answer less than a day and already started whining. I can answer in a minute, in a day or in a week, learn how to wait and respect other's time.
