### ISSUE TITLE
Remove Blur

### ISSUE THREAD

**Issue by AndyKeane** [Dimezis/BlurView#76]
I am using blur when a user enters his data and when I process them I set blurView.setBlurEnabled(false) if the user wants to submit another data the blur is rendered again.
@Dimezis

**Comment by Dimezis** [comment]
You think if you'll create a new account to post the same issue twice, I'll help you faster?

**Comment by AhmadHossam10** [comment]
I don't know what you are talking about, anyways you don't wanna help don't help. This is not a contest it's your library and you must support you don't want to it's up to you

**Comment by Dimezis** [comment]
I **must**? It's open source, I don't owe anything to anyone. Especially to spammers who think I **must** help with any question they have in blink of an eye. 
You are not even able to post a code sample or provide a proper description of your problem, and you say I **must** help you?
