### ISSUE TITLE
Bleeding edge on top of soft navigation bar

### ISSUE THREAD

**Issue by rahulsh12** [Dimezis/BlurView#77]
Full screen blur with a dark layout below the blur layout, gives bleeding edges at the top of the soft navigation bar.

**Comment by rahulsh12** [comment]
![screenshot_20180711-113546 2](https://user-images.githubusercontent.com/11179459/42586906-c2c5e484-84fe-11e8-98ac-a29c0c3e6a86.png)

**Comment by Pranoy1c** [comment]
Is there any solution to this? Same issue with the other 500px blurring library too.

**Comment by Dimezis** [comment]
Sorry for extremely long delay on this. 
Could you guys post how you set up the BlurView? What's the root layout?

**Comment by Dimezis** [comment]
https://github.com/Dimezis/BlurView/issues/82#issuecomment-428840634
Explanation and fix
