### ISSUE TITLE
BlurView Sliding Up

### ISSUE THREAD

**Issue by chetu97** [Dimezis/BlurView#78]
I am sliding up the blurview just like control center in IOS, but as the blurview slides up it already has the blurred image of what it is supposed to blur.

**Comment by Dimezis** [comment]
Attach the code of animation, BlurView setup and lib version.

**Comment by chetu97** [comment]
On Button Click - 
mBlurView.setVisibility(View.VISIBLE);
mBlurView.startAnimation(mSlideUp);

Animation XML -
<?xml version="1.0" encoding="utf-8"?>
<set xmlns:android="http://schemas.android.com/apk/res/android" >

    <translate
        android:duration="1000"
        android:fromYDelta="100%"
        android:toYDelta="0" />
</set>

Setup - 
View decor_view = getWindow().getDecorView();
        ViewGroup root_view = (ViewGroup) decor_view.findViewById(R.id.relative_layout);
        Drawable windowBackground = decor_view.getBackground();
        mBlurView.setupWith(root_view).windowBackground(windowBackground).blurAlgorithm(new RenderScriptBlur(MainActivity.this)).blurRadius(RADIUS);

**Comment by Dimezis** [comment]
Seems like it doesn't work with XML animations. 
Can you do something like 
```Java
blurView.animate().translationY(x)
```
instead?

**Comment by chetu97** [comment]
I will try that, Thank you very much
