### ISSUE TITLE
Problems with ImageView as background

### ISSUE THREAD

**Issue by tato469** [Dimezis/BlurView#8]
I am trying to set the blur effect at the bottom of my screen and set an image as background but the result that I get is:

https://s31.postimg.org/gx452v7rf/test_blur_1.png

**There is any bug with imageView?**

Here is the XML that I tested:

    <?xml version="1.0" encoding="utf-8"?>
    <FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.esmonissimo.monissimotienda.LoginActivity">

    <ImageView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/image_background_login"
        android:src="@mipmap/login_background"
        android:scaleType="centerCrop" />

    <eightbitlab.com.blurview.BlurView
        android:id="@+id/blurView"
        android:layout_width="match_parent"
        android:layout_height="50dp"
        android:layout_gravity="bottom"
        app:blurOverlayColor="@color/colorOverlay">

    </eightbitlab.com.blurview.BlurView>
    </FrameLayout>

and the activity:

    public class LoginActivity extends AppCompatActivity {

    @BindView(R.id.blurView) BlurView blurView;
    @BindView(R.id.image_background_login) ImageView imageView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_login);

        ButterKnife.bind(this);

        final float radius = 16f;

        final View decorView = getWindow().getDecorView();
        //Activity's root View. Can also be root View of your layout
        final View rootView = decorView.findViewById(android.R.id.content);
        //set background, if your root layout doesn't have one
        final Drawable windowBackground = decorView.getBackground();

        blurView.setupWith(rootView)
                .windowBackground(windowBackground)
                .blurAlgorithm(new RenderScriptBlur(this, true)) //Preferable algorithm, needs RenderScript support mode enabled
                .blurRadius(radius);
    }
    }

**Note:** if I set the blurView setup with:
     
     android:layout_width="match_parent"
     android:layout_height="match_parent"

Shows all the image blurred.

**Comment by Dimezis** [comment]
Hi.
Can't reproduce with the given setup.
Are there any other specific settings?
Is the ImageView visible in visual editor preview?
Is it visible without BlurView in hierarchy?
Can you send that login_background image?

**Comment by tato469** [comment]
Hello seems that was a memory error because the image size. But is weird because the app worked good.
