### ISSUE TITLE
Blur RecycleView viewholders, where the viewholders contains BlurView.

### ISSUE THREAD

**Issue by anonymCC** [Dimezis/BlurView#80]
```xml
**A recycleview item looks so:**

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:card_view="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:blurkit="http://schemas.android.com/tools"
    android:longClickable="true">
    <android.support.v7.widget.CardView
        android:id="@+id/holder_card"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_margin="10dp"
        app:cardBackgroundColor="@color/transparent"
        app:cardCornerRadius="14dp">
        <eightbitlab.com.blurview.BlurViewPro
            android:id="@+id/blurLayout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:focusable="true"
            app:blurOverlayColor="@color/colorOverlay"/>
...
    </android.support.v7.widget.CardView>
</LinearLayout>


**activity_main.xml**

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/relative_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    <RelativeLayout
        android:id="@+id/blur_root"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        tools:ignore="UselessParent">
        <FrameLayout
            android:id="@+id/background_image"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@drawable/background_original"/>
            <android.support.v7.widget.RecyclerView
                android:id="@+id/device_recycler_view"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:scrollbars="none"/>
            <eightbitlab.com.blurview.BlurView
                android:id="@+id/fragment"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:focusable="true"
                android:clickable="true"
                android:visibility="gone" />
    </RelativeLayout>
</RelativeLayout>

I set up the BlurView(@id/fragment) so:
        RelativeLayout blurRoot = findViewById(R.id.blur_root);
        BlurView blurView = findViewById(R.id.fragment);
`       blurView.setVisibility(View.VISIBLE);
        blurView.setupWith(blurRoot)
                .setBlurAutoUpdate(true)
                .blurAlgorithm(new RenderScriptBlur(this)
                .blurRadius(23f)
                .setBlurAutoUpdate(true);

I want to blur, the recycleview items, but only the views outsides the _blurLayout_ get blurred(and the background).

Is it possible?

**Comment by Dimezis** [comment]
I didn't quite get what do you want to achieve. Why do you need BlurView both in ViewHolders and over a RecyclerView? You want to blur each item separately or you want to have 1 big BlurView over the RecyclerView?

If you want to blur only items (not sure though what exactly you want to blur in items), you need to set up the BlurViews in ViewHolders with a different root layout (`holder_card `). Now I see the setup for only 1 BlurView, which is not in ViewHolder

**Comment by anonymCC** [comment]
Thanks for your answer.

My purpose is to have a big BlurView (`fragment`) over the RecycleView.

I create the ViewHolders BlurView (`blurLayout`) in the `onBindViewHolder()` method so:
```java
 FrameLayout rootView = ((MainActivity)mContext).findViewById(R.id.background_image);
 setupWith(rootView)
                .blurAlgorithm(new RenderScriptBlur(mContext))
                .blurRadius(23f)
                .setOverlayColor(colorOverlay)
                .setBlurAutoUpdate(true);
```
 and it works perfect, but when I create the BlurView (`fragment`), only the background get blurred, and the ViewHolder layouts outside the `blurLayout` BlurView.

**Comment by Dimezis** [comment]
BlurView can't blur things inside of other BlurView if that's what you're asking.

**Comment by anonymCC** [comment]
I do not want to blur things inside the BlurView. I want to blur the ViewHolders BlurView. Like in the Apple's Home app.
Have a look at this video: [http://www.youtube.com/watch?v=AWVKAclBJXQ&t=4m2s](url) (after longpress).

**Comment by Dimezis** [comment]
Did you check sample app? I have a BlurView there that blurs ViewHolders

**Comment by aravindtechzar** [comment]
I add blurview for recyclerview adapter for every recyclereview item blur in android fragment.

for android fragment with recyclerview adapter this codes does not work.

internal inner class ViewHolder(itemView : View): RecyclerView.ViewHolder(itemView){
        val announceTitle = itemView.title_text
        val announceTime = itemView.announce_time_ago
        val announceDescription = itemView.announce_description
        val announceImage = itemView.announce_image
        val announceParent = itemView.announce_item_parent_linear

}
  override fun onBindViewHolder(holder: RecyclerView.ViewHolder, position: Int) {
viewHolder.blurImage.setupWith(viewHolder.announceParent)
                .setBlurRadius(radius)
                .setBlurEnabled(true)
                .setBlurAlgorithm(RenderScriptBlur(context))
                .setBlurRadius(radius)
                .setHasFixedTransformationMatrix(true)
                .setBlurAutoUpdate(true)

}
