### ISSUE TITLE
Can you add a scaling blur api?

### ISSUE THREAD

**Issue by Anzhi-Meiying** [Dimezis/BlurView#81]
Hello, can you add an api that can be scaled and then blur?

Because the number of blurs is too large, it will cause lagging...

> https://github.com/wasabeef/Blurry

 I very much like Blurry sampling api, it can solve this problem, unfortunately, this library can not be real-time fuzzy.

**Comment by Dimezis** [comment]
Actually it's already downscaled before blur, I've picked the best quality/performance ratio I could find. So I don't think there's a point in exposing this as API

**Comment by Anzhi-Meiying** [comment]
Thanks answer~
`blurView.setupWith(rootView)
           .windowBackground(windowBackground)`

setupWith & windowBackground can I not set it? Because I think this is a bit of a hassle，and what is the use of this?

I want to get the answer, thank you~

**Comment by Dimezis** [comment]
Those methods have Javadoc plus comments in the example project and readme.md. You can find the answers there.
`setupWith` is obligatory to call, `windowBackground` is optional, depends on your setup.

**Comment by Anzhi-Meiying** [comment]
This solved my doubts, thank you very much!
