### ISSUE TITLE
White artifact inside BlurView, possible sampling outside screen

### ISSUE THREAD

**Issue by harounhajem** [Dimezis/BlurView#82]
Hi! 

I get this artifact, strange white color, when adding Blur to an item in the bottom of the screen. The artifact disappears when i push the bottom item 5dp above the bottom line.
I would guess BlurView is sampling, the white color, outside the screen. 
![bug](https://user-images.githubusercontent.com/17148955/46675757-6bb57600-cbdf-11e8-8727-05c247f3b556.png)

**Comment by Dimezis** [comment]
Hi, please post your BlurView setup

**Comment by harounhajem** [comment]
It's added to a framelayout with this code 

`final Drawable windowBackground = ((Activity) context).getWindow()
                .getDecorView().getBackground();

        final ViewGroup root = (ViewGroup) ((Activity) context).findViewById(android.R.id.content);

        blurView.setupWith(root)
                .windowBackground(windowBackground)
                .blurAlgorithm(new SupportRenderScriptBlur(context))
                .blurRadius(18f /*fixed radius*/)
                .setHasFixedTransformationMatrix(false);

        ViewGroup.LayoutParams params = new LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,
                ViewGroup.LayoutParams.MATCH_PARENT);

        addView(blurView, 0, params); 

And this the item that holds BlurView to the bottom of the screen. 
 
`
<FrameLayout
        android:id="@+id/bottom_bar"
        android:layout_width="match_parent"
        android:layout_height="142dp"
        android:layout_alignParentBottom="true"
        android:gravity="center"
        android:orientation="horizontal"
        android:background="@drawable/shadow_top" />
`

My screen size is  1280x720  9",  I'm running Android Pie, but this issue was also found in Oreo.

**Comment by Dimezis** [comment]
Don't set it up with android.R.id.content, pass your activity root

**Comment by harounhajem** [comment]
It didn't work. I used android.R.id.content following the method deceleration in the library.  
I'm now dependency injecting the **_topView_** into the _**bottomBar**_ (BlurView-Parent)
Still doesn't work, I suspect it is sampling outside screen. 


![bild](https://user-images.githubusercontent.com/17148955/46767076-22028380-cce4-11e8-92c1-3622f9e53214.png)
........
`mBottomBar.activateBlurView(findViewById(R.id.topView), this);`
........


    public boolean activateBlurView(@NonNull ViewGroup root, @NonNull Context context) {

        final Drawable windowBackground = ((Activity) context).getWindow()
                .getDecorView().getBackground();

        blurView.setupWith(root)
                .setFrameClearDrawable(windowBackground)
                .setBlurAlgorithm(new SupportRenderScriptBlur(context))
                .setBlurRadius(18f /*fixed radius*/)
                .setBlurAutoUpdate(true)
                .setHasFixedTransformationMatrix(false);

        ViewGroup.LayoutParams params = new LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,
                ViewGroup.LayoutParams.MATCH_PARENT);

        addView(blurView, 0, params);

        return true;
    }

**Comment by harounhajem** [comment]
It's working now =D 
The issue is found in this line 

  final Drawable windowBackground = ((Activity) context).getWindow()
            .getDecorView().getBackground();

It was containing a bit of white line, probably a pixel from outside the screen, just guessing.

**Comment by Dimezis** [comment]
Cool, glad you resolved it, and thanks for letting me know

**Comment by harounhajem** [comment]
Thanks for the support and the time.
