### ISSUE TITLE
Get the BlurView layout with rounded corners

### ISSUE THREAD

**Issue by samesl** [Dimezis/BlurView#83]
I'm trying to add radius to the BlurView in my projects to have a rounded-corner blurry layout but the radius doesn't get applied on the layout. I'm wondering how would it be possible to get it like that ? thanks and here's my xml code 

 <eightbitlab.com.blurview.BlurView
        android:id="@+id/storeBlurView"
        android:layout_width="0dp"
        android:layout_height="88dp"
        android:layout_marginStart="10dp"
        android:layout_marginEnd="10dp"
        android:layout_marginBottom="8dp"
        android:background="@drawable/rounded_corner"
        app:layout_constraintBottom_toTopOf="@+id/storeItemBlurView"
        app:layout_constraintDimensionRatio=""
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:blurOverlayColor="@color/transparent_white_fifty">

**Comment by Dimezis** [comment]
See https://github.com/Dimezis/BlurView/issues/37

**Comment by samesl** [comment]
thanks so much for your super quick response!!!
