### ISSUE TITLE
BlurView crashing on API 19 with AndroidX

### ISSUE THREAD

**Issue by ernest-p** [Dimezis/BlurView#86]
Sample crashing on Android API 19 simulator after migrating to AndroidX

A/libc: Fatal signal 11 (SIGSEGV) at 0x00000000
[blurview-crash-log.txt](https://github.com/Dimezis/BlurView/files/2632907/blurview-crash-log.txt)

https://github.com/ernest-p/BlurView

**Comment by Dimezis** [comment]
I guess support version of Renderscript is broken with AndroidX

**Comment by ernest-p** [comment]
There is bug filled in AndroidX bug tracked, added my info as well

https://issuetracker.google.com/issues/119582492

**Comment by Dimezis** [comment]
The id doesn't necessarily reflect the number of the bug. 
And I'm pretty sure that vast majority of those issues are irrelevant, duplicate or just plain bullshit

**Comment by Dimezis** [comment]
Closing since Support version of RenderScript is pretty much obsolete
