### ISSUE TITLE
How to implement blur view on Popup Menu? ^^

### ISSUE THREAD

**Issue by lanhuaguizha** [Dimezis/BlurView#87]

**Comment by Dimezis** [comment]
What's exactly your problem? What have tried and what didn't work?

**Comment by lanhuaguizha** [comment]
I wanted to achieve this effect, and outlook's right-click menu has a blurring effect
![mail_transientcontextmenu](https://user-images.githubusercontent.com/9106780/54085199-235cd880-4376-11e9-9c8c-332e505b74fa.png)

**Comment by Dimezis** [comment]
I understand, I mean have you tried to do something and what's exactly not working?

**Comment by lanhuaguizha** [comment]
thks. I am looking for the source code of androd system, but I can't find it how to load the menu.xml parsing view into popup window. So with no result, I think I need to find where the popupmenu view loads into the popupwindow
