### ISSUE TITLE
Question: Animate blur effect

### ISSUE THREAD

**Issue by boichukDA** [Dimezis/BlurView#9]
Can you add posibility or show example (i can't find it by myself) to animate BlurView from default view state(no blur) to blur with radius 16f. I tried with ObjectAnimator.valueOf and animate redius but that's not what I was looking for

**Comment by Dimezis** [comment]
I guess I can add a separate method for changing the radius, for now you can go with something like:

`final BlurView.ControllerSettings settings = blurView.setupWith(rootView);`

```
        final ValueAnimator animator = ValueAnimator.ofFloat(1f, 16f);
        animator.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
            @Override
            public void onAnimationUpdate(ValueAnimator animation) {
                settings.blurRadius((float) animator.getAnimatedValue());
                blurView.updateBlur();
            }
        });
        animator.setDuration(5000);
        animator.start();
```

Note that StackBlur doesn't support those smooth float radius changes, so please use this approach only with RenderScriptBlur.

**Comment by boichukDA** [comment]
Ok. Thanks for Your reply

**Comment by KnIfER** [comment]
ControllerSettings is removed?

**Comment by KnIfER** [comment]
looks strange now..

**Comment by Dimezis** [comment]
@knifer what do you mean? You can change blur radius directly on the BlurView now

**Comment by KnIfER** [comment]
newer version looks different

**Comment by Dimezis** [comment]
What exactly is different?

**Comment by EmmanuelMess** [comment]
How is this done now?
